### ISSUE TITLE
comment Tag has maximum length tttool should care of

### ISSUE THREAD

**Issue by DAD405** [entropia/tip-toi-reveng#100]
While trying to create own project discovered the Fact that the Comment Line has a maximum of 49 characters. (including spaces, without leading Space after >comment:<

At the moment the following willl happen (tttool-win32-1.3)
if a comment exceeds this limit the gme file will be created but the resulting file will not be recocnized by the tiptoi-pen-

request 1:
tttool should at least warn about this problem and ask to abort or maybe shorten the text to apropriate maxsize

additional suggestions:
the example yaml files should mention Limits in Tags
the examples should contain tags like the speak funktions or the language Tag

**Comment by nomeata** [comment]
> While trying to create own project discovered the Fact that the Comment Line has a maximum of 49 characters.
That is certainly not the case. My guess is that your editor is wrapping the lines, or something else went wrong.

What’s your edior? Can you attach a broken yaml file? Can you test the file at http://www.yamllint.com/?

**Comment by DAD405** [comment]
Editor ist Notepad++
its not the yaml-comments which are limited
it looks like the gme-comment line is limited

Following will result in an broken .gme:
    media-path: media/gig_%s
    speak: null
    language: null
    welcome: 1,2
    product-id: 824
    comment: Ein erster Tiptoi-Versuch zur Kommunion von Maureen
    scripts:
      4719:
      - P(0)
    init: $0:=1
    scriptcodes: null

the following will resulkt in an gme which is recognized:
    media-path: media/gig_%s
    speak: null
    language: null
    welcome: 1,2
    product-id: 824
    comment: Ein erster Tiptoi-Versuch zur Kommunion von Maure
     scripts:
      4719:
      - P(0)
    init: $0:=1
    scriptcodes: null

Gibt es hier auf Github keine code-tags?
auf Wunsch kann ich sowohl eine funktionierende als auch eine nicht funbktionierende gme zur Verfügung stellen (sorry abut the german)

**Comment by nomeata** [comment]
>  it looks like the gme-comment line is limited

Ah, jetzt verstehe ich. Danke!

Ja, das sollte tttool wohl abfangen. Mach ich bei Gelegenheit!

49 macht übrigens Sinn: Laut https://github.com/entropia/tip-toi-reveng/blob/master/GME-Format.md sind da 64 Bytes für Kommentarlänge (1Byte), Kommentar, Datum (8 Byte) und Sprache (6 Byte). 64 - 1 - 8 - 6 = 49.

> Gibt es hier auf Github keine code-tags?
Doch, mit dreifachen backticks oder mit vier spaces eingerückt.

**Comment by DAD405** [comment]
Hmm, das mit den vier spaces hatte ich oben gemacht.
Ich nehm nochmal die Accents wegen der optik

Hauptsache das Problem ist erkannt.

**Comment by DAD405** [comment]
Jetzt hab ich das sus Versehen geclosed. Ist ja noch Open

**Comment by nomeata** [comment]
Passiert mir auch immer :-)
