### ISSUE TITLE
Windows: `tttool media -d` bringt `usage`, wenn man ein Verzeichnis mit Leerzeichen angibt

### ISSUE THREAD

**Issue by stgermain1** [entropia/tip-toi-reveng#101]
Das tttool bringt, trotz Anführungsstrichen unter Windows die `usage` aus anstatt in das entsprechende
Verzeichnis die Meida-Dateien zu exportieren.

`tttool.exe media -d "F:\ischniertshauer\OOPortable\Documents\KowHow\tipToi\tip-toi-reveng\media\008\00512 - Das Geheimnis der Zahleninsel\20100901\" Geheimnis_der_Zahleninsel.gme`
bringt 
`Usage: tttool.exe [options] command .... ` 

Erst ein ersetzen der Leerzeichen, macht den Export der medien:
`F:\ischniertshauer\OOPortable\Documents\KowHow\tipToi\tip-toi-reveng>tttool.exe media -d F:\ischniertshauer\OOPortable\Documents\KowHow\tipToi\tip-toi-reveng\media\008\00512-Das_Geheimnis_der_Zahleninsel\20100901 Geheimnis_der_Zahleninsel.gme
Audio Table entries: 965
Dumped sample 0 as F:\ischniertshauer\OOPortable\Documents\KowHow\tipToi\tip-toi-reveng\media\008\00512-Das_Geheimnis_der_Zahleninsel\20100901/Geheimnis_der_Zahleninsel_0.ogg`

**Comment by nomeata** [comment]
Der Code im `tttool` sieht eigentlich gut aus. Ich kenne mich nicht mit der Windows-Eingabeaufforderung aus, und wie man dort Leerzeichen korrekt escapet.

Laut http://superuser.com/questions/279008/how-do-i-escape-spaces-in-command-line-in-windows-without-using-quotation-marks könntest du statt `".."` auch versuchen, vor jedes Leerzeichen ein `^` zu schreiben.

**Comment by stgermain1** [comment]
Gelöst: Verwende nun die 8.3 Notation, die über `dir /x` angezeigt werden kann.
