### ISSUE TITLE
include von yaml-Dateien

### ISSUE THREAD

**Issue by stgermain1** [entropia/tip-toi-reveng#103]
Für größere Aufgaben und Projekte,
kann es (wie in meinem Fall) gut sein, wenn
man die Scripte in verschiedenen Dateien ablegen kann,
die dann beim `tttool  play` und beim `tttool assemble` zusammengebunden werden.

`scripts:`
`    # includings:`
`     - include: "Pfad-zur-Include-Datei"`

Ist diese nicht vorhanden, wird mit einem Text
 `Fehler:nn line:xx - Konnte include Datei: "Angabe" nicht finden. ` 
abgebrochen.

**Comment by nomeata** [comment]
Gute Idee. Allerdings nicht so ganz einfach. Man würde ja gern "include" an beliebigen Stellen im Dokument verwenden können. Aber ich verwende ja einen fertigen YAML-Parser, der kann das nicht.

Bzw, er kann es, aber wohl nicht so dass Teile einer Liste (etwa scripts) mit weiteren Teilen aus der Datei zusammengefügt werden können.

Vielleicht gibt es Möglichkeiten, aber da muss ich erstmal drüber nachdenken.

**Comment by nomeata** [comment]
Ich bezweifle dass ich das demnächst angehen werde, und es steht ja jedem frei selbst die YAML-Dateien zu generieren. Ich nehm es mal von der Liste der offenen Issues.

**Comment by uli42** [comment]
Muss ja nicht der eigentliche Parser machen. Ginge ja zum Beispiel
auch so: http://www.linuxtopia.org/online_books/linux_tool_guides/the_sed_faq/sedfaq4_025.html

Uli
