### ISSUE TITLE
openBinaryFile: resource exhausted (Too many open files)

### ISSUE THREAD

**Issue by HamOP** [entropia/tip-toi-reveng#104]
Hallo,

zuerst einmal danke für dieses klasse Tool!

Ich habe ein Original-gme-Datei zerlegt (yaml extrahiert und media extrahiert). Wenn ich sie nun versuche, wieder zu assemblen, bekomme ich o.g. Fehlermeldung. Mache ich etwas falsch?

**Comment by HamOP** [comment]
Ich habe es selbst hingekriegt: Es liegt an MacOS (ich hatte das vergessen, zu erwähnen).

Folgende Befehle beheben das Problem:
sudo sysctl -w kern.maxfiles=20480
ulimit -S -n 2048

Hilfreicher Artikel hier: http://krypted.com/mac-os-x/maximum-files-in-mac-os-x/

**Comment by nomeata** [comment]
Gut dass es einen Work-Around gibt, aber es sollte auch ohne sowas funktionieren. Welche Einstellung ist den Default unter OS X? Und wieviele Medien-Dateien sind das?

**Comment by HamOP** [comment]
Es sind knapp 1000 Dateien, er bricht aber immer bei der 363. Datei ab. Gemäß des Artikels liegt es wohl daran, dass unter OS X die kern.maxfiles standardmäßig auf ca. 12000 stehen. Auf welchem Wert die maximal offenen Files für das Terminal standardmäßig stehen (ulimit), kann ich nicht sagen, mein einer Rechner meldet "unlimited", den anderen hatte ich vorher auf 2048 gestellt, weil er vorher die o.g. Fehlermeldung brachte.
Anscheinend liegt es daran, dass MacOS im Hintergrund indiziert und sich auf die 1000 ogg-Files stürzt, sobald man sie extrahiert hat.

**Comment by nomeata** [comment]
Ok, das heißt ich hab keinen Grund zur Annahme dass `tttool` fälschlicherweise zu viele Dateien öffnet und offen offen hält, ohne sie zu schließen, und dass ich auch gar nichts gegen dieses Problem machen kann?

**Comment by HamOP** [comment]
Sieht so aus. Offensichtlich passiert das unter MacOS häufiger, auch bei anderen Haskell-Programmen.

**Comment by nomeata** [comment]
Ok, danke. Ich schließe das dann erstmal.
