### ISSUE TITLE
assemble meldet alle fehlenden audiofiles in einer Liste

### ISSUE THREAD

**Issue by stgermain1** [entropia/tip-toi-reveng#106]
beim 'assemble' wird eine fehlende Audiodatei nach der anderen als fehlend
ausgeworfen:
'Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Alle Rechte vorbehalten.

F:\tip-toi-reveng\myProjects\rechenzwerg>"..\..\tttool (2).exe" assemble rechenkobold.yaml
Could not find any of these files:
.\./sounds/n42.wav
.\./sounds/n42.ogg
.\./sounds/n42.flac
.\./sounds/n42.mp3

F:\tip-toi-reveng\myProjects\rechenzwerg>"..\..\tttool (2).exe" assemble rechenkobold.yaml
Could not find any of these files:
.\./sounds/n48.wav
.\./sounds/n48.ogg
.\./sounds/n48.flac
.\./sounds/n48.mp3

F:\tip-toi-reveng\myProjects\rechenzwerg>"..\..\tttool (2).exe" assemble rechenkobold.yaml
Could not find any of these files:
.\./sounds/n49.wav
.\./sounds/n49.ogg
.\./sounds/n49.flac
.\./sounds/n49.mp3

F:\tip-toi-reveng\myProjects\rechenzwerg>"..\..\tttool (2).exe" assemble rechenkobold.yaml
Could not find any of these files:
.\./sounds/n54.wav
.\./sounds/n54.ogg
.\./sounds/n54.flac
.\./sounds/n54.mp3'

Kann das nicht als Eine Liste der Dateien kommen? 
Und ohne Endung, damit es übersichtlicher ist, könnte 
die Liste auch in 4 Spalten aus gegeben werden.

**Comment by nomeata** [comment]
Richtig, das hat mich auch schon gestört. Zur Zeit ist der Code an der Stelle nicht sehr vorbildlich strukturiert, und diese Fehlermeldung ist im Grunde ein relativ unkoordiniertes Abbrechen des Programms. Werd ich mir mal bei Gelegenheit anschauen, auch wenns keine hohe Priorität hat.
