### ISSUE TITLE
play modus mit "OID-Liste"?

### ISSUE THREAD

**Issue by stgermain1** [entropia/tip-toi-reveng#107]
Im Moment teste ich mein 1x1-Spiel. Dabei durchlaufe ich viele Aufgaben/Lösungen-OID's. Gut wäre es, wenn man den Play-Modus mit einer Liste in der Form:
`tttool play *.yaml "OID1,OID2,OID3....OIDn,OIDn+1` als Startwerte angeben kann.
Nach dem Ablauf der Liste wartet das `tttool play`dann auf die nächste OID.

**Comment by nomeata** [comment]
Ja, wäre denkbar. Auch in der Variante ohne dass er danach auf weitere Eingaben wartet, dann kann man manche Programmabläufe komplett Skripten und zum Testen durchlaufen lassen.

Unter Linux kannst du das übrigens auch so skripten:
```
(echo OID1; echo OID2; echo OID3; cat) | tttool play foo.yaml
```
Vermutlich geht ähnliches auch unter Windows irgendwie.

**Comment by stgermain1** [comment]
Dann muss ich das auch unter cygwin machen ;)
K.A. wie das unter win. geht ;)

**Comment by ToniMahagoni** [comment]
Kann man das unter Windows nicht zeilenweise aus ner Textdatei holen?
xy.exe<textdatei.txt

https://www.microsoft.com/resources/documentation/windows/xp/all/proddocs/en-us/redirection.mspx?mfr=true

**Comment by nomeata** [comment]
Ah, das geht natürlich auch (wenn auch nicht dass man danach weitermachen kann)

**Comment by stgermain1** [comment]
jepp, das funktioniert gut für mich. Danke für die Hinweise ....

**Comment by ToniMahagoni** [comment]
Guter Punkt!

Unter Windows könnte auch das gehen:
type input.txt | tttool play *.yaml

Müsste mal einer testen, ob man dann noch weitere Eingaben machen kann.

**Comment by stgermain1** [comment]
geht auch, danke
