### ISSUE TITLE
Save OID PNG files with correct DPI

### ISSUE THREAD

**Issue by jovermann** [entropia/tip-toi-reveng#109]
Currently the generated OID PNG files are saved with 72 DPI. Saving them with the actually intended DPI (600 or 1200) would help when printing them from certain programs.

(It may be that they are currently saved without any DPI information and that my applocations (Mac OS X Preview and Gimp) just display the monitor default of 72 DPI.)

This is a minor issue.

**Comment by nomeata** [comment]
This is only recently possible with the library we are using, see  https://github.com/Twinside/Juicy.Pixels/issues/93 and https://github.com/Twinside/Juicy.Pixels/commit/866ef77022d24be52641eeb61b9fefe325896c3a

But now that it’s there, we should definitely use it! Thanks for the suggestion.
