### ISSUE TITLE
Make firstObjectCode unique for product id.

### ISSUE THREAD

**Issue by jovermann** [entropia/tip-toi-reveng#110]
In order to make the object codes unique for different projects (and different from existing Ravensburger products, as far as possible) it would be nice if the firstObjectCode could be changed. Two modes would be useful.
1. Manually set the firstObjectCode, or
2. by default the firstObjectCode could be derived somehow from the product id.

The latter could be done by multiplying the product id with (sqrt(5)-1)/2 (Goldener Schnitt) to avoid collisions as far as possible.

**Comment by nomeata** [comment]
I don’t follow. The object codes are usually fine to overlap, sometimes you event want that (when changing the sounds of a ravensburger product) and in general they do not matter. Am I missing something?

**Comment by jovermann** [comment]
Well, I am new to this and maybe my assumption how Ravensburger assigns object code to different products are wrong. I agree that in general they do not matter.

But here is the problem and the motivation:

1. You open Book A(firstObjectId=4716) and activate it by pointing the pen at the start button. Book A works.
2. You open Book B(firstObjectId=4716) and forget to point at the start button. Pointing the pen at the plane makes a deep cow Muuhhhhhhhh! :-)

This is not what happens when you use the Ravensburger book. You virtually always (I only have tried by accident, not consistently) get the message 'please point at the start button before using this book' which means the OID code is not in the currently active GME file. So I blindly assume (without verifying) that they use different codes for every book, as far as possible.

Using different objects codes for different projects just makes this start button message come up more often. If there are collisions this is completely harmless, but if for example we build all our books starting from the same object id the pen will not be able to detect that a book was not activated. As we will probably just have 10 books with 20 codes in them each and we have 15000 object codes we could avoid collisions altogether. To make it less complex and less data driven I would simply derive the starting point from the one things which is different for different projects anyway, the product id.

This all is of course only for the symbolic script entries. Numeric entries should of course be left untouched.

Cheers,
Johannes

**Comment by nomeata** [comment]
I see your point now, and I like the idea of deterministically deriving the code range from the product ID.

I’d choose a large number of codes expected for each project (maybe 800), thus get a list of possible firstObjectIDs (1000, 1800, 2600, ...), and then simply lookup the project id in this list (project id modulo size of that list). This way, successive projects have no overlap and only every ~20th project shares the codes.

Slight improvement would be to extend the list even more, by shifting the start in the second round (1400, 2200, 3000) and variations of that.

I’ll look into some day, but not with high priority.

**Comment by jovermann** [comment]
Thanks for your response. Yes, that would be very useful, and agreed, not high priority.

If we want to remove all the constants (800, offset for second round) we can choose a big offset X (can be in the thousands, around 800 is fine as well) which is most distant from any fraction of the length on the code-list we can choose from, and assign codes with wrap around and simply multiply the product id with X and then modulo length of list. (The number which is most distant from _any_ fraction is (sqrt(5)-1/2).

I am happy to look into this as well, perhaps starting off with being able to hardcode firstObjectId in the YAML file. Assigning to myself. 

My biggest obstacle is that my Miranda knowledge from ... gosh ... 20 years ago (I did not realize I got old) are insufficient to write Haskell code. I can figure out most stuff intuitively, but lines like 'code2RawCode code = knownRawCodes V.!? fromIntegral code' puzzle me! :-)

Interesting! I like learning new stuff!

Cheers,
Johannes

Am 01.10.2015 um 10:37 schrieb Joachim Breitner <notifications@github.com>:

> I see your point now, and I like the idea of deterministically deriving the code range from the product ID.
> 
> I�d choose a large number of codes expected for each project (maybe 800), thus get a list of possible firstObjectIDs (1000, 1800, 2600, ...), and then simply lookup the project id in this list (project id modulo size of that list). This way, successive projects have no overlap and only every ~20th project shares the codes.
> 
> Slight improvement would be to extend the list even more, by shifting the start in the second round (1400, 2200, 3000) and variations of that.
> 
> I�ll look into some day, but not with high priority.
> 
> �
> Reply to this email directly or view it on GitHub.
> 

-- 
Johannes.Overmann@joov.de (http://joov.de)
Fichtenstr. 5, 79194 Gundelfingen, +49 761 556 3222

**Comment by jovermann** [comment]
I don't seem to be able to assign my own reported issue to myself, :-) Feel free to assign it to myself.

**Comment by nomeata** [comment]
It looks only people with commit rights can be assigned. But you are welcome to work on it without being the asignee :-)

**Comment by jovermann** [comment]
Ack! :-)

**Comment by nomeata** [comment]
With #111 done, is there anything left to do in this ticket?

**Comment by jovermann** [comment]
This is done and works in practice here. Can be closed. Oh! I have a close button! :-)
