### ISSUE TITLE
Bug in tttool play command

### ISSUE THREAD

**Issue by HorstBock** [entropia/tip-toi-reveng#112]
Hello,
my compiled gme file doesn't work in the tttool player. I got this output:

State now: $0=2 $1=1 $2=1 $3=101 $4=4 $5=2 $6=1 $8=4 $16=4
Next OID touched? 1425
Executing:  $3>=100? $4:=1 J(9001)
Executing:  $3==101? $2==$4? $16:=$4 J(9020)
Executing:  $16==1? $1+=1 $0-=1 P(5) J(9021)
Playing audio sample 5
None of these lines matched!
$0> 0? $3:=101 J(9013)
$0==0? $3:=100 P(15)
State now: $0=1 $1=2 $2=1 $3=101 $4=1 $5=2 $6=1 $8=4 $16=1
Next OID touched?

The variable $0 is 1 but the line $0>0 does not match. Why? If I copy the gme file to the tiptoi pen it jumps to 9013. I'm using the tttool version 1.4

**Comment by nomeata** [comment]
There was simply some code missing; next release will contain the fix.

Are you able to build from source or do you need a new release to get the fix?

**Comment by HorstBock** [comment]
Thanks for the fix. I'm using tttool on Windows. I don't know how to build it from source. Can you please provide a new release for Windows?

**Comment by nomeata** [comment]
Done, version 1.5.

**Comment by HorstBock** [comment]
Thanks for the new release. It's working with version 1.5.
