### ISSUE TITLE
whats about the .rav files ?? gibt es schon Versuche eigene .rav Files zu erzeugen?? 

### ISSUE THREAD

**Issue by spezi** [entropia/tip-toi-reveng#115]
we produce some litle audio stuff together with our kids. It would be wonderful to play it on the tiptoy pen ..

Wir Produzieren kleine Hörspiele mit unseren Kindern und es wäre grandios wenn man die auf den TipToy Stift übertragen könnte ..

has anybody looked at the .rav file format??
Hat sich das .rav Format schon mal jemand angeschaut??  

Grüße

**Comment by nomeata** [comment]
Bisher nicht. Soweit wir wissen ist da ernsthafte Crypto im Spiel, wird also nicht leicht.

Allerdings kannst du die Hörspiele ja auch in eine GME-Datei packen und einen kleinen Abspiel-Zettel zur Auswahl des Hörspiels drucken. Andere auf der Mailingliste (https://lists.nomeata.de/mailman/listinfo/tiptoi) haben das schon gemacht und helfen dir sicher gern weiter. Frag dort einfach mal!

Ich bin so frei und schließe diesen Issue, weil es nicht direkt ein direkt umsetzbarer Bug-Report oder Feature-Request ans tttool ist.

**Comment by Markthegamer108** [comment]
Hey! Almost a decade after this thread was closed as "serious crypto", the RAV format is fully cracked — the whole thing was reverse engineered from the firmware itself (Thumb-2 disassembly of the 3203L update), not guessed from file pairs.

Repo with the full writeup and a converter: https://github.com/Markthegamer108/rav-tool

The short version, verified byte-exact against original pen files and confirmed by playing custom files on real hardware:

- a `.rav` = 0x20-byte header + encrypted Ogg Vorbis (mono, 22050 Hz)
- header: magic `Ravensburgerv03\0` (16 B), LE u16 `value16`, flag `0xBE`, 8-byte key blob `TABLE[value16 + 3 + i] ^ key8[i]`, trailer `4E 6C 31 F2 65`
- key: `key8 = "CommonI2"`, `checksum = (sum(key8) + value16) & 0xFFFF`, `keystream[i] = TABLE[(checksum + i) & 0xFFF]` (note: mask applies to `checksum + i` only)
- body cipher, op = `pos & 3`: XOR with pass-through rules / SUB / ADD / XOR (no pass-through); keystream index is payload-relative (`(pos - 0x20) & 0x1FF`)
- the 4096-byte `TABLE` sits in the firmware image at file offset `0xDBADC`; decode loop at `0x8DF3B4`, key gen at `0x8DF380`, audio-open at `0x8DFE84`
- decoder quirks worth knowing: Ogg page CRCs are ignored, and oversized Vorbis comment headers (a ~9 KB one from a YouTube rip) make the pen reject the file — keep metadata small or strip it

The tool converts any audio to `.rav`, decrypts stock files, and can extract the key table from any firmware `.upd` (so a different pen generation is a 30-second check away, not a new project). Prebuilt binaries for Windows/macOS/Linux are on the releases page.

Would you be open to me replacing the RAV wiki page stub with the full writeup, or sending a PR? Happy to keep it in the community wiki format.

**Comment by nomeata** [comment]
Interesting that you also reverse engineered the firmware (using AI I presume). Did you see my latest messages on the Tiptoi mailing lists about https://github.com/nomeata/tt-emu and https://github.com/nomeata/tt-firmware-reveng/ ?

**Comment by nomeata** [comment]
Ah, and:

> Would you be open to me replacing the RAV wiki page stub with the full writeup, or sending a PR? Happy to keep it in the community wiki format.

Please do update the wiki!

**Comment by Markthegamer108** [comment]
hey nomeata, the wiki writeup for the RAV file format is basically done, but i dont have write access to the repo so i cant push it myself. could you give me wiki access? or if you prefer, i can paste the whole page here and you can put it up.

**Comment by nomeata** [comment]
The wiki should be editable by anyone

**Comment by Markthegamer108** [comment]
tried that just now, push to the wiki repo still gets a 403: "Permission to entropia/tip-toi-reveng.wiki.git denied to Markthegamer108". it only opens up if you tick the box in Settings - General - Features - Wikis - "Anyone on GitHub can edit this repository's wiki". could you do that? then ill push the page right away.

**Comment by nomeata** [comment]
I only see “Restrict editing to users in teams with push access only Loading ” and that is not checked. Odd. Maybe a github restriction. Or maybe you can only edit using the web interface?

**Comment by Markthegamer108** [comment]
yep, the web UI worked. the RAV page is fully updated now, the whole writeup is up: https://github.com/entropia/tip-toi-reveng/wiki/RAV-file-format

thanks for the quick help!

**Comment by Markthegamer108** [comment]
> Interesting that you also reverse engineered the firmware (using AI I presume). Did you see my latest messages on the Tiptoi mailing lists about https://github.com/nomeata/tt-emu and https://github.com/nomeata/tt-firmware-reveng/ ?

i completely missed those mailing list messages, sorry. just looked at both repos now, this is really cool stuff. the emulator booting the real unmodified firmware is wild, and the ghidra pipeline with the naming databases is exactly the kind of setup i would have loved while doing the rav work.

and yeah, ai did a lot of the heavy lifting here too, you called it.

one thing you might find interesting though: your variants are the 2N (3202MT) and ZC3201, but the rav crack came from the 3203L update, the player pen. that one is not in your list. if you want, i can share the disassembly notes and the .upd, could make a nice third variant for the pipeline.

**Comment by nomeata** [comment]
I'm not sure I'll do that (no pressing need). If your notes can be public, maybe dump them into an issue over there so that we have them if we get to that.

**Comment by Markthegamer108** [comment]
sure, will do. dumping the notes into an issue over there now.
