### ISSUE TITLE
Number games and subgames in "tttool explain", "tttol games" and "tttool export" from 1 to n

### ISSUE THREAD

**Issue by ToniMahagoni** [entropia/tip-toi-reveng#119]
The games are internally numbered from 1 to n.
See gid-lists for gametype 8 e.g. in Bauernhof: gids: [9,10,11]
"tttool explain", "tttool games" lists the games from 0 to n-1.
The YAML-files generated by "tttool export" show G(0) to G(n-1).
It would be helpful, to have the output of the above functions in the same way as the internal games.

The subgames in "tttool explain" are numbered from 0 to n-1, but are internally numbered from 1 to n 
See"playlistlist" which is a "subgamelistlist" for gametype 7 e.g in Bauernhof: playlistlist: [[1,2],[3..6],[7,8]]
"tttool games" doesn't even attach numbers to the subgames. Please add them for subgames counting from 1 to n (and add A and B for gametype 6).

Changing the numbers won't mess anything up, because import of games isn't possible by now.

**Comment by nomeata** [comment]
Sounds reasonable.

But note that the 0 in `G(0)` comes directly from the GME file. So it seems that even the original GME file is inconsistent.

Also I’m not sure whether you can rely on the fact that the `gids` are really game ids, as I don’t know how well that hypothesis is confirmed. Do you know more about that?

I could add lint checks for these cross-references, i.e. that `G(n)` only occurs if there are <n games, and similar (but shifted by 1) in the gid list.

**Comment by ToniMahagoni** [comment]
Interesting. I didn't realize that G(0) is already in the GME.
Yes, I guess I know something more and will soon transfer it from my wiki to your wiki.

For gametype 6 and 7 the subgames are numbered from 1 to n (forget about A and B!).

For gametype 6 the main game of consists of subgames 1 to a and the bonusgame consists of subgames a+1 to n.
Example Bauernhof, game 5 (or 6):
The playlist (which actually is a subgamelist) is [6,7,8,9].
There are 5 regular subgames and 4 bonus subgames (6 to 9), so it's a match.
Example Straßenverkehr, game 4 (or 5):
The subgamelist is [8,9,10].
There are 7 regular subgames and 3 bonus subgames (8-10), another match.
Example Straßenverkehr, game 9 (or 10):
The subgamelist is [11,12].
There are 10 regular subgames and 2 bonus subgames (11 to 12), you get the idea...

For gametype 7 the playlistlist groups subgames so they are played in order.
Example Bauernhof, game 6 (or 7):
The playlistlist (which actually is a subgamelistlist) contains: [[1,2],[3..6],[7,8]]
There are 8 subgames. At the beginning of a game, one of the subsets is chosen randomly.
So if you start with subgame 3, your next subgame will be 4, then subgame 5 and subgame 6.
As soon as the subgame-subset has been played completely, another subset is chosen and played from left to right.

For gametype 8 the gameidlist contains the games you can choose by pointing to the corresponding OID.
Example Bauernhof, game 7 (or 8):
The gidlist is [9,10,11].
The games you actually can play are the games 9-11 (if you count from 1) or 8-10 (if you count from 0).
Example Straßenverkehr, game 7 (or 8):
The gidlist is [9,10]
The games you actually can play are the games 9-10 (if you count from 1) or 8-9 (if you count from 0).

I've got some more stuff in the wiki. Just wait and see! Or see and don't wait.. ;-)

**Comment by nomeata** [comment]
Nice! What and where is “your wiki”?

**Comment by ToniMahagoni** [comment]
Fork

Am 23. Dezember 2015 12:00:19 MEZ, schrieb Joachim Breitner <notifications@github.com>:

**Comment by ToniMahagoni** [comment]
Subgames are now numbered from 1 to n.
Initially I wanted the main- and the bonus-subgames numbered separately, but that's not really a good idea.
The subgamelists always refer to the number of a subgame in the whole list of subgames per game.
So it would be better to number the main-subgames from 1 to m and the bonus-subgames from m+1 to n. Sorry for the change of mind.

How about numbering the games from 1 to n in the games/explain-function and let the script/import/export-function shift the value for G() up and down by 1?

The raw-script would still be zero-based, but who cares?

**Comment by nomeata** [comment]
> How about numbering the games from 1 to n in the games/explain-function and let the script/import/export-function shift the value for G() up and down by 1?

Right – but why not number the games from 0 to n-1 and let the import/export shift the entries in the gameidlist by 1? So both solutions look equivalently good. Is there any further argument in one or the other direction?

I think everything else is 0-based, so I guess I’d rather shift the entries in the gameidlist.

**Comment by nomeata** [comment]
>  So it would be better to number the main-subgames from 1 to m and the bonus-subgames from m+1 to n. Sorry for the change of mind.

This this case, maybe you want to ditch `f` in https://github.com/entropia/tip-toi-reveng/wiki/GME-Games and simply write “e: b * 32bit pointers to subgames, for type 6 there are b+c pointers”?

**Comment by ToniMahagoni** [comment]
>I think everything else is 0-based, so I guess I’d rather shift the entries in the gameidlist

In the end it's your decision and I'm totally fine with it. As long as the frontend isn't as inconsistent as the GME-file:
Same startpoint for G(), gidlists and subgamelists.

**Comment by ToniMahagoni** [comment]
> maybe you want to ditch f

Not sure about that.
Definitely a good way to handle this in the coding.
But maybe it's a little bit easier to understand if separate it in the documentation.

**Comment by nomeata** [comment]
>  Definitely a good way to handle this in the coding.

Done.

**Comment by ToniMahagoni** [comment]
Seems to work fine in the issue120-branch.
