### ISSUE TITLE
Orphaned play scripts

### ISSUE THREAD

**Issue by ToniMahagoni** [entropia/tip-toi-reveng#122]
In "WWW Strassenverkehr" (and at least one more file I don't remember) there seem to be some orphaned play scripts.
Between the play scripts for 1033 and 1035 is some code left which is identical to the code of 1034 (found between 1321 and 1322).
This leads to unknown code in a section that's fully discovered.
Should this be handled in any way?

**Comment by nomeata** [comment]
>  Should this be handled in any way?

Well, if we find how its referenced, then yes. Otherwise, we have to assume that their GME creation tool is broken.

Do you find the position of these scripts mentioned somewhere, as a 32 bit offset?

**Comment by uli42** [comment]
tttool could try to identify such unknown areas if they appear between the other play scripts. And mark them as "probably unused. At least in `tttool explain` and `tttool holes`

**Comment by nomeata** [comment]
Hmm, that’d be some non-trivial code for little gain, I am hesitant to implement that right now.

**Comment by uli42** [comment]
On Thu, Nov 29, 2018 at 9:05 PM Joachim Breitner
<notifications@github.com> wrote:
>
> Hmm, that’d be some non-trivial code for little gain, I am hesitant to implement that right now.

Well, you could just assume that all the playscripts are stored in
order. If you find a disabled entry in the script table you can check
if the data following the previous entry's playscript. is in a hole
and has the right size. It doesn't need to be perfect, it should just
help elimination holes that are not really holes but artefacts of the
Ravensburger build utility.

Uli

**Comment by nomeata** [comment]
I don’t think I’ll get to do that (but thanks for the suggestion). Odd that the Ravensburger tool would create such file… Seems to apply to other files as well.
