### ISSUE TITLE
Install fails (while "cabal install") with "Not in scope: createPDFRawImage"

### ISSUE THREAD

**Issue by schnitzler** [entropia/tip-toi-reveng#123]
While precisely following the instructions under https://github.com/entropia/tip-toi-reveng#installation, the installation fails while running "cabal install --bindir=.".

The (shortened) output is:

------------------------------------------------------------------------
(...)
Loading package safe-0.3.9 ... linking ... done.
Loading package errors-2.0.1 ... linking ... done.
Loading package random-1.1 ... linking ... done.
Loading package HPDF-1.4.10 ... linking ... done.
[10 of 22] Compiling OidTable         ( src/OidTable.hs, dist/build/tttool/tttool-tmp/OidTable.o )

src/OidTable.hs:106:30:
    Not in scope: `createPDFRawImage'
    Perhaps you meant createPDFRawImage' (line 106)
Failed to install tttool-1.6
cabal: Error: some packages failed to install:
tttool-1.6 failed during the building phase. The exception was:
ExitFailure 1
------------------------------------------------------------------------

I was using OSX 10.9.5 - and although the error message didn't sound like it's a compatibility issue,  re-retested using Ubuntu 14.04 64bit to be sure. Same result, obviously.

If there's anything else I can supply to help with this issue, please let me know.

Thanks!

**Comment by nomeata** [comment]
Thanks. A dependency changed its API with an unexpected version bump; I’ll fix this very shortly.

**Comment by schnitzler** [comment]
whow, that was quick ;-)

thanks a lot!
