### ISSUE TITLE
Scriptline limit

### ISSUE THREAD

**Issue by codingPF** [entropia/tip-toi-reveng#125]
Hi,
I found some strange behavior on long scriptlines. When a line exceeds 8 commands, the playlist is ignored. Dummy sample below:
```javascript
scripts:
  1001:
  - P(A00_ok) P(A00_ok) P(A00_ok) P(A00_ok) P(A00_ok) P(A00_ok) P(A00_ok)
  1002:
  - P(A00_ok) P(A00_ok) P(A00_ok) P(A00_ok) P(A00_ok) P(A00_ok) P(A00_ok) P(A00_ok)
  1003:
  - P(A00_ok) P(A00_ok) P(A00_ok) P(A00_ok) P(A00_ok) P(A00_ok) P(A00_ok) P(A00_ok) P(A00_ok)
  1004:
  - $a:=1 $b:=1 $c:=1 $d:=1 $e:=1 $f:=1 $g:=1 $h:=1 P(A00_ok)
speak:
  A00_ok: "OK"
```
Output:
1001: working
1002: working
1003: silence (no sound played at all)
1004: same as 1003

Yes, this example does not make sense but if this is a known limitation maybe tttool should throw an exception on parsing yaml file?

**Comment by nomeata** [comment]
> Yes, this example does not make sense but if this is a known limitation maybe tttool should throw an exception on parsing yaml file?

Quite right; this is planned. Thanks for the reminder.

I’d like to know better however what the limit is: I have heard that with your 1004-line, the register commands _are_ executed.

**Comment by codingPF** [comment]
Sorry, I did not include this finding but yes the register commands are executed...
I would assume it is only the playlist which is broken...
