### ISSUE TITLE
Tiptoi mit Player does not recognize tttool gme files

### ISSUE THREAD

**Issue by thawn** [entropia/tip-toi-reveng#126]
I just bought the new tiptoi with Player.
I created the Debug.gme and printed the corresponding start.png OID code (created with `tttool oid-codes Debug.yaml`). Then I uploaded the GME on the tiptoi. The code is recognized by the pen but the pen asks me to download the proper game file. I also printed the OID code 1 which corresponds to the preinstalled "WWW Bauernhof.gme" which I found already on the tiptoi and this works fine.

I suspect there is some new error checking involved in the latest firmware. This is supported by the fact that the tiptoi manager complained that the Debug.gme file was corrupt and automatically deleted it (even though it played just fine using tttool play Debug.gme). Could this have something to do with the magic xor numbers? I tried to play the preinstalled "WWW bauernhof.gme" using tttool and that worked just fine.

Here is the info that tttool prints for the working preinstalled "WWW bauernhof.gme":

    ./tttool info WWW\ Bauernhof.gme 
    Product ID: 1
    Raw XOR value: 0x00000039
    Magic XOR value: 0xAD
    Comment: CHOMPTECH DATA FORMAT CopyRight 2009 Ver2.4.0316
    Date: 20111024
    Number of registers: 101
    Initial registers: [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
    Initial sounds: [[618,619]]
    Scripts for OIDs from 1401 to 1728; 78/328 are disabled.
    Audio table entries: 620
    Binary tables entries: 0/0/0/0
    Checksum found 0x92C8962E, calculated 0x92C8962E

I am happy to provide any additional information about the my tiptoi with player or the preinstalled gme file that works. Just let me know how to obtain that information.

**Comment by uli42** [comment]
On Wed, Jan 6, 2016 at 8:53 AM, thawn <notifications@github.com> wrote:
>
> I just bought the new tiptoi with Player
> I created the Debuggme and printed the corresponding startpng OID code (created with tttool oid-codes Debugyaml) Then I uploaded the GME on the tiptoi The code is recognized by the pen but the pen asks me to download the proper game file I also printed the OID code 1 which corresponds to the preinstalled "WWW Bauernhofgme" which I found already on the tiptoi and this works fine
>
> I suspect there is some new error checking involved in the latest firmware This is supported by the fact that the tiptoi manager complained that the Debuggme file was corrupt and automatically deleted it (even though it played just fine using tttool play Debuggme) Could this have something to do with the magic xor numbers? I tried to play the preinstalled "WWW bauernhofgme" using tttool and that worked just fine

Maybe the new firmware checks the date string and then decides what
fields in the header are allowed. Does it help to adapt the date
string? Also, is the checksum still correct? Maybe the new firmware
checks the checksum (the old one did not) and somewhere along the road
our calculation broke..

Uli

**Comment by thawn** [comment]
Hi Uli,

Thanks for the quick reply.
The checksum for the builtin WWW Bauernhof.gme file is recognized and calculated o.k.: `Checksum found 0x92C8962E, calculated 0x92C8962E`. Also for the generated Debug.gme file, the calculated and found checksums match (no surprise there).

Is there a way to specify the date in the yaml file or do I need to use a hex editor?

I'll test whether changing the date helps as soon as I get home and post the results here.

Cheers

**Comment by uli42** [comment]
I would try to change the date in the tttool source so that you get the correct checksum, too.

BTW: Does the new pen complain in a different way if you change the checksum to something invalid?

Uli

Vom Smartphone gesendet.

----- Ursprüngliche Nachricht -----
Von: "thawn" <notifications@github.com>
Gesendet: ‎06.‎01.‎2016 11:21
An: "entropia/tip-toi-reveng" <tip-toi-reveng@noreply.github.com>
Cc: "uli42" <uli42@gmx.de>
Betreff: Re: [tip-toi-reveng] Tiptoi mit Player does not recognize tttool gmefiles (#126)

Hi Uli,
Thanks for the quick reply.
The checksum for the builtin WWW Bauernhof.gme file is recognized and calculated o.k.: Checksum found 0x92C8962E, calculated 0x92C8962E. Also for the generated Debug.gme file, the calculated and found checksums match (no surprise there).
Is there a way to specify the date in the yaml file or do I need to use a hex editor?
I'll test whether changing the date helps as soon as I get home and post the results here.
Cheers

**Comment by thawn** [comment]
o.k. I hard coded the date to `20111026` in the source (TipToiYaml.hs line 269) and assembled a new Debug.gme. `tttool info Debug.gme` now shows `20111026` as date. Let's see whether that works.

**Comment by thawn** [comment]
Habe auf der mailing liste die Lösung gefunden. Ich hatte den Stift einmal zu früh abgezogen und dadurch war offensichtlich das Dateisystem beschädigt. "Repair Disk" mit diskutil (Mac OS X version von chkdsk) hat das Problem behoben.

witzigerweise funktioniert sowohl die Datei in der ich von Hand das Datum geändert habe (die folglich eine falsche Checksumme hatte) als auch die mit dem auf fixe Daten gepatchten tttool erstellte (mit altem Datum und korrekter Checksumme)

**Comment by thawn** [comment]
O.k. apparently it was not that easy after all. The issue was apparently not (only) with filesystem errors. Trying to add another (very similarly named) gme file, I ran across the same issue again. This time repairing the filesystem did not help. Then I tried various other things and after I uploaded another file from Ravensburger, the message "Please have a moment of patience" appeared again after unplugging the pen afterwards everything worked fine. Then, after renaming the files, the issue appeared again. This time emptying the Mac OS X trash and removing hidden files and directories created by Mac OS X (rm -r .Trashes; rm -r ._*; rm -r .Spotlight-V100; etc...) the message appeared again and everything worked fine again.
Apparently the new sticks have some sort of media library that needs to be updated after files are loaded onto the pen. It seems like the recognition algorithm is easily confused. Maybe because it uses the old DOS filenames which still lurk somewhere in the fat32 filesystem. So this is likely an upstream bug in the ravensburger firmware, which will hopefully be fixed soon.

So if you run across the same problem try the following steps:
* repair the filesystem
* delete files and directories starting with a dot (EXCEPT for .tiptoi.log which is created by the tiptoi during firmware upgrades)
* try downloading a gme file from ravensburger and copying that onto the tiptoi pen

**Comment by B-G-T** [comment]
Hallo,

das erinnert mich an den Post von Johannes:

> Hallo,
>
> ich bin mittlerweile passionierter tttool Benutzer. Meine Frau hat mittlerweile 6 normale Kinder-Bilderbücher 'besprochen' und ich mache gerne kleine laminierte DIN A4 Sachen (Adventskalender, Weihnachtsgeschichte etc).
>
> Da unser Stift schon mal ballistische Flugbahnen nimmt, haben wir uns (auch zum entwickeln) extra einen weiteren Tip-Toi Stift gekauft. Die neue Version des Tip-Toi mit Player ist komischerweise neu billiger als gebrauchte auf eBay (30 EUR). Jetzt haben wir einen 'alten' (ohne Player) und einen 'neuen' (mit den Player-Knöpfen).
>
> Die unterscheiden sich im Verhalten: Wenn man eine *.gme Datei auf den neuen Kopiert und danach den Stecker abzieht sagt er 'Bitte gedulde dich einen Moment ... (3 Sek Pause) ... Fertig! Jetzt kannst du den Stift anschalten.' (oder so). Der alte sagt da garnix.
>
> Problem: Plötzlich sagte der Stift zwar 'Bitte gedulde dich einen Moment ...' und dann sagt der garnix mehr und ist auch augenscheinlich gar nicht mehr an. Offensichtlich abgestürzt. Das selbe passierte jetzt jedes mal wenn man ihn anschaltet. Gedulden, und nix passiert. Stift war nicht mehr benutzbar.
>
> Lösung: Den Ordner '.Spotlight-V100' auf dem Stift vor dem Auswerfen löschen. Den legt das Mac OS X immer ungefragt an, sobald man den Stift einsteckt. Das muss ich jetzt jedes mal machen. Dann funktioniert wieder alles wie gehabt. (Unter Windows gibt es dieses Problem nicht.) Offensichtlich verhaspelt sich der Tip-Toi in den Dateien der Spotlight Suche.
>
> (Falls jemand weiss, wie man das automatische Anlegen dieser Order deaktivieren kann, würde ich mich über eine Mail freuen!)
>
> Liebe Grüße und frohe Festtage!
>
> Johannes

Viele Grüße
Björn


Am 06.01.2016 um 22:16 schrieb thawn:

**Comment by thawn** [comment]
Ah, ich habe [gefunden wie man das Anlegen dieses Ordners verhindert](https://discussions.apple.com/thread/5486948?tstart=0): Man kann im tiptoi hauptverzeichnis (`/Volumes/tiptoi`) eine Datei namens `.metadata_never_index` anlegen (im Terminal: `touch /Volumes/tiptoi/.metadata_never_index`). Danach muss man den spotlight ordner noch einmal löschen und dann hat man Ruhe...
