### ISSUE TITLE
Install fails (cabal: Error: some packages failed to install:) 

### ISSUE THREAD

**Issue by portulaca2** [entropia/tip-toi-reveng#128]
HPDF-1.4.10 depends on primitive-0.6.1.0 which failed to install.
JuicyPixels-3.2.7 depends on primitive-0.6.1.0 which failed to install.
aeson-0.11.0.0 depends on primitive-0.6.1.0 which failed to install.
attoparsec-0.13.0.1 depends on primitive-0.6.1.0 which failed to install.
conduit-1.2.6.2 depends on mtl-2.2.1 which failed to install.
exceptions-0.8.2.1 depends on mtl-2.2.1 which failed to install.
mmorph-1.0.6 depends on mtl-2.2.1 which failed to install.
mtl-2.2.1 failed during the configure step. The exception was: ExitFailure 1
parsec-3.1.9 depends on mtl-2.2.1 which failed to install.
primitive-0.6.1.0 failed during the configure step. The exception was: ExitFailure 1
resourcet-1.1.7.2 depends on mtl-2.2.1 which failed to install.
scientific-0.3.4.4 depends on primitive-0.6.1.0 which failed to install.
spool-0.1 depends on primitive-0.6.1.0 which failed to install.
vector-0.11.0.0 depends on primitive-0.6.1.0 which failed to install.
yaml-0.8.15.3 depends on primitive-0.6.1.0 which failed to install.

I have no idea, what to do (no programmer). My system is ubuntu 12.04 LTS.
thanks in advance

Christina

**Comment by nomeata** [comment]
The real error messages must be further up. Can you find them, or paste the whole log?

Also, what’s your version of GHC?

**Comment by portulaca2** [comment]
My version of GHC is ghc 7.4.1-1ubuntu2.

And the log:
chris@chris:~$ cd tttool
chris@chris:~/tttool$ cabal update
Downloading the latest package list from hackage.haskell.org
chris@chris:~/tttool$ cabal install --only-dependencies
Resolving dependencies...
Configuring mtl-2.2.1...
cabal: At least the following dependencies are missing:
transformers ==0.4.* && ==0.5.1.0
Configuring primitive-0.6.1.0...
cabal: At least the following dependencies are missing:
transformers >=0.2 && <0.5 && ==0.5.1.0
cabal: Error: some packages failed to install:
HPDF-1.4.10 depends on primitive-0.6.1.0 which failed to install.
JuicyPixels-3.2.7 depends on primitive-0.6.1.0 which failed to install.
aeson-0.11.0.0 depends on primitive-0.6.1.0 which failed to install.
attoparsec-0.13.0.1 depends on primitive-0.6.1.0 which failed to install.
conduit-1.2.6.2 depends on mtl-2.2.1 which failed to install.
exceptions-0.8.2.1 depends on mtl-2.2.1 which failed to install.
mmorph-1.0.6 depends on mtl-2.2.1 which failed to install.
mtl-2.2.1 failed during the configure step. The exception was:
ExitFailure 1
parsec-3.1.9 depends on mtl-2.2.1 which failed to install.
primitive-0.6.1.0 failed during the configure step. The exception was:
ExitFailure 1
resourcet-1.1.7.2 depends on mtl-2.2.1 which failed to install.
scientific-0.3.4.4 depends on primitive-0.6.1.0 which failed to install.
spool-0.1 depends on primitive-0.6.1.0 which failed to install.
vector-0.11.0.0 depends on primitive-0.6.1.0 which failed to install.
yaml-0.8.16 depends on primitive-0.6.1.0 which failed to install.
chris@chris:~/tttool$

**Comment by nomeata** [comment]
Oh, GHC 7.4 is actually quite old, and with recent changes I had to drop 7.4 compatibility. Any chance that you can upgrade your version of Ubuntu?

If not, you can get newer version of GHC for Ubuntu precise here: https://launchpad.net/~hvr/+archive/ubuntu/ghc

**Comment by portulaca2** [comment]
Nach einigem Hin und Her habe ich nun die vier Pakete ghc-7.8.4 runtergeladen, aber scheinbar nicht richtig installiert.

Brauche ich eine höhere Version oder ein Paket zusätzlich oder nur den richtigen Befehl? 

chris@chris:~/tttool$ cabal update
Downloading the latest package list from hackage.haskell.org
chris@chris:~/tttool$ cabal install --only-dependencies
cabal: The program ghc version >=6.4 is required but it could not be found.

**Comment by nomeata** [comment]
Warum vier Pakete?

Versuchs mal mit vorher diesen Befehl eingeben:
```
export PATH=/opt/ghc/7.8.4/bin:$PATH
```

**Comment by portulaca2** [comment]
Alles, was zum Download bereit stand
    ghc-7.8.4-dyn_7.8.4-10~precise_amd64.deb (2.2 KiB)
    ghc-7.8.4-htmldocs_7.8.4-10~precise_amd64.deb (7.3 MiB)
    ghc-7.8.4-prof_7.8.4-10~precise_amd64.deb (27.9 MiB)
    ghc-7.8.4_7.8.4-10~precise_amd64.deb (34.7 MiB)

Es kam wieder eine lange Liste mit Warnungen und Fehlern

chris@chris:~$ cd tttool
chris@chris:~/tttool$ cabal update
Downloading the latest package list from hackage.haskell.org
chris@chris:~/tttool$ export PATH=/opt/ghc/7.8.4/bin:$PATH
chris@chris:~/tttool$ cabal install --only-dependencies
Resolving dependencies...
[1 of 1] Compiling Main             ( /tmp/haskeline-0.7.2.2-11971/haskeline-0.7.2.2/Setup.hs, /tmp/haskeline-0.7.2.2-11971/haskeline-0.7.2.2/dist/setup/Main.o )
Linking /tmp/haskeline-0.7.2.2-11971/haskeline-0.7.2.2/dist/setup/setup ...
Configuring haskeline-0.7.2.2...
Building haskeline-0.7.2.2...
Preprocessing library haskeline-0.7.2.2...
[ 1 of 27] Compiling System.Console.Haskeline.Recover ( System/Console/Haskeline/Recover.hs, dist/build/System/Console/Haskeline/Recover.o )
[ 2 of 27] Compiling System.Console.Haskeline.Directory ( dist/build/System/Console/Haskeline/Directory.hs, dist/build/System/Console/Haskeline/Directory.o )
[ 3 of 27] Compiling System.Console.Haskeline.Key ( System/Console/Haskeline/Key.hs, dist/build/System/Console/Haskeline/Key.o )
[ 4 of 27] Compiling System.Console.Haskeline.History ( System/Console/Haskeline/History.hs, dist/build/System/Console/Haskeline/History.o )
[ 5 of 27] Compiling System.Console.Haskeline.LineState ( System/Console/Haskeline/LineState.hs, dist/build/System/Console/Haskeline/LineState.o )
[ 6 of 27] Compiling System.Console.Haskeline.Command ( System/Console/Haskeline/Command.hs, dist/build/System/Console/Haskeline/Command.o )
[ 7 of 27] Compiling System.Console.Haskeline.Backend.WCWidth ( System/Console/Haskeline/Backend/WCWidth.hs, dist/build/System/Console/Haskeline/Backend/WCWidth.o )
[ 8 of 27] Compiling System.Console.Haskeline.MonadException ( System/Console/Haskeline/MonadException.hs, dist/build/System/Console/Haskeline/MonadException.o )

System/Console/Haskeline/MonadException.hs:38:1: Warning:
    Module ‘Control.Monad.Trans.Error’ is deprecated:
      Use Control.Monad.Trans.Except instead

System/Console/Haskeline/MonadException.hs:161:29: Warning:
    In the use of type constructor or class ‘Error’
    (imported from Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"

System/Console/Haskeline/MonadException.hs:161:57: Warning:
    In the use of type constructor or class ‘ErrorT’
    (imported from Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"

System/Console/Haskeline/MonadException.hs:162:19: Warning:
    In the use of data constructor ‘ErrorT’
    (imported from Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"

System/Console/Haskeline/MonadException.hs:163:40: Warning:
    In the use of data constructor ‘ErrorT’
    (imported from Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"

System/Console/Haskeline/MonadException.hs:163:55: Warning:
    In the use of ‘runErrorT’
    (imported from Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"

System/Console/Haskeline/MonadException.hs:164:29: Warning:
    In the use of ‘runErrorT’
    (imported from Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"
[ 9 of 27] Compiling System.Console.Haskeline.Prefs ( System/Console/Haskeline/Prefs.hs, dist/build/System/Console/Haskeline/Prefs.o )
[10 of 27] Compiling System.Console.Haskeline.Monads ( System/Console/Haskeline/Monads.hs, dist/build/System/Console/Haskeline/Monads.o )
[11 of 27] Compiling System.Console.Haskeline.Command.Undo ( System/Console/Haskeline/Command/Undo.hs, dist/build/System/Console/Haskeline/Command/Undo.o )
[12 of 27] Compiling System.Console.Haskeline.Command.History ( System/Console/Haskeline/Command/History.hs, dist/build/System/Console/Haskeline/Command/History.o )
[13 of 27] Compiling System.Console.Haskeline.Command.KillRing ( System/Console/Haskeline/Command/KillRing.hs, dist/build/System/Console/Haskeline/Command/KillRing.o )
[14 of 27] Compiling System.Console.Haskeline.Completion ( System/Console/Haskeline/Completion.hs, dist/build/System/Console/Haskeline/Completion.o )
[15 of 27] Compiling System.Console.Haskeline.Term ( System/Console/Haskeline/Term.hs, dist/build/System/Console/Haskeline/Term.o )

System/Console/Haskeline/Term.hs:107:16: Warning:
    In the use of ‘isEmptyChan’
    (imported from Control.Concurrent, but defined in Control.Concurrent.Chan):
    Deprecated: "if you need this operation, use Control.Concurrent.STM.TChan instead.  See <http://ghc.haskell.org/trac/ghc/ticket/4154> for details"
[16 of 27] Compiling System.Console.Haskeline.RunCommand ( System/Console/Haskeline/RunCommand.hs, dist/build/System/Console/Haskeline/RunCommand.o )
[17 of 27] Compiling System.Console.Haskeline.Backend.Posix.Encoder ( System/Console/Haskeline/Backend/Posix/Encoder.hs, dist/build/System/Console/Haskeline/Backend/Posix/Encoder.o )
[18 of 27] Compiling System.Console.Haskeline.Backend.Posix ( dist/build/System/Console/Haskeline/Backend/Posix.hs, dist/build/System/Console/Haskeline/Backend/Posix.o )
[19 of 27] Compiling System.Console.Haskeline.Backend.Terminfo ( System/Console/Haskeline/Backend/Terminfo.hs, dist/build/System/Console/Haskeline/Backend/Terminfo.o )
[20 of 27] Compiling System.Console.Haskeline.Backend.DumbTerm ( System/Console/Haskeline/Backend/DumbTerm.hs, dist/build/System/Console/Haskeline/Backend/DumbTerm.o )
[21 of 27] Compiling System.Console.Haskeline.Backend ( System/Console/Haskeline/Backend.hs, dist/build/System/Console/Haskeline/Backend.o )
[22 of 27] Compiling System.Console.Haskeline.InputT ( System/Console/Haskeline/InputT.hs, dist/build/System/Console/Haskeline/InputT.o )

System/Console/Haskeline/InputT.hs:17:1: Warning:
    The import of ‘Control.Monad’ is redundant
      except perhaps to import instances from ‘Control.Monad’
    To import instances alone, use: import Control.Monad()
[23 of 27] Compiling System.Console.Haskeline.Command.Completion ( System/Console/Haskeline/Command/Completion.hs, dist/build/System/Console/Haskeline/Command/Completion.o )
[24 of 27] Compiling System.Console.Haskeline.Vi ( System/Console/Haskeline/Vi.hs, dist/build/System/Console/Haskeline/Vi.o )
[25 of 27] Compiling System.Console.Haskeline.Emacs ( System/Console/Haskeline/Emacs.hs, dist/build/System/Console/Haskeline/Emacs.o )
[26 of 27] Compiling System.Console.Haskeline ( System/Console/Haskeline.hs, dist/build/System/Console/Haskeline.o )
[27 of 27] Compiling System.Console.Haskeline.IO ( System/Console/Haskeline/IO.hs, dist/build/System/Console/Haskeline/IO.o )
/usr/bin/ld: cannot find -lHStransformers-0.5.2.0-ghc7.8.4
/usr/bin/ld: cannot find -lHSdirectory-1.2.5.1-ghc7.8.4
/usr/bin/ld: cannot find -lHSunix-2.7.1.0-ghc7.8.4
/usr/bin/ld: cannot find -lHStime-1.5.0.1-ghc7.8.4
collect2: ld gab 1 als Ende-Status zurück
Configuring mtl-2.2.1...
cabal: At least the following dependencies are missing:
transformers ==0.4.* && ==0.5.2.0
Configuring optparse-applicative-0.12.1.0...
Building optparse-applicative-0.12.1.0...
Preprocessing library optparse-applicative-0.12.1.0...
[ 1 of 15] Compiling Options.Applicative.Help.Pretty ( Options/Applicative/Help/Pretty.hs, dist/build/Options/Applicative/Help/Pretty.o )
[ 2 of 15] Compiling Options.Applicative.Help.Chunk ( Options/Applicative/Help/Chunk.hs, dist/build/Options/Applicative/Help/Chunk.o )
[ 3 of 15] Compiling Options.Applicative.Help.Types ( Options/Applicative/Help/Types.hs, dist/build/Options/Applicative/Help/Types.o )
[ 4 of 15] Compiling Options.Applicative.Types ( Options/Applicative/Types.hs, dist/build/Options/Applicative/Types.o )
[ 5 of 15] Compiling Options.Applicative.Internal ( Options/Applicative/Internal.hs, dist/build/Options/Applicative/Internal.o )
[ 6 of 15] Compiling Options.Applicative.Builder.Completer ( Options/Applicative/Builder/Completer.hs, dist/build/Options/Applicative/Builder/Completer.o )
[ 7 of 15] Compiling Options.Applicative.Common ( Options/Applicative/Common.hs, dist/build/Options/Applicative/Common.o )
[ 8 of 15] Compiling Options.Applicative.Builder.Internal ( Options/Applicative/Builder/Internal.hs, dist/build/Options/Applicative/Builder/Internal.o )
[ 9 of 15] Compiling Options.Applicative.Builder ( Options/Applicative/Builder.hs, dist/build/Options/Applicative/Builder.o )
[10 of 15] Compiling Options.Applicative.BashCompletion ( Options/Applicative/BashCompletion.hs, dist/build/Options/Applicative/BashCompletion.o )
[11 of 15] Compiling Options.Applicative.Help.Core ( Options/Applicative/Help/Core.hs, dist/build/Options/Applicative/Help/Core.o )
Loading package ghc-prim ... linking ... done.
Loading package integer-gmp ... linking ... done.
Loading package base ... linking ... done.
Loading package transformers-0.5.2.0 ... <command line>: can't load .so/.DLL for: libHStransformers-0.5.2.0.so (libHStransformers-0.5.2.0.so: cannot open shared object file: No such file or directory)
Configuring primitive-0.6.1.0...
cabal: At least the following dependencies are missing:
transformers >=0.2 && <0.5 && ==0.5.2.0
Configuring zlib-0.6.1.1...
Warning: Unknown extensions: DeriveGeneric
cabal: Missing dependency on a foreign library:
* Missing (or bad) header file: zlib.h
* Missing C library: z
This problem can usually be solved by installing the system package that
provides this library (you may need the "-dev" version). If the library is
already installed but in a non-standard location then you can use the flags
--extra-include-dirs= and --extra-lib-dirs= to specify where it is.
If the header file does exist, it may contain errors that are caught by the C
compiler at the preprocessing stage. In this case you can re-run configure
with the verbosity flag -v3 to see the error messages.
cabal: Error: some packages failed to install:
HPDF-1.4.10 depends on zlib-0.6.1.1 which failed to install.
JuicyPixels-3.2.7 depends on zlib-0.6.1.1 which failed to install.
aeson-0.11.0.0 depends on primitive-0.6.1.0 which failed to install.
attoparsec-0.13.0.1 depends on primitive-0.6.1.0 which failed to install.
conduit-1.2.6.2 depends on mtl-2.2.1 which failed to install.
exceptions-0.8.2.1 depends on mtl-2.2.1 which failed to install.
haskeline-0.7.2.2 failed during the building phase. The exception was:
ExitFailure 1
mmorph-1.0.6 depends on mtl-2.2.1 which failed to install.
mtl-2.2.1 failed during the configure step. The exception was:
ExitFailure 1
optparse-applicative-0.12.1.0 failed during the building phase. The exception
was:
ExitFailure 1
parsec-3.1.9 depends on mtl-2.2.1 which failed to install.
primitive-0.6.1.0 failed during the configure step. The exception was:
ExitFailure 1
resourcet-1.1.7.2 depends on mtl-2.2.1 which failed to install.
scientific-0.3.4.4 depends on primitive-0.6.1.0 which failed to install.
spool-0.1 depends on primitive-0.6.1.0 which failed to install.
vector-0.11.0.0 depends on primitive-0.6.1.0 which failed to install.
yaml-0.8.16 depends on primitive-0.6.1.0 which failed to install.
zlib-0.6.1.1 failed during the configure step. The exception was:
ExitFailure 1
chris@chris:~/tttool$

**Comment by nomeata** [comment]
Ah, that helps. Install `zlib1g-dev` and try again!

**Comment by nomeata** [comment]
Hmm, there are other weirdnesses. Try to remove `~/.ghc` before retrying.

**Comment by portulaca2** [comment]
Also alles aus .ghc rausgeworfen
Dann lies sich erstmal gar nichts installieren.
Als Nächstes hat sich ein Paket bei der Installation verklemmt. Scheint öfter vorzukommen - dafür gab es eine schöne Anleitung.

Nach Installation von zlib1g-dev und ghc habe ich den Befehl cabal install --only-dependencies eingegeben. Dann kam so eine lange Liste, daß der Anfang aus dem Terminal verschwunden ist. Der zweite Vesuch ist unten:

chris@chris:~/tttool$ cabal install --only-dependencies
Resolving dependencies...
[1 of 1] Compiling Main             ( /tmp/haskeline-0.7.2.2-14799/haskeline-0.7.2.2/Setup.hs, /tmp/haskeline-0.7.2.2-14799/haskeline-0.7.2.2/dist/setup/Main.o )
Linking /tmp/haskeline-0.7.2.2-14799/haskeline-0.7.2.2/dist/setup/setup ...
Configuring haskeline-0.7.2.2...
Building haskeline-0.7.2.2...
Preprocessing library haskeline-0.7.2.2...
[ 1 of 27] Compiling System.Console.Haskeline.Recover ( System/Console/Haskeline/Recover.hs, dist/build/System/Console/Haskeline/Recover.o )
[ 2 of 27] Compiling System.Console.Haskeline.Directory ( dist/build/System/Console/Haskeline/Directory.hs, dist/build/System/Console/Haskeline/Directory.o )
[ 3 of 27] Compiling System.Console.Haskeline.Key ( System/Console/Haskeline/Key.hs, dist/build/System/Console/Haskeline/Key.o )
[ 4 of 27] Compiling System.Console.Haskeline.History ( System/Console/Haskeline/History.hs, dist/build/System/Console/Haskeline/History.o )
[ 5 of 27] Compiling System.Console.Haskeline.LineState ( System/Console/Haskeline/LineState.hs, dist/build/System/Console/Haskeline/LineState.o )
[ 6 of 27] Compiling System.Console.Haskeline.Command ( System/Console/Haskeline/Command.hs, dist/build/System/Console/Haskeline/Command.o )
[ 7 of 27] Compiling System.Console.Haskeline.Backend.WCWidth ( System/Console/Haskeline/Backend/WCWidth.hs, dist/build/System/Console/Haskeline/Backend/WCWidth.o )
[ 8 of 27] Compiling System.Console.Haskeline.MonadException ( System/Console/Haskeline/MonadException.hs, dist/build/System/Console/Haskeline/MonadException.o )

System/Console/Haskeline/MonadException.hs:38:1: Warning:
    Module ‘Control.Monad.Trans.Error’ is deprecated:
      Use Control.Monad.Trans.Except instead

System/Console/Haskeline/MonadException.hs:161:29: Warning:
    In the use of type constructor or class ‘Error’
    (imported from Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"

System/Console/Haskeline/MonadException.hs:161:57: Warning:
    In the use of type constructor or class ‘ErrorT’
    (imported from Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"

System/Console/Haskeline/MonadException.hs:162:19: Warning:
    In the use of data constructor ‘ErrorT’
    (imported from Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"

System/Console/Haskeline/MonadException.hs:163:40: Warning:
    In the use of data constructor ‘ErrorT’
    (imported from Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"

System/Console/Haskeline/MonadException.hs:163:55: Warning:
    In the use of ‘runErrorT’
    (imported from Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"

System/Console/Haskeline/MonadException.hs:164:29: Warning:
    In the use of ‘runErrorT’
    (imported from Control.Monad.Trans.Error):
    Deprecated: "Use Control.Monad.Trans.Except instead"
[ 9 of 27] Compiling System.Console.Haskeline.Prefs ( System/Console/Haskeline/Prefs.hs, dist/build/System/Console/Haskeline/Prefs.o )
[10 of 27] Compiling System.Console.Haskeline.Monads ( System/Console/Haskeline/Monads.hs, dist/build/System/Console/Haskeline/Monads.o )
[11 of 27] Compiling System.Console.Haskeline.Command.Undo ( System/Console/Haskeline/Command/Undo.hs, dist/build/System/Console/Haskeline/Command/Undo.o )
[12 of 27] Compiling System.Console.Haskeline.Command.History ( System/Console/Haskeline/Command/History.hs, dist/build/System/Console/Haskeline/Command/History.o )
[13 of 27] Compiling System.Console.Haskeline.Command.KillRing ( System/Console/Haskeline/Command/KillRing.hs, dist/build/System/Console/Haskeline/Command/KillRing.o )
[14 of 27] Compiling System.Console.Haskeline.Completion ( System/Console/Haskeline/Completion.hs, dist/build/System/Console/Haskeline/Completion.o )
[15 of 27] Compiling System.Console.Haskeline.Term ( System/Console/Haskeline/Term.hs, dist/build/System/Console/Haskeline/Term.o )

System/Console/Haskeline/Term.hs:107:16: Warning:
    In the use of ‘isEmptyChan’
    (imported from Control.Concurrent, but defined in Control.Concurrent.Chan):
    Deprecated: "if you need this operation, use Control.Concurrent.STM.TChan instead.  See <http://ghc.haskell.org/trac/ghc/ticket/4154> for details"
[16 of 27] Compiling System.Console.Haskeline.RunCommand ( System/Console/Haskeline/RunCommand.hs, dist/build/System/Console/Haskeline/RunCommand.o )
[17 of 27] Compiling System.Console.Haskeline.Backend.Posix.Encoder ( System/Console/Haskeline/Backend/Posix/Encoder.hs, dist/build/System/Console/Haskeline/Backend/Posix/Encoder.o )
[18 of 27] Compiling System.Console.Haskeline.Backend.Posix ( dist/build/System/Console/Haskeline/Backend/Posix.hs, dist/build/System/Console/Haskeline/Backend/Posix.o )
[19 of 27] Compiling System.Console.Haskeline.Backend.Terminfo ( System/Console/Haskeline/Backend/Terminfo.hs, dist/build/System/Console/Haskeline/Backend/Terminfo.o )
[20 of 27] Compiling System.Console.Haskeline.Backend.DumbTerm ( System/Console/Haskeline/Backend/DumbTerm.hs, dist/build/System/Console/Haskeline/Backend/DumbTerm.o )
[21 of 27] Compiling System.Console.Haskeline.Backend ( System/Console/Haskeline/Backend.hs, dist/build/System/Console/Haskeline/Backend.o )
[22 of 27] Compiling System.Console.Haskeline.InputT ( System/Console/Haskeline/InputT.hs, dist/build/System/Console/Haskeline/InputT.o )

System/Console/Haskeline/InputT.hs:17:1: Warning:
    The import of ‘Control.Monad’ is redundant
      except perhaps to import instances from ‘Control.Monad’
    To import instances alone, use: import Control.Monad()
[23 of 27] Compiling System.Console.Haskeline.Command.Completion ( System/Console/Haskeline/Command/Completion.hs, dist/build/System/Console/Haskeline/Command/Completion.o )
[24 of 27] Compiling System.Console.Haskeline.Vi ( System/Console/Haskeline/Vi.hs, dist/build/System/Console/Haskeline/Vi.o )
[25 of 27] Compiling System.Console.Haskeline.Emacs ( System/Console/Haskeline/Emacs.hs, dist/build/System/Console/Haskeline/Emacs.o )
[26 of 27] Compiling System.Console.Haskeline ( System/Console/Haskeline.hs, dist/build/System/Console/Haskeline.o )
[27 of 27] Compiling System.Console.Haskeline.IO ( System/Console/Haskeline/IO.hs, dist/build/System/Console/Haskeline/IO.o )
/usr/bin/ld: cannot find -lHStransformers-0.5.2.0-ghc7.8.4
/usr/bin/ld: cannot find -lHSdirectory-1.2.5.1-ghc7.8.4
/usr/bin/ld: cannot find -lHSunix-2.7.1.0-ghc7.8.4
/usr/bin/ld: cannot find -lHStime-1.5.0.1-ghc7.8.4
collect2: ld gab 1 als Ende-Status zurück
Configuring mtl-2.2.1...
cabal: At least the following dependencies are missing:
transformers ==0.4.* && ==0.5.2.0
Configuring optparse-applicative-0.12.1.0...
Building optparse-applicative-0.12.1.0...
Preprocessing library optparse-applicative-0.12.1.0...
[ 1 of 15] Compiling Options.Applicative.Help.Pretty ( Options/Applicative/Help/Pretty.hs, dist/build/Options/Applicative/Help/Pretty.o )
[ 2 of 15] Compiling Options.Applicative.Help.Chunk ( Options/Applicative/Help/Chunk.hs, dist/build/Options/Applicative/Help/Chunk.o )
[ 3 of 15] Compiling Options.Applicative.Help.Types ( Options/Applicative/Help/Types.hs, dist/build/Options/Applicative/Help/Types.o )
[ 4 of 15] Compiling Options.Applicative.Types ( Options/Applicative/Types.hs, dist/build/Options/Applicative/Types.o )
[ 5 of 15] Compiling Options.Applicative.Internal ( Options/Applicative/Internal.hs, dist/build/Options/Applicative/Internal.o )
[ 6 of 15] Compiling Options.Applicative.Builder.Completer ( Options/Applicative/Builder/Completer.hs, dist/build/Options/Applicative/Builder/Completer.o )
[ 7 of 15] Compiling Options.Applicative.Common ( Options/Applicative/Common.hs, dist/build/Options/Applicative/Common.o )
[ 8 of 15] Compiling Options.Applicative.Builder.Internal ( Options/Applicative/Builder/Internal.hs, dist/build/Options/Applicative/Builder/Internal.o )
[ 9 of 15] Compiling Options.Applicative.Builder ( Options/Applicative/Builder.hs, dist/build/Options/Applicative/Builder.o )
[10 of 15] Compiling Options.Applicative.BashCompletion ( Options/Applicative/BashCompletion.hs, dist/build/Options/Applicative/BashCompletion.o )
[11 of 15] Compiling Options.Applicative.Help.Core ( Options/Applicative/Help/Core.hs, dist/build/Options/Applicative/Help/Core.o )
Loading package ghc-prim ... linking ... done.
Loading package integer-gmp ... linking ... done.
Loading package base ... linking ... done.
Loading package transformers-0.5.2.0 ... <command line>: can't load .so/.DLL for: libHStransformers-0.5.2.0.so (libHStransformers-0.5.2.0.so: cannot open shared object file: No such file or directory)
Configuring primitive-0.6.1.0...
cabal: At least the following dependencies are missing:
transformers >=0.2 && <0.5 && ==0.5.2.0
cabal: Error: some packages failed to install:
HPDF-1.4.10 depends on primitive-0.6.1.0 which failed to install.
JuicyPixels-3.2.7 depends on primitive-0.6.1.0 which failed to install.
aeson-0.11.0.0 depends on primitive-0.6.1.0 which failed to install.
attoparsec-0.13.0.1 depends on primitive-0.6.1.0 which failed to install.
conduit-1.2.6.2 depends on mtl-2.2.1 which failed to install.
exceptions-0.8.2.1 depends on mtl-2.2.1 which failed to install.
haskeline-0.7.2.2 failed during the building phase. The exception was:
ExitFailure 1
mmorph-1.0.6 depends on mtl-2.2.1 which failed to install.
mtl-2.2.1 failed during the configure step. The exception was:
ExitFailure 1
optparse-applicative-0.12.1.0 failed during the building phase. The exception
was:
ExitFailure 1
parsec-3.1.9 depends on mtl-2.2.1 which failed to install.
primitive-0.6.1.0 failed during the configure step. The exception was:
ExitFailure 1
resourcet-1.1.7.2 depends on mtl-2.2.1 which failed to install.
scientific-0.3.4.4 depends on primitive-0.6.1.0 which failed to install.
spool-0.1 depends on primitive-0.6.1.0 which failed to install.
vector-0.11.0.0 depends on primitive-0.6.1.0 which failed to install.
yaml-0.8.16 depends on primitive-0.6.1.0 which failed to install.
chris@chris:~/tttool$ 

Es dreht sich scheinbar immer um die beiden Pakete mtl-2.2.1 und primitive-0.6.1.0 oder sehe ich das komplett falsch? Bei haskell.org ? sind die als veraltet markiert.
Soll ich eine höhere Version ghc nehmen? Oder wo kommen die Pakete her?

**Comment by portulaca2** [comment]
kurze Zwischenmeldung: bin jetzt auf Ubuntu 14.04 umgestiegen

**Comment by nomeata** [comment]
Ich kann das Problem nicht ganz nachvollziehen. Hast du jetzt GHC aus den offiziellen Ubuntu-Quellen, oder sonst wo her (z.B. PPA)?

**Comment by portulaca2** [comment]
tttool meldet sich ordnungsgemäß :-)

Nachdem am Freitag mit dem ghc 7.8.4 aus https://launchpad.net/~hvr/+archive/ubuntu/ghc und dem zlib1g-dev wieder so viele Fehler kamen, habe ich gestern Ubuntu 14.04 installiert.

Dort ist ghc 7.6.3-10 in den offiziellen Quellen. Mit dieser Version konnte ich heute ganz normal die Installation aus der Readme abarbeiten.

Also wenn ich gewußt hätte, wie leicht sich inzwischen ein USB-Stick zur Installation von Ubuntu herstellen läßt...
Danke für die Unterstützung

Christina

**Comment by nomeata** [comment]
gern geschehen
