### ISSUE TITLE
Bug in Parsing command FFE0 (RandomVariant)

### ISSUE THREAD

**Issue by NimVek** [entropia/tip-toi-reveng#130]
### Invocation

```
tttool (info|export|lint|...) <gmefile>
```

### Affected GME Files

ProductID | Filename | Date
------ | ------- | -----
015 | Het ridderkasteel.gme | 20120522
015 | Puzzle Chateau.gme | 20120417
015 | Puzzle - Il castello.gme | 20130711
015 | Puzzle Ritterburg.gme | 20110126
015 | Rycarskij zamok.gme | 20141024
016 | Puzzle Baustelle.gme | 20110510
016 | Puzzle Baustelle.gme | 20150305
017 | De manege.gme | 20120607
017 | Puzzle - Il maneggio dei pony.gme | 20131023
017 | Puzzle Poney.gme | 20120131
017 | Puzzle Ponyhof.gme | 20110527
017 | Puzzle Ponyhof.gme | 20110928
017 | Puzzle Ponyhof.gme | 20141016
028 | Puzzle Kinderarzt.gme | 20120102
028 | Puzzle Kinderarzt.gme | 20141017
039 | Das versunkene Logikland.gme | 20120920
039 | Das versunkene Logikland.gme | 20141017
044 | Wettstreit im Hexenwald.gme | 20121130
044 | Wettstreit im Hexenwald.gme | 20141017
046 | De turbulente tijdreis.gme | 20140613
046 | Die turbulente Zeitreise.gme | 20120906
046 | Die turbulente Zeitreise.gme | 20141017
046 | Voyage dans le temps.gme | 20131213
053 | Animali_Africa.gme | 20140312
053 | Animali_Farmset.gme | 20140320
053 | Animali_Fattoria.gme | 20140324
053 | Animali_Fattoria.gme | 20140328
053 | Figurines_Afrique.gme | 20140604
053 | Figurines_Afrique.gme | 20141029
053 | Figurines_Chevaux.gme | 20141218
053 | Figurines_Dinosaures.gme | 20150522
053 | Figurines_Ferme.gme | 20140603
053 | Figurines_Ferme.gme | 20141216
053 | Figurines_MaFermeAnimee.gme | 20140516
053 | Figurines_MaFermeAnimee.gme | 20141218
053 | Figurines_MonCentreEquestreAnime.gme | 20150422
053 | Speelfiguren_Afrika.gme | 20150227
053 | Speelfiguren_Afrika.gme | 20151113
053 | Speelfiguren_boerderij.gme | 20150227
053 | Speelfiguren_boerderij.gme | 20151113
053 | Speelfiguren_dierenset_boerderij.gme | 20150119
053 | Speelfiguren_dierenset_boerderij.gme | 20151113
053 | Speelfiguren_paarden.gme | 20151127
053 | Spielfiguren1.gme | 20130930
053 | Spielfiguren1.gme | 20140402
053 | Spielfiguren1.gme | 20150126
053 | Spielfiguren1.gme | 20150629
053 | Spielfiguren2.gme | 20130927
053 | Spielfiguren2.gme | 20140523
053 | Spielfiguren2.gme | 20141124
053 | Spielfiguren2.gme | 20150629
053 | Spielfiguren3.gme | 20130927
053 | Spielfiguren3.gme | 20140512
053 | Spielfiguren3.gme | 20141124
053 | Spielfiguren3.gme | 20151204
053 | Spielfiguren_AsienAustralien.gme | 20150629
053 | Spielfiguren_Dinosaurier.gme | 20140702
053 | Spielfiguren_Dinosaurier.gme | 20141124
053 | Spielfiguren_Dinosaurier.gme | 20150629
053 | Spielfiguren_Dinosaurier.gme | 20151204
053 | Spielfiguren_dinos.gme | 20150227
053 | Spielfiguren_dinos.gme | 20151113
053 | Spielfiguren_Pferde.gme | 20140514
053 | Spielfiguren_Pferde.gme | 20141217
053 | Spielfiguren_Pferde.gme | 20150422
053 | Spielfiguren_Reiterhof.gme | 20140408
053 | Spielfiguren_Reiterhof.gme | 20141124
053 | Spielfiguren_Zoo.gme | 20150629
082 | Dierenset Falabella.gme | 20151012
082 | Tier-Set Falabella.gme | 20150820
083 | Dierenset Leeuwen.gme | 20151112
083 | Tier-Set Loewen.gme | 20150820

### Error message
```bash
tttool: Pattern match failure in do expression at src/GMEParser.hs:199:13-24
 when reading segment Line 2
 when reading segment 10204
 when reading segment Scripts
 when reading segment Header
```

### Code
src/GMEParser.hs:197-200
```haskell
        [ (B.pack [0xE0,0xFF], \r -> do
            unless (r == 0) $ fail "Non-zero register for RandomVariant command"
            Const 0x0000 <- getTVal
            return RandomVariant)
```

**Comment by nomeata** [comment]
I need to do something about this, I guess. Of course I can (and should) make the parser ignore the argument to `FFE0`, but it would be good to know if these arguments actually have an effect.

**Comment by NimVek** [comment]
I like to analyse but Haskell is a little bit complicated for me ;)
Is it possible to parse and put then as comment next to the Command in tttool (scripts|export)

**Comment by nomeata** [comment]
> I like to analyse but Haskell is a little bit complicated for me ;)

If you just want to get the bug out of the way, replace `Const 0x0000` with `_`.

>  Is it possible to parse and put then as comment next to the Command in tttool (scripts|export)

Yes, I’ll do something like that.

**Comment by nomeata** [comment]
Ok, I pushed a proper fix. Are you able to test it for me, and report whether it works?
