### ISSUE TITLE
Size and title of file resulting from "tttool oid-code 42" command

### ISSUE THREAD

**Issue by maehw** [entropia/tip-toi-reveng#137]
Hey there,

long time no tiptoi for me. For getting started really quick, I tried the Windows release (v1.6.1) for the first time. I have never tested printing successfully before, so I wanted to prepare for this situation.

It is working, however if understand the comments on http://tttool.entropia.de/ right, the `tttool oid-code 42` command should output a PNG file of size 4800×4800 pixels. I get 1440×1440 pixels instead.

1440 pixels result in 1.2 inches/ 3.048 cm using 1200 dpi.
4800 pixels result in 4 inches/ 10.16 cm using 1200 dpi.
(So I am also not sure if 10×10 cm is meant exact and could therefore result in accuracy problems as an inch equals 2.54 cm and not 2.5 cm?)

Some other minor "issue": the title of the generated PNG file is `Tiptoi OID Code 272` which is the raw code. Maybe also the ID `42` should be included in the title. However, I don't know which program ever uses this meta data.

Cheers

**Comment by nomeata** [comment]
Thanks for the prod! The default changed to 3cm×3cm, as you can see by running `tttool --help`. I updated the webpage.
