### ISSUE TITLE
Building on Ubuntu 14.04 requires aeson<0.11

### ISSUE THREAD

**Issue by chwissing** [entropia/tip-toi-reveng#139]
In order to compile tttool on Ubuntu 14.04 I needed to lower the maximum version of aeson:

aeson       >= 0.7     &&   < 0.11,

It used to be 1.2 in the checked out code. This is likely more an issue of the Haskell platform on the OS itself than a problem with tttool as such. Since I have no clue about that programming language, I just report here, what hack made it work for me.

Cheers, chwis

**Comment by nomeata** [comment]
I’m not sure what you mean. In the checked out code, it currently is
```
    aeson       >= 0.7     &&   < 1.1,
```
Isn’t it?
