### ISSUE TITLE
Wiki: Explain Codes FFE0, FFE1 FB00, FC00

### ISSUE THREAD

**Issue by thoka** [entropia/tip-toi-reveng#146]
In https://github.com/entropia/tip-toi-reveng/wiki/GME-Script-line FFE0 (Play one random sample) and FFE1 (Play all smaples) are described to be both written as P(). Is this so ?

Some lines lower FB00  and FC00 have both the represantation P(b-a). Is there something missing in the docs?

**Comment by thoka** [comment]
I added info from https://lists.nomeata.de/archive/tiptoi/2016/001231.html to the wiki.

**Comment by nomeata** [comment]
Thanks!
