### ISSUE TITLE
error parsing media-path

### ISSUE THREAD

**Issue by voxspox** [entropia/tip-toi-reveng#149]
`tttool assemble` with

    media-path: %s

in the config file leads to:

    InvalidYaml (Just (YamlParseException {yamlProblem = "found character that cannot start any token", yamlContext = "while scanning for the next token", yamlProblemMark = YamlMark {yamlIndex = 541, yamlLine = 15, yamlColumn = 12}}))

line 15 column 12 is the % character of %s.

A `media-path` of `./%s` is accepted as expected.

**Comment by nomeata** [comment]
Hi. The file is a parsed as a YAML file, and all the restrictions of that file format apply here. In particular, if a string starts with one of a few special characters, of which `%` is one, it *has* to be quoted:
```
media-path: "%s"
```
But 
```
media-path: ./%s
```
works just as nicely.

A bit annoying, but unless I start writing my own file format nothing I can fix.

**Comment by voxspox** [comment]
ok. I propose to specify media-path in the example.yaml as explicit string (with quotes): "example/%s". I was altering this file when I was faced with the issue.
Now something else leaps into my mind. Shouldn't the variable be named `media-filepath` because %s is substituted with the filename and the result is the filepath.

**Comment by nomeata** [comment]
>  I propose to specify media-path in the example.yaml as explicit string (with quotes)

Good idea, done.

>  Now something else leaps into my mind. Shouldn't the variable be named media-filepath because %s is substituted with the filename and the result is the filepath.

*shrug* Maybe – but certainly not worth the confusion that changing that would ensure, so I’ll leave it named as it is.

Thanks for your suggestions, they are appreciated!

**Comment by voxspox** [comment]
agree :)
