### ISSUE TITLE
code names in PNG title field (feature request)

### ISSUE THREAD

**Issue by voxspox** [entropia/tip-toi-reveng#150]
To print an image of a scene with oid codes GIMP can be used. `tttool oid-codes` creates some PNGs which can be imported to an image, p.ex. as layers. To have suitable sized oid areas the `--code-dim` option come in handy but the overall process is still cumbersome.

I want to propose a different and very easy way: GIMP can fill area with a fill pattern. The tttool-generated PNGs could be use as fill patterns directly. Just set a path in Preferences / Folders / Patterns to your gme-project. Now just fill an area with the oid code you need.
The fill patterns are displayed in GIMP with the PNG title. Unfortunately in the generated PNG title field is only the raw OID code. It would be comfortable to have the code name here.

I want to propose an tttool option which sets the PNG title just to the code name specified in the yaml file or even better, according to a given pattern.

Current state:

    $ tttool oid-code 1
    Writing oid-1.png.. (Code 1, raw code 5)
    $ exiftool oid-1.png -title
    Title : Tiptoi OID Code 5

Simple option:

    $ tttool oid-codes --png-title=code-name
    Writing oid-1.png.. (Code 1, raw code 5)
    $ exiftool oid-1.png -title
    Title : first_code

Set PNG title according to a given pattern:

    $ tttool oid-codes --png-title="name:{name} raw:{raw} code:{code}"
    Writing oid-1.png.. (Code 1, raw code 5)
    $ exiftool oid-1.png -title
    Title : name:first raw:5 code:1

**Comment by nomeata** [comment]
Great idea!

Shouldn’t maybe the filename of the `.png` file also contain the title?

I’d like to keep things simple and avoid configuration flags when possible. So why not simply always
```
$ tttool oid-codes
Writing oid-1-first.png.. (Code 1, raw code 5)
$ exiftool oid-1-first.png -title
Title : first (code 1, raw 5)
```

**Comment by voxspox** [comment]
The PNGs are already named according to the title ;-)

It seems currently there is only one purpose for the PNG title fields: GIMP fill pattern name. Thus, your example how to format the title field is ok: `first (code 1, raw 5)`. If there is no code name, then maybe just `code 1, raw 5`.

If somebody wants to use tttool inside another tool, of course a more meaningful API/options would be nice.

**Comment by nomeata** [comment]
Ok, implemented. Are you in a position to test the git version?

**Comment by voxspox** [comment]
Yes. Looks good :)

summary:
- generate codes with `tttool oid-codes`
- add path to the generated oid-*.png files in GIMP: Preferences / Folders / Patterns
- restart GIMP
- select Bucket Fill Tool + Fill Type: Pattern Fill + View as List (see screenshot)
- fill your area, if necessary clear area first!
- et voila: OID area

![gimp_oid_fill_patterns](https://user-images.githubusercontent.com/1503565/30019850-32342628-9162-11e7-9c17-5149f635af33.jpg)

**Comment by nomeata** [comment]
Great!

We really should have a proper user-friendly manual explaining how to use tttool, and all the various tips around it, so that others will actually learn about this feature.
