### ISSUE TITLE
syntax highlighter für tttool-YAML

### ISSUE THREAD

**Issue by HorstFrank** [entropia/tip-toi-reveng#151]
Hi,
Ich habe eine syntax highlighter Erweiterung für Prism geschrieben. Damit werden unsere tttool-yaml-sachen farblich dargestellt, wenn man sein Projekt im Netzt präsentiert. Das ganze habe ich in ein Repo gepackt https://github.com/HorstFrank/prism-YAML-tttool-definitions

Ich bin nicht sicher ob das etwas für tip-toi-reveng ist,  dann würde ich das hier irgendwo ablegen.

Wenn das nicht gut in tip-toi-reveng passt, werde ich das nur auf der mailingliste posten. Wäre ja auch okay.

**Comment by Rambaldi1988** [comment]
Vielen lieben Dank Horst Frank,

sowas habe ich gebraucht 😊
http://tiptoi.as-webstyling.de/codierung.php

Klick auf YAML-Datei ein/ausblenden 😊

Ich hoffe ich darf das so verwenden. Hab dich unter dem Code auch erwähnt und verlinkt.
Werde noch die css anpassen, wie ich sie gerne hätte. Hoffe das geht i.O.

Liebe Grüße
André

 

Von: Horst Frank [mailto:notifications@github.com] 
Gesendet: Montag, 4. September 2017 16:15
An: entropia/tip-toi-reveng <tip-toi-reveng@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [entropia/tip-toi-reveng] syntax highlighter für tttool-YAML (#151)

 

Hi,
Ich habe eine syntax highlighter Erweiterung für Prism geschrieben. Damit werden unsere tttool-yaml-sachen farblich dargestellt, wenn man sein Projekt im Netzt präsentiert. Das ganze habe ich in ein Repo gepackt https://github.com/HorstFrank/prism-YAML-tttool-definitions

Ich bin nicht sicher ob das etwas für tip-toi-reveng, ansonsten würde ich das hier irgendwo ablegen.

Wenn das nicht gut in tip-toi-reveng passt, werde ich das nur auf der mailingliste posten. Wäre ja auch okay.

**Comment by HorstFrank** [comment]
Hi André!

Cool, danke :D  ... JA!!!! bitte benutzen :)

Ich bins ... Boris von der Mailingliste :D ... dein Code und die arbeit an der Präsentation von meinem tttool-Projekt waren sogar der Auslöser für das highlighting-ding. 

Viele Grüße,
Horst

**Comment by Rambaldi1988** [comment]
Hey Boris, Horst (oder sonst wie 😃 )

Freut mich, dass das hier so ein tolles Miteinander ist 😊

Ich bin übrigens gerade am Aufbau einer optisch besser Strukturierten Dokumentation, wie man tttool nutzt und vor allem will ich auch Codeschnipsel anbieten.
Daher kommt der Highlighter echt gelegen 😉

Bisher noch nicht „designed“ und noch sehr mager, aber ich arbeite ab und an daran:
http://tiptoi.as-webstyling.de/doku.php

Freue mich über Meinungen und Feedback.
Aber wie gesagt. Aktuell noch in der Anfangsphase und noch nicht viel drin 😉

Grüße
André

P.S.: Will das machen, da ich bei meinen ersten Schritten immer alles irgendwie zusammensuchen musste 😊
Hoffe diese Doku hilft dann „Neulingen“ und auch euch allen.
Gerade durch Codeschnipsel will ich es ALLEN erleichtern.



 

Von: Horst Frank [mailto:notifications@github.com] 
Gesendet: Montag, 4. September 2017 16:36
An: entropia/tip-toi-reveng <tip-toi-reveng@noreply.github.com>
Cc: Rambaldi1988 <andre@christina-und-band.de>; Comment <comment@noreply.github.com>
Betreff: Re: [entropia/tip-toi-reveng] syntax highlighter für tttool-YAML (#151)

 

Hi André!

Cool, danke :D ... JA!!!! bitte benutzen :)

Ich bins ... Boris von der Mailingliste :D ... dein Code und die arbeit an der Präsentation von meinem tttool-Projekt waren sogar der Auslöser für das highlighting-ding.

Viele Grüße,
Horst

**Comment by HorstFrank** [comment]
Hi André,

Das ist ein guter Anfang. Und ich weiß genau was du meinst. Ich muss mir auch immer alles zusammensuchen aus dem Wiki hier, aus der Mailingliste usw. Ich hatte auch schon überlegt ein Wiki anzufangen, und dort alles (gerade was yaml-coding betrifft) mal zu sammeln. Das muss man sich als Neuling schon recht mühsam zusammensammeln.

Viele Grüße,
Boris

**Comment by nomeata** [comment]
Natürlich darf der Code in dieses Repo (z.B. im Unterverzeichnis `prism-syntax-highlighter`). Mach einfach einen Pull Request.

**Comment by HorstFrank** [comment]
Cool! danke .. dann mache ich die example.html nochmal etwas erklärender. kommt die tage.

**Comment by nomeata** [comment]
Das ist mit 1c05889746166a387edae160e58987e867471527 wohl erledigt.
