### ISSUE TITLE
Tiptoi in French strange problems with Globe

### ISSUE THREAD

**Issue by tavibe** [entropia/tip-toi-reveng#153]
Hi,

I'm so happy to have found this group. 
I bought the Interactive Globe in French and the Atlas book in French that came with the pen.
I activated the pen in French with the Atlas, it's working fine, except for the songs that are in German... my kids like the songs in German :)

On the other hand I can't make it work with the Globe. I installed the Tiptoi manager, downloaded the Globe interactive package and then it was installed on the pen, the pen said it was successfully installed. 
But when I point the pen to the green "on" button it says 2-3 words "Bienvenue au Globe..." and then it dies completely (it switches off by itself).

I'm running the latest firmware version (TR030138) , the tiptoi manager wanted to update the firmware, and that happened well as well. 

I do not know if my pen is new or old, I see it has 6.83GB capacity.

I'm not using the ttool, but I believe that I have to do that. I wrote to ravensburger with no reply. I'd like to return the globe, but I can't find all the other parts of the package and it could be that the pen has something wrong since the songs are in German. I've seen that somebody else reported the same issue with songs in German on a French pen. I do not mind the songs in German but I'm taking it as a sign that the pen is malfunctioning. 

Do you have any idea where to start?
Any advice would be greatly appreciated as my son was so much looking forward to it, it was his birthday present... and now the globe it's not working.

Thank you very much

**Comment by nomeata** [comment]
Sorry to send you in circles, but I think more people are reading the mailing list at https://lists.nomeata.de/mailman/listinfo/tiptoi than this issue tracker. You should try again there.

(Closing this as it is not an issue with `tttool`.)
