### ISSUE TITLE
Tiptoi no turn on

### ISSUE THREAD

**Issue by nings007** [entropia/tip-toi-reveng#171]
Hello,

I have a tiptoi B6 (4 GB) but won't turn on.

- With batteries 3.07v on the red and black cable on the pcb and nothing on the VDDIO/GND points but when I push the power button, 3.26v between VDDIO/GND points
- Fuse RT1 is good
- With usb cable and batteries when I push the power button 3.26v and after release 2.4v between VDDIO/GND points (nothing after remove usb plug)
- no light on the power button when I push it and no sound at all

I try the "test mode" but not working and try the "USB Storage Boot Mode" with a 470ohm resistor (may be that need really 800/1kohm ?) but not recognized by the computer. I use a standard USB cable (should use only the original cable ?).

Thank you for your help ;)

**Comment by B-G-T** [comment]
Hi,

If you let me know your email address, I can send you a schematic of the 
TT B6.

As the schematic is based on reverse engineering, it is probably not 
100% accurate but it might be nevertheless a good start for your 
diagnostics ...



Am 26.12.2017 um 15:27 schrieb nings007:

**Comment by wernight** [comment]
I tried changing language (I found some elements of the documentation not very clear) and ended up bricking the pen ([the README](https://github.com/entropia/tip-toi-reveng/wiki/Firmware) should state clearly that it may brick the pen). Anyway I managed to get the boot mode (once enabled, the power light turns green while GPIO13 is connected).

Looked also at https://github.com/entropia/tip-toi-reveng/issues/132 and similar... but found no way to flash or unbrick the device, or access the device as a mass storage and update the `LanguageInfo2.txt`.

**Comment by nings007** [comment]
Thank you for your reply, can you send this schematic to 007liamg007@gmail.com please ?

Great news... why is so hard to repair electronic material now ? :(
Something no power on, you replace the fuse or power supply and should be fine...

**Comment by wernight** [comment]
E-mailed, let me know if you need something more.

**Comment by maehw** [comment]
@wernight Can you please elaborate on the procedure which actually broke your pen (if you know it)?

**Comment by wernight** [comment]
The LanguageInfo2.txt was like

3
999 GERMAN Foo.upt
998 FRENCH Foo.upt
997 ...

I swapped 998 with 999 and placed the French update files in system
directory and root directory (as copy). Then unplugged and powered on the
pen.

**Comment by kaiminator** [comment]
Hi,

has this issue been resolved? I got a B6 from the neighbors. The pen has been working right before my wife connect the usb cord with an external 5v power supply to load the internal akku. Yes, u know it - it has not an internal akku :-) Since then the pen ist broken. Fuse is ok with no resitance, 3,3 v on pcb. Any hints to debug this? Any schmematic?

**Comment by B-G-T** [comment]
Hi,

If you let me know your email address, I can send you a schematic of the TT B6. As the schematic is based on reverse engineering, it is probably not 100% accurate but it might be nevertheless a good start for your diagnostics ...
Please share what was broken if you can identify the problem.

**Comment by kaiminator** [comment]
Hey,

please send it to kaiminator@protonmail.com - i am not 100% expert in debugging circuits but i will do my best and will share if the problem was found

**Comment by elph-jr** [comment]
@kaiminator Hi, did you find the solution? I have the same problem.
@B-G-T could you please send the schematic of the TT B6 to elph_jr@mail.ru?

**Comment by wernight** [comment]
The biggest issue for me was that it bricked a device (which I could get replaced and then managed to support another language). Unbricking is the most crutial missing piece to toy with another device IMO.

**Comment by B-G-T** [comment]
@nings007 @kaiminator @elph-jr :
Could you fix your pens? If yes, what was the issue and how did you solve it?

**Comment by Hitschkock** [comment]
Hi @ all,
i have still the same problem! The only different is, i have a 174 R6 board. Please can somebody send me the circuits too.

Do some one have the Datasheet for processor ZC3203L and will send it to me.

krause@arcor.de

greetings Frank

**Comment by jore011** [comment]
@B-G-T could you please send the schematic of the TT B6 to gullu0815@arcor.de?

**Comment by B-G-T** [comment]
@jore011:
gullu0815@arcor.de:
SMTP error from remote server for RCPT TO command, host: mx002.vodafonemail.xion.oxcs.net (157.97.76.175) reason: 550 5.5.0 Unknown Recipient OX_500

**Comment by jore011** [comment]
@B-G-T sorry, i mean: gulli0815@arcor.de

**Comment by vin883** [comment]
@B-G-T  could you also please send me the TT B6 schematic at: contact@vrtec.fr ?
Thanks!!

**Comment by Seal1984** [comment]
Hi @ all,

hope someone is able to help me. I have a TipToi pen (1742R6) and after turning it on, there is no reaction (just the light). It is also not recognized through the PC. I tried to put it in Boot mode, but there is no GPIO13 testpad on the PCB. I tried with pulling down the TX testpad , but it was not working. The controller itself is a ZC3203L and it seems as if it is not pin compatible with the ZC3202N. Can someone tell me how to get into the boot mode with this version?

Thanks and regards

**Comment by B-G-T** [comment]
> I tried to put it in Boot mode
You mean what is called "Mass Storage Boot" on https://github.com/entropia/tip-toi-reveng/wiki/PEN-Hardware-Details ?

I would assume that ZC3203L and ZC3202N are basically pin-to-pin compatible.
What parts/test pads are connected to pin39 of your ZC3203L?

Can you share pictures of front and back of your 1742R6 for publication on https://github.com/entropia/tip-toi-reveng/wiki/PEN-Revisions ? This would make it more simple to identify possible test points.

**Comment by Seal1984** [comment]
Hi,

The R6 looks similar to the R5. But as I could reverse engineer, PIN39 has no testpad. Also the crystal seems to be on a different PIN as it is at the ZC3202. Perhaps I am wrong with PIN 1, but I think it is marked on the PCB.

![20200322_163256](https://user-images.githubusercontent.com/6429019/77253562-6a54fd80-6c5b-11ea-99a8-50c92bc1c252.jpg)
![20200322_163228](https://user-images.githubusercontent.com/6429019/77253588-822c8180-6c5b-11ea-9de2-d0c68af41cbe.jpg)

**Comment by B-G-T** [comment]
It would be helpful to know how far in the booting process is comes.
Is the LED flashing as it should (once every 10 s)? This would mean that it basically boots fine from NAND flash.
If you have an SDR available, you could also check how much vital signs you can see.

**Comment by Seal1984** [comment]
The LED is flashing every 10s but there is no sound and the PC does not show any device when connected. I have a oszilloskope for testing available.

**Comment by Hitschkock** [comment]
Hi@all,
with what software do all of you write the firmware into the Tiptoi-pen?
please send me some links.

greetings Frank

**Comment by fritsjan** [comment]
I have a broken tiptoi, the inductor L10 is fysically broken.
Does anyone know the value of this inductor so I can replace it?

![image](https://user-images.githubusercontent.com/1918415/82888202-54103a00-9f49-11ea-811f-b0278d37f49c.png)

**Comment by fritsjan** [comment]
Anyone? An educated guess would also be appreciated.
Or maybe a schematic? Can be sent to mail @fritsjan . nl 
The name/type of te U5 part might also be enough, then I could find the datasheet and follow their recommendation of the inductor.

**Comment by Hitschkock** [comment]
I Hope it's enough
![20200601_212413](https://user-images.githubusercontent.com/23487369/83446358-d10e4880-a44e-11ea-94fb-fa55703f4749.jpg)

**Comment by B-G-T** [comment]
U5 is a 3.3V voltage regulator, L10 is connected directly to its input. The reading pen reference design you can find on the Internet does not show any inductor there.
I therefore suppose its value is very uncritical.

**Comment by fritsjan** [comment]
Thank you all, I will try to find one inductor with the same size and will replace this broken one, hope it works ;-)

**Comment by nomeata** [comment]
Closing this, as there is no issue with the code. Feel free to continue discussing this here, though.

**Comment by B-G-T** [comment]
Hi Majuss, I am not sure but would assume that the the ZC3203L handles the boot mode selection exactly like the CZ3202N does. I would therefore try to identify at first GPIO13 by probing different test points etc.

**Comment by majuss** [comment]
For that kind of work the datasheet would be nice :D I could also attach a wire directly to pin 39 if I know which one it is.

**Comment by maehw** [comment]
Hi guys,

https://github.com/entropia/tip-toi-reveng/wiki/PEN-Hardware-Details provides a lot of details about the hardware and how to enter the different boot modes.

What are you expecting from a special boot mode?

Do you see the USB masss storage device on your PC?

Cheers

**Comment by majuss** [comment]
Unfortunately I have the R6 of the pen and this revision is nowhere documented. I want to reflash the firmware via the burn tool. Yes I see the pen as a storage drive, but the tiptoi manager is failing to recognize the pen and as I said the UDISK test fails.

**Comment by majuss** [comment]
So nobody can help me fix my pen? The datasheet for the ZC3203L is not available?

**Comment by mley** [comment]
I know this is a fairly old thread on a closed issue. But maybe some people have some knowledge to share.

I got a used R1, that after uploading the (original) audio files always only said "Please upload the audio files for this product". Even after a reformat of the filesystem and re-uploading the files. Then I tried to reformat the device with overwriting everything (secure erase/formatting on MacOS, first random data, then zeros). That process failed and now the device is not recognised as USB mass storage any more. There is no sound when I turn the device on, only the green LED lights up, and stays on for a minute or so. During that time I can't turn it off with the button. I have to remove the batteries to turn it off. When it turned off on it's own, I cannot turn it on again unless I remove the batteries. 

`dmesg` (on Linux) shows nothing when plugged in. Also no reaction trying to enable test mode.

**Comment by B-G-T** [comment]
If it's not a HW defect, probably the best way to fix it is to flash it from scratch:
https://github.com/entropia/tip-toi-reveng/wiki/PEN-Firmware#usb-storage-boot-mode-firmware-flashing

**Comment by mley** [comment]
@B-G-T Thanks. I will try that.

**Comment by faroit** [comment]
@fritsjan did you manage to fix the inductor? if yes, where did you source L10 with these dimensions?

**Comment by fritsjan** [comment]
No I did not. Too much hussle
But if , I would have sourced from farnell or mouser.
Problem is, I do not know the inductor value.

Frits Jan van Kempen
ProductBakery
________________________________
Van: Fabian-Robert Stöter ***@***.***>
Verzonden: Friday, April 26, 2024 12:06:49 PM
Aan: entropia/tip-toi-reveng ***@***.***>
CC: Frits Jan van Kempen ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [entropia/tip-toi-reveng] Tiptoi no turn on (#171)


@fritsjan<https://github.com/fritsjan> did you manage to fix the inductor? if yes, where did you source L10 with these dimensions?
