### ISSUE TITLE
export/media/assemble does not work out of the box

### ISSUE THREAD

**Issue by frisi** [entropia/tip-toi-reveng#173]
trying to replace an audio file for "WWW Feuerwehr.gme"

the export adds leading zeros to filenames (eg `0` is dumped as `0000.ogg`)

```
$ tttool export "WWW Feuerwehr.gme"
$ tttool media "WWW Feuerwehr.gme"                  
Audio Table entries: 878
Dumped sample 0 as media/WWW Feuerwehr_0000.ogg
Dumped sample 1 as media/WWW Feuerwehr_0001.ogg
Dumped sample 2 as media/WWW Feuerwehr_0002.ogg
...
```

in the yml file, sound files are referred w/o leading zeros

```yml
media-path: media/WWW Feuerwehr_%s
welcome: 876,877
product-id: 2
```

when assembling the (modified) yml file again, the sound files can't be looked up properly:
```
$ tttool assemble "WWW Feuerwehr.yaml" feuerwehr-custom.gme
...
Could not find any of these files:
./media/WWW Feuerwehr_876.wav
./media/WWW Feuerwehr_876.ogg
./media/WWW Feuerwehr_876.flac
./media/WWW Feuerwehr_876.mp3
...
```

**Comment by nomeata** [comment]
Oh, good point. This bug was introduced in https://github.com/entropia/tip-toi-reveng/commit/c6bdd86fd4956ae8162fae038fd40b3ad2ac7362 (#172). I’ll revert that for now…
