### ISSUE TITLE
Roundtrip for Feuerwehr - game broken

### ISSUE THREAD

**Issue by frisi** [entropia/tip-toi-reveng#174]
when round-tripping http://static.tiptoi.com/db/applications/WWW%20Feuerwehr.gme
i noticed that a game is not working (i know there are warnings in the docs that games might be broken) but i though reporting a bug might result in certain games being fixed in the future.

* starting a game : script id 4558
* choose game 2 (green star) for selecting the right object for a sound: script id 4560

now the game is explained and the first sound is played.
if you tip the correct object it should say:

"now you'll hear 2 sounds in a row" and play the first sound and a second one

but what happens is that it says
"now you'll hear 2 sounds in a row" "now you'll hear 3 sounds in a row" ... "now you'll hear 6 sounds in a row" and then it plays 2 sounds.
if you choose the correct objects the game is stopped and a completely different sound is played

uid 4547 im mode 3: "der schlauchturm ist für uns ein super übungsplatz..."

```yml
  4547:
  - $0==1? P(111)
  - $0==2? P(110)
  - $0==3? P(112) P(28) P(7)
```

**Comment by nomeata** [comment]
If you export to yaml, import to gmp and then again export to yaml, do you get a different yaml file?

**Comment by frisi** [comment]
yes they differ. looks like the differences are only names for the soundfiles.

here is what i did:

```
$ tttool export feuerwehr-orginal.gme
$ tttool media feuerwehr-orginal.gme
$ tttool assemble feuerwehr-orginal.yaml feuerwehr-assembled.gme
$ tttool export feuerwehr-assembled.gme
$ diff feuerwehr-assembled.yaml feuerwehr-orginal.yaml
```

and this are both yaml files (renamed to txt to make the github upload work)

[feuerwehr-assembled.yaml.txt](https://github.com/entropia/tip-toi-reveng/files/1597941/feuerwehr-assembled.yaml.txt)

[feuerwehr-orginal.yaml.txt](https://github.com/entropia/tip-toi-reveng/files/1597942/feuerwehr-orginal.yaml.txt)

**Comment by nomeata** [comment]
Thanks. Yes, that looks good so far…

The code that reads and writes games is pretty ugly, not unlikely that there is a bug. (But I then I would expect that repeated round-tripping would show differences.)

**Comment by nomeata** [comment]
Could you do me a favor and find which sound file corresponds to the correct string that you should hear, and which to the other sounds that you hear in the round-tripped GME?

**Comment by nomeata** [comment]
Man darf hier auch Deutsch reden, insbesondere wenn man die Audio-Samples beschreibt :-)

**Comment by nomeata** [comment]
Hab ein bisschen rumgeschaut und ein paar Audio-Samples angehört, aber keinen offensichtlichen Bug gefunden. Vielleicht will @NimVek, der die Games selbst entschlüsselt hat, sich das anschauen?

**Comment by JoWi81** [comment]
Hallo zusammen, ich habe scheinbar das gleiche Problem wie frisi. Ich habe festgestellt, dass die Binärdateien für die Spiele nicht mit übernommen werden.

Mit folgenden Schritten habe ich dieses Problem festgestellt:
```
tttool binaries "Bilderlexikon Tiere orig.gme"
Binary Table entries: 16
Dumped binary Game1.bi from block 1 as binaries/1_Game1.bi
Dumped binary Game2.bi from block 1 as binaries/1_Game2.bi
Dumped binary Game3.bi from block 1 as binaries/1_Game3.bi
Dumped binary Game4.bi from block 1 as binaries/1_Game4.bi
Dumped binary Game5.bi from block 1 as binaries/1_Game5.bi
Dumped binary Game6.bi from block 1 as binaries/1_Game6.bi
Dumped binary Game7.bi from block 1 as binaries/1_Game7.bi
Dumped binary Game8.bi from block 1 as binaries/1_Game8.bi
Dumped binary Game1.bi from block 2 as binaries/2_Game1.bi
Dumped binary Game2.bi from block 2 as binaries/2_Game2.bi
Dumped binary Game3.bi from block 2 as binaries/2_Game3.bi
Dumped binary Game4.bi from block 2 as binaries/2_Game4.bi
Dumped binary Game5.bi from block 2 as binaries/2_Game5.bi
Dumped binary Game6.bi from block 2 as binaries/2_Game6.bi
Dumped binary Game7.bi from block 2 as binaries/2_Game7.bi
Dumped binary Game8.bi from block 2 as binaries/2_Game8.bi
```

```
tttool rewrite "Bilderlexikon Tiere orig.gme"  "Bilderlexikon Tiere rewr.gme"
tttool binaries "Bilderlexikon Tiere rewr.gme"
Binary Table entries: 0
```

**Comment by nomeata** [comment]
Ne, das ist ein anderes Problem: “Games” und “Binaries” sind zwei verschiedene paar Schuhe.

**Comment by frisi** [comment]
@nomeata 
ich helfe gern weiter. verstehe aber im moment noch nicht wie das möglich sein kann.


das spiel funktioniert so:

tiptoi spielt einen sound.
user klickt auf passendes objekt
tiptoi sagt: "jetzt hörst du 2 geräusche" und spielt zwei sounds
user klickt auf erstes und zweites passendes objekt
toptoi sagt "jetzt hörst du 3 geräusche" und spielt die ersten zwei und einen zusätzlichen.


welche sound files abgespielt werden ist also zufall.

in der round tripped version funktoniert das spiel bis zum tippen des ersten passenden sounds.
dann kommt die ansage für den zweiten, gefolgt von "jetzt hörst du 3" und "jetzt hörst du 4" bis zu sechs.
dann zwei geräusche und dann bist du nach dem tippen von zwei objekten aus dem spiel und ganz wo anders (andere seite im buch - objektid und sound oben beschrieben)

**Comment by nomeata** [comment]
Kannst du zu diesen Sounds die Nummer raussuchen und dazuschreiben? (Du musst nicht alle Sounds ausprobieren, vermutlich reicht es die Sounds auszuprobieren, die im Abschnitt `games` erwähnt werden.) Das würde es einfacher machen, das Spiel nachzuvollziehen.

**Comment by frisi** [comment]
klar. ich hoffe folgendes hilft weiter:

so sieht sie seite aus:
![ratespiel](https://user-images.githubusercontent.com/1120517/34530801-8d67de88-f0b0-11e7-845d-f8e1e4ef4060.jpg)

würfel-taste:
```yaml
  4558:
  - $0==1? $0:=4 G(1)
```

wir haben hier zwei spiele für dich, beim roten stern kannst du ein quiz spielen, beim grünen wartet ein geräuschespiel auf dich.

roter stern: 4559
grüner stern: 4560


sound dateien für das spiel:

683: spielerklärung "du hörst jetzt nacheinander verschiedene geräusche, tippe die dazugehörigen bilder in der reihenfolge an..."
684: hier kommt das erste geräusch
685: jetzt hörst du zwei
686: geräusche hintereinander
687: jetzt hörst du drei
688: jetzt hörst du vier
689: jetzt hörst du fünf
690: jetzt hörst du sechs
692: katze
693: hör' nochmal genau hin
694: sirene
695: hund
696: feuer
697: baby
698: sirene
699: motor

**Comment by frisi** [comment]
hab grad noch die uids von den einzelnen objekten dazugegeben. damit sollte eigentlich das spiel mit `ttool play` von der orginal-datei nachgespielt werden können. funktioniert aber leider nicht - vermutlich weil tttool die befehle noch nicht korrekt auslesen/interpretieren kann

```
$ tttool play "WWW Feuerwehr.gme" 
Initial state (not showing zero registers): $0=1
Playing audio sample 876
Playing audio sample 877
# tipp auf würfel und den grünen stern spielt schon keine sounds ab
Next OID touched? 4558
Executing:  $0==1? $0:=4 G(1)
State now: $0=4
Next OID touched? 4560
Executing:  $0==4? G(3)
State now: $0=4
```

**Comment by nomeata** [comment]
Ok, die falsch erklingenden Sounds sind in der YAML-Datei alle in diesem Feld des entsprechenden Spiels:

      roundendplaylist: 685,686,612,687,686,612,688,686,612,689,686,612,690,686,612,612

Klar erkennbar gehören hier immer drei Audio-Dateien zusammen. Ich hab ne Idee…

**Comment by nomeata** [comment]
Ja, ich glaub ich habs. In der GME-Datei ist das tatsächlich eine List von Listen von Audio, und der Yaml-Export/Import hat die Information weggeschmissen. Wenn ich das versuche zu fixen, dann steht da

```
  roundendplaylist:
  - 685,686,612
  - 687,686,612
  - 688,686,612
  - 689,686,612
  - 690,686,612
  - '612'
```

Sieht gut aus, oder?

@frisi, kannst du das tttool selber bauen? Dann probier doch mal den branch `retain-playlistlists` und schau ob das deine Probleme löst. (Wenn du das nicht kannst und Windows benutzt, dann schick mir ne Mail und ich schick dir ein Binary).

**Comment by frisi** [comment]
kann ich selber bauen und werde das asap ausprobieren.

**Comment by frisi** [comment]
hab jetzt alle spiele im buch kurz ausprobiert - scheint gut zu funktionieren!

**Comment by frisi** [comment]
danke. hat auch tagelange tests durch die kleinen bestanden ;-)

**Comment by JoDaEmPa** [comment]
Hallo frisi ! Ich weiss nicht wie mann das tttool umschreibt und "retain-playlistlists" einfügt ! könnte ich die veränderte tttool.exe haben ?

**Comment by frisi** [comment]
@JoDaEmPa für eine exe datei musst du dich an @nomeata wenden. ich weiss nicht wie man die baut - sorry :-(

**Comment by JoDaEmPa** [comment]
Danke frisi ... hatte sich hier so gelesen als ob du das mit dem branch retain-playlistlists selber gemacht hättest.

kann ich selber bauen und werde das asap ausprobieren.

**Comment by nomeata** [comment]
Der code ist inzwischen auf `master`, gab nur noch kein offiizelles Release bisher. Extra-testing wäre super, danke @JoDaEmPa

**Comment by JoDaEmPa** [comment]
Würden wir gerne testen, aber was heisst "master" ? Ist klasse, dass Du immer noch bei diesem Projekt  soviel Engagement zeigst !

**Comment by nomeata** [comment]
`master` ist der aktuelle Entwicklerstand. Den bekommst du wenn du z.B.
```
git clone https://github.com/entropia/tip-toi-reveng
```
eingibst.

**Comment by JoDaEmPa** [comment]
Wir sind Windows-User ... den Entwicklungsstand von 
29 Aug 2017 | 1.7.0.4
habe ich gesehen, aber wie bekomme ich davon eine exe ?

**Comment by KOTRET** [comment]
@JoDaEmPa entweder [selbst kompilieren](https://github.com/entropia/tip-toi-reveng#installation) oder @nomeata ganz lieb fragen ob er ein Release bereitstellt :)

**Comment by nomeata** [comment]
Euer Wunsch ist mein Befehl: https://github.com/entropia/tip-toi-reveng/releases/tag/1.8

**Comment by JoDaEmPa** [comment]
Suuupperrr ! Scheint alles zu klappen bei Memory !

**Comment by JoDaEmPa** [comment]
Klasse Memory scheint jetzt alles zu funktionieren mit eigenen Sounds ! Interesse an der GME ?

Gesendet: Dienstag, 06. Februar 2018 um 15:20 Uhr
Von: "Joachim Breitner" <notifications@github.com>
An: entropia/tip-toi-reveng <tip-toi-reveng@noreply.github.com>
Cc: JoDaEmPa <vergissx@gmx.de>, Mention <mention@noreply.github.com>
Betreff: Re: [entropia/tip-toi-reveng] Roundtrip for Feuerwehr - game broken (#174)


Euer Wunsch ist mein Befehl: https://github.com/entropia/tip-toi-reveng/releases/tag/1.8

**Comment by nomeata** [comment]
> Interesse an der GME ?

Nö, aber freut mich zu hören dass es klappt! :-)
