### ISSUE TITLE
Rekorde im Tierreich Memory

### ISSUE THREAD

**Issue by JoDaEmPa** [entropia/tip-toi-reveng#176]
Wenn ich die GME Datei in YAML und in Media OGG umwandele und einfach wieder zurück packe ist der Spiel ablauf kaputt !

**Comment by nomeata** [comment]
Ja, wir haben leider noch nicht alle Aspekte von GME-Dateien verstanden. 

Ich hab mir die Datei gerade angeschaut – es kommen keine binaries drin vor (der größte Happen). Und bei Games haben wir kürzlich was gerichtet (#174). Also vielleicht tut es mit der aktuellen Entwicklerversion schon!

**Comment by JoDaEmPa** [comment]
Danke für die schnelle Antwort ! Es ist dasselbe Problem..... ich werde ein bissel rumprobieren..... Ich habe das Memory mit deiner tollen Beschreibung neu vertont... und viel Spaß ! Aber als echtes Spiel klappt's halt nicht....
