### ISSUE TITLE
 There is data after the audio files, file would not work afterwards!

### ISSUE THREAD

**Issue by foward** [entropia/tip-toi-reveng#177]
Hi!! 

I am trying to replace the Audios of the game "Sprichst du Englisch " to my nephew in spanish but when I run the lib tiptoi said 

```
> Franciscos-MBP:tttool friveros$ ./libtiptoi r ./libtiptest/libtiptestfilelist.txt Sprichst_Du_Englisch_new.gme Sprichst_Du_Englisch.gme 
> 
> There is data after the audio files, file would not work afterwards!
```

Could you please help me how can I replace the audios from German to Spanish ? ... I have all identified and I wanted to replace with the spanish translation ... Thank you in advance!!! really cool project!!

**Comment by nomeata** [comment]
Sorry, `libtiptoi` isn’t really mainained. You can use `tttool` to replace the audio (but might lose a few features like some of the  “games” in the process), see https://tttool.readthedocs.io/de/latest/erste-schritte.html#tone-in-tiptoi-buchern-andern
