### ISSUE TITLE
Language switch

### ISSUE THREAD

**Issue by FabianRoger** [entropia/tip-toi-reveng#181]
Hej. 

I just stumbled across this amazing repo after being enraged after finding out that Ravensburger would not allow having two different languages on the same pen. While some cool options seem to exist, for now, it would be enough to be able to switch one of our two German pens to French. 

In the [wiki](https://github.com/entropia/tip-toi-reveng/wiki/Firmware#firmware-version-string), it is described how to achieve this but before I end with a brick I would like to double check:

In my German pen, the file `LanguageInfo.txt` is missing but there is a file called `LanguageInfo2.txt` which has the described format which looks like this 

    5
    999 GERMAN Update3203L.upd
    998 FRENCH Update3203L_fr.upd
    997 DUTCH Update3203L_nl.upd
    996 ITALIAN Update3203L_it.upd
    995 RUSSIA Update3203L_ru.upd
    994 ENGLISH Update3203L_en.upd
 
+ here I change to `998 GERMAN and 999 FRENCH`?
+ copy the file `Update3203L_fr.upd` with the md5sum `a3916c084ca3bb3733b4eb3444a2aa05` onto the stick
+ restart the stick **and activated it again using an activation sheet** (which might be a problem as I am not we have hay of those left)

also, we seem to have the **4 GB version**. 

could you confirm that this is the procedure? (naturally with absolutely no guarantees)

thanks for the help!

Fabian

**Comment by nomeata** [comment]
Not sure if you reach the right audience here. Maybe you should subscribe to and post this on https://lists.nomeata.de/mailman/listinfo/tiptoi?

**Comment by uli42** [comment]
IIRC you do not need the activation sheet for this procedure. Unfortunately there was at least one user who bricked several _newer_ pens this way. We now know how to flash broken tiptois so it might be possible to repair such bricked pens. And it should also be possible to flash the firmware for the desired language directly without having to deal with LanguageInfo.txt
