### ISSUE TITLE
Cannot build on Ubuntu 16/04

### ISSUE THREAD

**Issue by Dupplicate** [entropia/tip-toi-reveng#182]
When trying to build tttool I get conflicts I do not understand (not a haskell programmer) 
Do I have to upgrade or downgrade haskell or is there a different problem?

cabal: Could not resolve dependencies:
trying: tttool-1.8 (user goal)
trying: base-4.8.2.0/installed-0d6... (dependency of tttool-1.8)
trying: blaze-svg-0.3.6.1 (dependency of tttool-1.8)
trying: blaze-markup-0.8.2.0 (dependency of blaze-svg-0.3.6.1)
trying: blaze-builder-0.4.1.0 (dependency of blaze-markup-0.8.2.0)
trying: semigroups-0.18.4 (dependency of blaze-builder-0.4.1.0)
trying: semigroups-0.18.4:+transformers
trying: transformers-compat-0.6.0.6 (dependency of
semigroups-0.18.4:+transformers)
next goal: transformers (dependency of semigroups-0.18.4:+transformers)
rejecting: transformers-0.4.2.0/installed-814... (conflict:
transformers-compat-0.6.0.6:four => transformers>=0.5.3 && <0.6)
trying: transformers-0.5.5.0
trying: semigroups-0.18.4:+hashable
trying: semigroups-0.18.4:+unordered-containers
trying: semigroups-0.18.4:+text
trying: semigroups-0.18.4:+tagged
trying: semigroups-0.18.4:+deepseq
trying: semigroups-0.18.4:+containers
trying: semigroups-0.18.4:+bytestring
trying: semigroups-0.18.4:+binary
trying: yaml-0.8.28 (dependency of tttool-1.8)
next goal: resourcet (dependency of yaml-0.8.28)
rejecting: resourcet-1.2.0 (conflict: base==4.8.2.0/installed-0d6...,
resourcet => base>=4.9 && <5)
rejecting: resourcet-1.1.11, 1.1.10, 1.1.9, 1.1.8.1, 1.1.8, 1.1.7.5, 1.1.7.4,
1.1.7.3, 1.1.7.2 (conflict: transformers-compat==0.6.0.6, resourcet =>
transformers-compat>=0.3 && <0.6)
rejecting: resourcet-1.1.7.1, 1.1.7, 1.1.6, 1.1.5, 1.1.4.1, 1.1.4, 1.1.3.3,
1.1.3.2, 1.1.3.1, 1.1.3, 1.1.2.3, 1.1.2.2 (conflict: transformers==0.5.5.0,
resourcet => transformers>=0.2.2 && <0.5)
rejecting: resourcet-1.1.2.1, 1.1.2, 1.1.1, 1.1.0.1, 1.1.0, 0.4.10.2,
0.4.10.1, 0.4.10, 0.4.9, 0.4.8, 0.4.7.2, 0.4.7.1 (conflict:
transformers==0.5.5.0, resourcet => transformers>=0.2.2 && <0.4)
rejecting: resourcet-0.4.7, 0.4.6, 0.4.5, 0.4.4, 0.4.3, 0.4.2, 0.4.1, 0.4.0.2
(conflict: base==4.8.2.0/installed-0d6..., resourcet => base>=4.3 && <4.7)
rejecting: resourcet-0.4.0.1, 0.4.0, 0.3.3.1, 0.3.3, 0.3.2.2, 0.3.2.1, 0.3.2
(conflict: transformers==0.5.5.0, resourcet => transformers>=0.2.2 && <0.4)
rejecting: resourcet-0.3.1, 0.3.0 (conflict: transformers==0.5.5.0, resourcet
=> transformers>=0.2.2 && <0.3)
Backjump limit reached (change with --max-backjumps).

**Comment by nomeata** [comment]
looks like you are using GHC-7.10. In principle, that is supported. Can you try
```
cabal install --constraint 'transformers-compat <0.6'
```

**Comment by Dupplicate** [comment]
yes, Ubuntu 16.04 is on ghc 7.10.3.

With your constraint tttool builds now.

Thanks a lot!
