### ISSUE TITLE
Inch / cm conversion - wrong calculation

### ISSUE THREAD

**Issue by SciLor** [entropia/tip-toi-reveng#184]
see https://github.com/entropia/tip-toi-reveng/blob/master/src/Commands.hs

you calculate with 25 instead of 25,4. I already wondered why the size of the created pngs were wrong (a bit to big).

**Comment by nomeata** [comment]
Can you try if this code yields the result you need expect:
```
    w' = round $ (fromIntegral w * cDPI conf) / 25.4
    h' = round $ (fromIntegral h * cDPI conf) / 25.4
```

**Comment by SciLor** [comment]
I have no buildchain here for the application.

It should give following results: 7016px x 4961px - 297mm x 210mm

**Comment by nomeata** [comment]
Are you working on Windows? I can build a development release for you to test.

**Comment by SciLor** [comment]
Yes, I am on Windows. Then I will cross check it.

**Comment by nomeata** [comment]
Does this work as intended?
[tttool-win32-1.8-1-g7c615c9.zip](https://github.com/entropia/tip-toi-reveng/files/1829675/tttool-win32-1.8-1-g7c615c9.zip)

**Comment by SciLor** [comment]
Works as expected. Great!

Please don't forget a legacy option. Maybe by giving the option the set a canvas in pixels and not in cm.

**Comment by nomeata** [comment]
I don’t think a legacy option is needed. So far, nobody has required so much precision, it seems.

**Comment by SciLor** [comment]
Maybe I am the first one who tried to use a professional toolset and patterns.
The idea I use is to always create a full sized oid.png(s) and overlay it with a mask with a free shape. That way I can easily overlay complex objects and change them even in shape easily without recreating the oid.png(s). In addition I have linked the oid.png(s) in the project. That way I can easily can exchange just the oid.png(s), if I want to print a different oid-pattern size or if you want to exchange the oid-codes.
The problem with the linked oid.png(s) is, that they have a fixed size. So if the oid.png(s) change in pixel-size those linked objects are scale automatically in size.

In my case it would be important, to have a legacy option, because otherwise I would need to change dimensions more than 70 codes in my image file. Maybe I can do that with a script automatically, but it would be easier to have the option to specify the size of the png in pixels. But that would be more or less a new feature.

OT:
I may describe that workchain further, if I have some time, in my blog. I created a paper version of [Mickey's ABC](https://archive.org/details/msdos_Mickeys_ABC_-_A_Day_at_the_Fair_1992). I used a older EVGA version of it. It is really bad that I cannot publish the project itself to the public due to copyright reasons.
I want to give you a big THANK YOU @nomeata for creating the tttool and working on reverse engineering of it!

**Comment by SciLor** [comment]
1. The difference is, that I just link the png files into my PSD (Photoshop) document. So I have my Image project as PSD, but if I make a change to the png on the file system, the object in the PSD file is automatically updated. So this way I can easily play around and even replace the oid-id without any drawback

2. Yes, but I need to replace it in the PSD by hand, because the pngs are linked and they are kept in size. So if the pixel size changes, they are scaled

3. This would be a workaround and a better option to a legacy mode in my opinion.

**Comment by nomeata** [comment]
I detest legacy mode. They make code maintenance complicated, and they put a burden on all future users. If we have `--dpi` and `--legaci-dpi`, then I expect that many of our user will simply always try both, which makes their live miserable.

**Comment by SciLor** [comment]
Yes, thats also my opinion. Fixed pixel size will help people needing the "legacy" sizes without confusing others
