### ISSUE TITLE
SVG pattern id= attribute fails to parse in Inkscape 0.92.3

### ISSUE THREAD

**Issue by PetteriAimonen** [entropia/tip-toi-reveng#187]
I get much better print quality with vector graphics, but it seems that the .svg files generated by tttool are incompatible with Inkscape.

tttool generates:

<pre>
&lt;pattern width="48" height="48" id="10000 (product 955 code 10000)" ....
&lt;rect width="48" height="48" fill="url(#10000 (product 955 code 10000))" /&gt;
</pre>

When trying to open this, Inkscape says `** (inkscape:21104): WARNING **: URI failed to parse: #10000 (product 955 code 10000`.

If I manually modify the .svg and change the id to just `10000`, it works.

I'm not quite sure whether this is a bug in tttool or in Inkscape. It seems that the [XML standard](https://www.w3.org/TR/xml-id/#processing) requires id attribute to be a `Name`, which does not allow space characters nor parentheses.

Would it be ok to change the id to be just the OID number (e.g. 10000)? This would also make it easier to script generation of SVG files by custom tools.

**Comment by nomeata** [comment]
Yeah, agreed that that name is a bit odd. I think the advantage of this id is that you have more descriptive pattern names after you open the file in inkscape. Or something…
