### ISSUE TITLE
File Size of GME Mein Wörter Bilderbuch

### ISSUE THREAD

**Issue by salgri** [entropia/tip-toi-reveng#189]
Hello

I want to delete the game on the Ravensburger book  Mein Wörter Bilderbuch
I have make with tttool the yaml and the media files with Export and media

If I make the assemble back to gme the file is only 17452 kb. That is smoler than the original

for first: 
After when I activte the product. It will not make any Sound. It make a silence activation.

for second
If I click on the game (green button) the Music will start. The red button stop has no influence

What I have do:
tttool Export "Mein Woerter-Bilderbuch Unser Zuhause.gme"
tttool media "Mein Woerter-Bilderbuch Unser Zuhause.gme"

tttool assemble "Mein Woerter-Bilderbuch Unser Zuhause.yaml"

**Comment by nomeata** [comment]
Willkommen! Deutsch ist auch erlaubt.

Dass Spiele nachher nicht mehr tun ist bekannt, das können wir einfach noch nicht.

Das mit dem fehlenden Aktivierungston ist komisch.  Hat das schon jemand anderes erlebt?

**Comment by salgri** [comment]
Sali

Was ich noch nicht gefunden habe ist eine Liste was aktuell noch nicht läuft? Gibt es sowas? Wäre interessant.

Danke für den Hinweis

**Comment by nomeata** [comment]
Ne, das ist leider nur im kollektiven Gedächtnis der Mailingliste. Ein paar Hinweise sind in https://github.com/entropia/tip-toi-reveng/blob/master/GME-Format.md verstreut. Und irgendwann einmal sollte wohl https://tttool.readthedocs.io/de/latest/ auch diese Frage beantworten, aber das Buch-Projekt ist ein wenig eingeschlafen.

**Comment by salgri** [comment]
Trotzdem danke für den Hinweis. In dem Fall kann ich aufhören es zu versuchen
