### ISSUE TITLE
Build fails on arch linux: cabal: Could not resolve dependencies

### ISSUE THREAD

**Issue by smu** [entropia/tip-toi-reveng#191]
Installation fails under arch linux.

```
$cabal install --bindir=.
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: tttool-1.8 (user goal)
[__1] next goal: base (dependency of tttool)
[__1] rejecting: base-4.11.1.0/installed-4.1... (conflict: tttool => base>=4.5
&& <4.11)
[__1] rejecting: base-4.12.0.0, base-4.11.1.0, base-4.11.0.0, base-4.10.1.0,
base-4.10.0.0, base-4.9.1.0, base-4.9.0.0, base-4.8.2.0, base-4.8.1.0,
base-4.8.0.0, base-4.7.0.2, base-4.7.0.1, base-4.7.0.0, base-4.6.0.1,
base-4.6.0.0, base-4.5.1.0, base-4.5.0.0, base-4.4.1.0, base-4.4.0.0,
base-4.3.1.0, base-4.3.0.0, base-4.2.0.2, base-4.2.0.1, base-4.2.0.0,
base-4.1.0.0, base-4.0.0.0, base-3.0.3.2, base-3.0.3.1 (constraint from
non-upgradeable package requires installed instance)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: base, tttool
Note: when using a sandbox, all packages are required to have consistent
dependencies. Try reinstalling/unregistering the offending packages or
recreating the sandbox.
```

```
 cabal install --only-dependencies
```
leads to the same error message. 

I have no experience with haskell. any ideas how to solve the problem with `base`? thanks!

**Comment by nomeata** [comment]
You seem to have a pretty new version of GHC. Let me update `tttool` to support that…

**Comment by nomeata** [comment]
Blocked on https://github.com/alpheccar/HPDF/issues/21 unfortunately.

**Comment by raisken** [comment]
I saw two issues in HPDF. It works fine after fixing them.

1) in Graphics/PDF/Draw.hs you need to modifiy the code around "(x:xs) <- gets supplyNames" to something like this:

supplyName = do
    x1 <- gets supplyNames
    case x1 of
        (x:xs) -> do
          modifyStrict $ \s -> s {supplyNames = xs}
          return x
        [] -> error "Nothing to draw"

2) The other issue was in Graphics/PDF/Typesetting/Breaking.hs

change foldWithKey to foldrWithKey

Could you then update tttool? I'm running ghc 8.6.3. Thanks much.

**Comment by nomeata** [comment]
Thanks for the HPDF patches. I need to do something about this, but I am not sure how best to proceed in terms of packaging etc.. Probably include a patched copy of HPDF as a `git subtree` in the repository…
