### ISSUE TITLE
tttool should learn about 0xc8 and 0xcc

### ISSUE THREAD

**Issue by uli42** [entropia/tip-toi-reveng#193]
> There are quite a few holes in at least Die verrueckte Weltreise.gme(meaning parts of the file that are not understood by tttool):
>
> Unknown file segments: 15 (148652 bytes total)
>    Offset: 000000AC to 00000200 (340 bytes)

We know that there are pointers at 0xc8 and 0xcc.

....
>    Offset: 02DB9E13 to 02DC0C47 (28212 bytes)
>    Offset: 02DC0C4B to 02DDCA27 (114140 bytes)

The last two are mostly addtional gametables as referenced at 0xc8 and 0xcc. Looks like tttool does not know about them. We do not know why we have several gametables but as the structure is known I'd say at least `tttool explain` and `tttool holes` should respect them!

**Comment by nomeata** [comment]
> We know that there are pointers at 0xc8 and 0xcc.

Do we? Would you mind extending https://github.com/entropia/tip-toi-reveng/blob/master/GME-Format.md with what you know?

**Comment by nomeata** [comment]
Hmm, if I try to treat the pointer at `0xC8` like the one at `0x10`, it does not parse…

**Comment by nomeata** [comment]
Ah, you mean table of binaries. That seems to work…

**Comment by uli42** [comment]
On Thu, Nov 29, 2018 at 8:56 PM Joachim Breitner
<notifications@github.com> wrote:
>
> Ah, you mean table of binaries. That seems to work…

You are right, that is not documented in the txt file, but it is
documented here:
https://github.com/entropia/tip-toi-reveng/wiki/GME-Header.

Uli
