### ISSUE TITLE
Firmware links seem to have changed?

### ISSUE THREAD

**Issue by daef** [entropia/tip-toi-reveng#197]
The german firmwaredownloadpage offers me the '3203L' version for 2nd gen pens (with player)...:

https://www.ravensburger.de/entdecken/ravensburger-marken/tiptoi/Aktualisierung-der-Firmware/index.html

links to

http://static.tiptoi.com/db/firmware/Update3203L.upd

maybe https://github.com/entropia/tip-toi-reveng/wiki/Firmware should be updated?

**Comment by nomeata** [comment]
It's a wiki - feel free to update it as you see fit!

**Comment by uli42** [comment]
AFAIR this is only valid for the new pens, the old ones have their few at
the old location.

Uli

Am So., 23. Dez. 2018, 11:19 hat Joachim Breitner <notifications@github.com>
geschrieben:

**Comment by exmackina** [comment]
The wiki page has moved to https://github.com/entropia/tip-toi-reveng/wiki/PEN-Firmware
