### ISSUE TITLE
suggestion for installation instructions

### ISSUE THREAD

**Issue by mmccoo** [entropia/tip-toi-reveng#201]
I'm not a Haskell guy so this was my first install of stack. I keep my home dir on a smaller partition but cabal/stack want to install a bunch of stuff there in the ~/.stack dir. I'm on arch linux and build fails due to a full disk/partition.

for me the solution was this:
export STACK_ROOT=<path to where I want my tiptoi stuff>
I also did
stack init
but I can't say for such whether it's required.

In the end, the new stack directory uses 5.4GB.

**Comment by nomeata** [comment]
Official build instructions now use nix, which should avoid this problem, and we provide binaries.
