### ISSUE TITLE
[Feature Req] Option to change language field of gme file

### ISSUE THREAD

**Issue by Mahelita** [entropia/tip-toi-reveng#203]
Changing the language field of gme files seems like a quite common desire of tiptoi users.
This can be done using a hex editor (when one knows what a hex editor is).
But doing this manually for many files is indeed bothersome.
Having a command like
`tttool change-language TARGET_LANGUAGE gme_file`
would make it much easier.
Could someone please consider implementing it?
Thanks!

**Comment by nomeata** [comment]
Yes, this is a good idea, and I might just do it next time I find some time to hack on `tttool`.

**Comment by uli42** [comment]
I think it should be implemented in a way that keeps the games in the gme file because there's no real need to dissemble/assemble the whole file for this purpose.

**Comment by nomeata** [comment]
> I think it should be implemented in a way that keeps the games in the gme file because there's no real need to dissemble/assemble the whole file for this purpose.

Absolutely, that’s what I had in mind

**Comment by maehw** [comment]
Support has been added in  `ttbox` to change the language:

https://github.com/cleracruza/ttbox#gmeyaml-tooling

Accoridng to @nomeata support might also be added in `tttool`.

**Comment by nomeata** [comment]
Just implemented this in f2179fbd4bc504da83d6703636e7f5e7b3623f23. Maybe someone wants to check this?

**Comment by gil04** [comment]
Hi, I just tested it to get a german book on an italian tiptoi:

./tttool set-language ITALIAN ../Pocket\ Wissen\ -\ Dinosaurier.gme 
New language "ITALIAN" is too long, header has only space for 6 bytes.

Any idea how to get this working?

**Comment by gil04** [comment]
Oh - ok - I just tried:
./tttool set-language ITALIA ../Pocket\ Wissen\ -\ Dinosaurier.gme
And this is working (in my case)
