### ISSUE TITLE
Installation fails in Kubuntu 18.04

### ISSUE THREAD

**Issue by EureDudeheit** [entropia/tip-toi-reveng#213]
Hello, i tried to install tttool via

`cabal install --only-dependencies`

but i receive the following error:

`felix@tardis:~/tttool$ cabal install
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: tttool-1.9 (user goal)
next goal: base (dependency of tttool-1.9)
rejecting: base-4.9.1.0/installed-4.9... (conflict: tttool => base>=4.11 &&
<4.13)
rejecting: base-4.10.0.0, base-4.9.1.0, base-4.9.0.0, base-4.8.2.0,
base-4.8.1.0, base-4.8.0.0, base-4.7.0.2, base-4.7.0.1, base-4.7.0.0,
base-4.6.0.1, base-4.6.0.0, base-4.5.1.0, base-4.5.0.0, base-4.4.1.0,
base-4.4.0.0, base-4.3.1.0, base-4.3.0.0, base-4.2.0.2, base-4.2.0.1,
base-4.2.0.0, base-4.1.0.0, base-4.0.0.0, base-3.0.3.2, base-3.0.3.1
(constraint from non-upgradeable package requires installed instance)
Dependency tree exhaustively searched.`

(Kubuntu 18.04 LTS 4.15.0-74-generic)

**Comment by nomeata** [comment]
The [supported installation methods](https://tttool.readthedocs.io/de/latest/installation.html) are: 
* install the binary from https://github.com/entropia/tip-toi-reveng/releases (includes a statically built version of `tttool` for linux), or
* to build from source with `nix`, as described in https://github.com/entropia/tip-toi-reveng/blob/master/Building.md.

There are other ways of building, such as with `cabal` directoy, but these are not supported in the sense that they should be used by those who know how to deal with issues like the one you are posting.

I recommend that you use the binary release.

**Comment by nomeata** [comment]
I just added a `cabal.project.freeze` file that should simplify building from source. Building from `nix` is still recommended.
