### ISSUE TITLE
[Question] Alternative to the TipToi pen?

### ISSUE THREAD

**Issue by Int32Overflow** [entropia/tip-toi-reveng#214]
I know that this question does not really belong here. But unfortunately I didn't know any other way.

Is there a better alternative to the TipToi pen, which is officially programmable?
I would like to use such pens at school to better support children with learning disabilities.

**Comment by nomeata** [comment]
Maybe the Ting pen? (Also see https://www.ting-el-tangel.de/)

**Comment by maehw** [comment]
> I know that this question does not really belong here. But unfortunately I didn't know any other way.
> 
> Is there a better alternative to the TipToi pen, which is officially programmable?
> I would like to use such pens at school to better support children with learning disabilities.

Hi. Why is it a requirement that the pen is "officially programmable"? Where are you lacking support or capabilities with `tttool`?

**Comment by Int32Overflow** [comment]
> 
> Hi. Why is it a requirement that the pen is "officially programmable"? Where are you lacking support or capabilities with `tttool`?

What about the law. Is it legal? Like I said, I want to use it in a school.

**Comment by nomeata** [comment]
We don’t know if it is legal. We have been playing around with it for 6 years without trouble. But this is of course not legal advise.

You can talk to Ravensburger directly, they are usual repsonsive and open for suggestions.

**Comment by nomeata** [comment]
Closing this to clear it from the list of open issues.
