### ISSUE TITLE
[Question] Does it work to print OIDs on transparent self adhesive film?

### ISSUE THREAD

**Issue by exmackina** [entropia/tip-toi-reveng#217]
Hello, I was wondering how it was possible to convert a classic book into a book compatible with tiptoi (without altering the book too much and therefore, without tearing the sheets of the book to put them in a printer ... assuming that it could work depending on the brightness of the drawing ...).
So I thought it would be great if we could make OID stickers, that is, print OIDs on a transparent self adhesive film, cut them to the desired shape and stick them on a book.
I haven't been able to try it yet, but if someone did, does it work?

I was thinking about this kind of film: https://www.amazon.de/Transparente-Adh%C3%A9sive-Autocollant-Feuilles-PPD-39-20/dp/B004BF8X2W (https://www.youtube.com/watch?v=m5AxR_S1DyY)

**Comment by KOTRET** [comment]
good question, I'm interested in this too.
I could imagine that you need to use high gloss foils to avoid covering the book with stickers with milky glass optics. On the other hand this can be difficult to print on.
I'm curious about possible reflections of the foil - does that affect the pen reading the patterns?

**Comment by nomeata** [comment]
Maybe you’ll get more responses on the mailing list at https://lists.nomeata.de/mailman/listinfo/tiptoi. Closing this to clear it from the list of open issues.
