### ISSUE TITLE
download of GME files fails

### ISSUE THREAD

**Issue by muelli** [entropia/tip-toi-reveng#219]
e.g.

```
$ ./scripts/update.sh
...
~/vcs/tip-toi-reveng/003/32901 - tiptoi® Entdecke den Flughafen/20141117 ~/vcs/tip-toi-reveng/003/32901 - tiptoi® Entdecke den Flughafen ~/vcs/tip-toi-reveng
--2020-06-02 19:46:21--  http://static.tiptoi.com/db/applications/WWW%20Flughafen.gme
Resolving static.tiptoi.com (static.tiptoi.com)... 46.16.77.133
Connecting to static.tiptoi.com (static.tiptoi.com)|46.16.77.133|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-06-02 19:46:21 ERROR 404: Not Found.

~/vcs/tip-toi-reveng/003/32901 - tiptoi® Entdecke den Flughafen ~/vcs/tip-toi-reveng
~/vcs/tip-toi-reveng

```

I see that the XML file contains URLs such as
http://static.tiptoi.com/db/applications/Wimmelbuch.gme
which throw a 404.

Is it a problem on their end?

**Comment by muelli** [comment]
from browsing their shop, e.g. https://www.ravensburger.de/produkte/kinderbuecher/tiptoi/tiptoi-die-welt-der-musik-32902/index.html#tiptoiDownloadContainer
I have noticed the following URL:
https://cdn.ravensburger.de/db/applications/WWW%20Musik.gme

Notice how the hostname is different.

I have patched the update script slightly to make it work:

```
diff --git a/scripts/update.sh b/scripts/update.sh
index e80531b..71c8e78 100755
--- a/scripts/update.sh
+++ b/scripts/update.sh
@@ -7,6 +7,6 @@ LANGUAGES="de_de fr_fr nl_nl it_it ru_ru"
 
 for lang in $LANGUAGES ; do 
    wget -m -nd https://ssl-static.ravensburger.de/db/tiptoi_$lang.xml
-   cat tiptoi_$lang.xml | `dirname $0`/download.pl | bash
+   cat tiptoi_$lang.xml | sed 's,http://static.tiptoi.com,https://cdn.ravensburger.de,g' | `dirname $0`/download.pl | bash
    #cat tiptoi_$lang.xml | ./download.pl
 done

```

**Comment by nomeata** [comment]
> Is it a problem on their end?

Maybe. @NimVek wrote that script – care to take a look?

**Comment by Andrwe** [comment]
It seems like the xml-file was moved to a new location too:
```
$ curl https://ssl-static.ravensburger.de/db/tiptoi_de_de.xml
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
</body></html>
```

**Comment by gizmo21** [comment]
on top now even not all books are shown on ravensburger.de to do the manual download: e.g. Entdecke den Flughafen is missing but if ylu know the name of the gme you can download it:
https://cdn.ravensburger.de/db/applications/WWW%20Flughafen.gme

Perhaps someone can dump one of the latest known tiptoi_de_de.xml on a Pastebin site an link it here, so one can find the right filenames and dl-locations.

**Comment by nomeata** [comment]
Surely the official program has a way of getting a list of products. Maybe someone (who uses that program) can sniff the connection and see where the xml file is now, or how else this is fetched?

**Comment by nomeata** [comment]
Maybe someone running Windows wants to use the official tiptoi Manager and sniff its network connection to see what URLs it fetches?

**Comment by m4r71n** [comment]
I've installed tiptoi Manager 4.2.1 and they've switch from xml to json:

https://ttapiv2.ravensburger.com/api/v2/config/de_DE/WIN
https://ttapiv2.ravensburger.com/api/v2/catalog/de_DE

**Comment by nomeata** [comment]
Ah, should have closed this, the script in https://github.com/entropia/tip-toi-reveng/blob/master/testsuite/list-gmes.sh does what we need.
