### ISSUE TITLE
Problems with assembling large .gme-files?

### ISSUE THREAD

**Issue by eazteregg** [entropia/tip-toi-reveng#221]
Hello everyone!
We are working on a project for a university course involving the TipToi-pen. Our goal is to create a small booklet that teaches users the basics of the Korean alphabet, and some simple pronunciation rules. The project spans some 150 OID-codes. It compiles fine and everything, works as it's supposed to in the play-mode, but upon assemblage, seemingly at random, certain audio files do not play, or registers are not set in the desired way. This results in a project that almost works, but in every exercise there are some items that do not work as intended, decreasing the overall quality of the product, despite the fact that they follow the exact same logic as the other items in that exercise. For example, consider the following lines. Here, the idea is that learners activate the exercise by touching an OID-code, listen to a Korean syllable, and then try to identify the corresponding Korean characters, again by touching an OID-code. 

> 7_instruction_exercise_2:
    - $start==0? P(0_touch_start)
    - $start==1? $exercise_7:=0 $exercise_8:=0 $exercise_9:=0 $exercise_10:=0 P(0_exercise_2)
>7_moo:
    - $exercise_7:=1 $exercise_8:=0 $exercise_9:=0 $exercise_10:=0 $woo:=0 $boo:=0 $joo:=0 $moo:=1 $soo:=0 P(7_1_4_moo)
> 7_moo_answer:
    - $exercise_7==1? $moo==1? P(0_correct) P(7_1_4_moo)
    - $exercise_7==1? $moo==0? P(0_wrong)`
    - $exercise_7==0?
  7_boo:
    - $exercise_7:=1 $exercise_8:=0 $exercise_9:=0 $exercise_10:=0 $woo:=0 $boo:=1 $joo:=0 $moo:=0 $soo:=0 P(7_1_2_boo)
  7_boo_answer:
    - $exercise_7==1? $boo==1? P(0_correct) P(7_1_2_boo)
    - $exercise_7==1? $boo==0? P(0_wrong)
    - $exercise_7==0?
  7_soo:
    - $exercise_7:=1 $exercise_8:=0 $exercise_9:=0 $exercise_10:=0 $woo:=0 $boo:=0 $joo:=0 $moo:=0 $soo:=1 P(7_1_5_soo)
  7_soo_answer:
    - $exercise_7==1? $soo==1? P(0_correct) P(7_1_5_soo)
    - $exercise_7==1? $soo==0? P(0_wrong)
    - $exercise_7==0?
  7_woo:
    - $exercise_7:=1 $exercise_8:=0 $exercise_9:=0 $exercise_10:=0 $woo:=1 $boo:=0 $joo:=0 $moo:=0 $soo:=0 P(7_1_1_woo)
  7_woo_answer:
    - $exercise_7==1? $woo==1? P(0_correct) P(7_1_1_woo)
    - $exercise_7==1? $woo==0? P(0_wrong)
    - $exercise_7==0? # if exercise is not selected, nothing should happen right? if yes, add this to all other answers
  7_joo:
    - $exercise_7:=1 $exercise_8:=0 $exercise_9:=0 $exercise_10:=0 $woo:=0 $boo:=0 $joo:=1 $moo:=0 $soo:=0 P(7_1_3_joo)
  7_joo_answer:
    - $exercise_7==1? $joo==1? P(0_correct) P(7_1_3_joo)
    - $exercise_7==1? $joo==0? P(0_wrong)
    - $exercise_7==0?

Interestingly enough, most of these items perform as desired, except that the sound file at the start of each item activation is omitted. It is issued via the final P()-command at the end of every item-initial OID-code (the first of every pair e.g. 7_joo).  Other than that the items perform as desired, except for the item activated with 7_soo and solved with 7_soo_answer. In all cases it simply plays the 0_wrong sound file. The logic, and everything is exactly the same as with all other items, so why does it not work in that particular case? Could it be that it is caused by having more than 8-commands in one line, but then why does it work in the case of all other items? In addition to this page, there are about 6 more, so could it be that the project is simply too cumbersome for the pen to handle? Should we split it up into smaller projects - one per page maybe? We are despairing over this issue, so any feedback is well appreciated!

**Comment by nomeata** [comment]
You should not put more than 8 commands in a single script line. I thought `tttool` warns if you do. Maybe it doesn't?

It’s unclear when exactly such long commands don't work on the pen, but so far splitting long lines (just jump to another script) worked fine?

**Comment by eazteregg** [comment]
Thank you so much for the quick reply!
We have run into a peculiar situation here. First we fixed the 8-commands-in-one-line problem on the page that the previously mentioned exercise was on, and then the sounds were playing as desired. However, some other oid-codes were still giving us trouble, so we looked through the code again and realized that there is another exercise with more than 8 commands per line, so we fixed those as well. Unfortunately, after doing so, the performance of the project as a whole declined immensely. Previously functional oid-codes and exercises simply stopped working for no discernible reason. For now, we are working with the half-fixed version as it provides the most satisfying experience for now. The problems that keep coming up, here is the consistent failure to play one specific sound file 100% of the time, and then some harsh inconsistencies with playing some of the correct responses to the items in the exercise shown above. In the first case, the following are the lines of code causing the trouble 100% of the time:
>7_instruction_exercise_2:
    - $start==0? P(0_touch_start)
    - $start==1? $exercise_7:=0 $exercise_8:=0 $exercise_9:=0 $exercise_10:=0  P(0_exercise_2)

When it comes to the inconsistent oid-codes, initially, the pen refuses to activate the desired oid-code's logic until, suddenly, some undefinable attempts later, it activates it without fail. The logic behind all of the items is exactly the same, so it seems unlikely that it can be the source of the problem. On the other hand, when the project is not activated, the pen recognizes the patterns perfectly, so here too, the locus of the problem appears to be elsewhere.
Here you can see one of the inconsistent oid-code's logic. As you can see it is identical in form to those from my earlier comment, save the Jump-command at the end for obvious reasons:
>8_doon:
    - $exercise_9:=1 $doon:=1 $dyoung:=0 $deon:=0 $dyong:=0 P(8_1_4_doon) J(disabletwo)
  8_doon_answer:
    - $exercise_9==1? $doon==1? P(0_correct) P(8_1_4_doon)
    - $exercise_9==1? $doon==0? P(0_wrong)
    - $exercise_9==0?

I know that it is a long stretch to ask for solutions to such fickle and hard to pin down problems, but your first response was already a great help and has helped improve the overall feel of our project by a lot. Thank you!!

**Comment by nomeata** [comment]
Is this a new pen (can also play audiobooks)? There is something with the interplay of P and J that is odd about the new pen, and I don't understand the full details. You can ask on the mailing list for more rumors.

If it works with the J, did you try to jump to an auxiliary empty script at the end of `7_instruction_exercise_2`? Maybe that helps

**Comment by eazteregg** [comment]
Thanks again for your timely reply!
Yes, indeed, it is a new pen (year 2018). However, I do not believe that the inconsistencies arose due to the intermingling of J and P commands. We actually experienced similar behavior before, but I did not mention it in my first message because I thought it was already long enough. It would seem as though the inconsistencies themselves arise in scripts which do not feature J and P commands together, or do you believe that the inconsistencies may arise in any part of the code?
By the way, we tried the idea with the empty script, but could not really figure out how to write a script without any commands in it, so instead we went with:
> empty:
    - $blabla==0? $blabla:=1
    - $blabla==1? $blabla:=0

> 7_instruction_exercise_2:
    - $start==0? P(0_touch_start)
    - $start==1? $exercise_7:=0 $exercise_8:=0 $exercise_9:=0 $exercise_10:=0  P(0_exercise_2) J(empty)

Unfortunately, the result remains the same, and the sound file for `7_instruction_exercise_2` refuses to play.

**Comment by nomeata** [comment]
Sorry, out of ideas then. Maybe ask on https://lists.nomeata.de/mailman/listinfo/tiptoi if anyone has had similar problems. And of course let us know if you learn more about when exactly what problems occur.

**Comment by uli42** [comment]
On Sun, Jul 12, 2020 at 8:27 PM eazteregg <notifications@github.com> wrote:
>
> Thanks again for your timely reply!
> Yes, indeed, it is a new pen (year 2018). However, I do not believe that the inconsistencies arose due to the intermingling of J and P commands. We actually experienced similar behavior before, but I did not mention it in my first message because I thought it was already long enough. It would seem as though the inconsistencies themselves arise in scripts which do not feature J and P commands together, or do you believe that the inconsistencies may arise in any part of the code?
> By the way, we tried the idea with the empty script, but could not really figure out how to write a script without any commands in it, so instead we went with:
>
> empty:
> - $blabla==0? $blabla:=1
> - $blabla==1? $blabla:=0


I think you can also define lines without any condition, but I am
unsure about the syntax. Maybe start just _after_ the ?. Then setting
a dummy variable to a dummy value should be enough.

Uli

**Comment by nomeata** [comment]
```
empty:
 -  $blabla:=0
```
or even 
```
empty: $blabla:=0
```
should work.

**Comment by eazteregg** [comment]
There has been some development. We were able to fix the inconsistencies by using `tttool assemble` on a windows machine. So far we'd been using it on mac and linux exclusively. Now, the version where all lines with more than 8 commands were fixed works nicely, except for that pesky sound file for `7_instruction_exercise_2`. I guess we can live with that, though. Just thought, I'd let you guys know.

**Comment by nomeata** [comment]
> We were able to fix the inconsistencies by using tttool assemble on a windows machine. So far we'd been using it on mac and linux exclusively

I would be _very_ surprised if you get different `.gme` files on different systems! Are you sure that you really used the same input on windows and linux?

If so, I’d love to see the full `.yaml` file, and the two different GME files as produced on Windows and Linux (by mail if you don't want to share publicly).

**Comment by nomeata** [comment]
> > We were able to fix the inconsistencies by using tttool assemble on a windows machine. So far we'd been using it on mac and linux exclusively
> 
> I would be _very_ surprised if you get different `.gme` files on different systems! Are you sure that you really used the same input on windows and linux?

Just for the record if someone else reads this: it turned out that the files included different audio files (ogg vs. wav), so not a platform dependency after all (phew).

**Comment by nomeata** [comment]
So I guess this can be closed? Please reopen if I missed something.
