### ISSUE TITLE
How to implement a select language functionality

### ISSUE THREAD

**Issue by SonjaChevre** [entropia/tip-toi-reveng#222]
Hi,

we have books in both German and French - thanks to your project, we are using only 1 pen (configured in French) by overriding the language setting in the GME files to German. 

It would be nice for my child to be able to use the same book (no matter whether it is written in French or German) with both languages, provided both GME files are available. Having like a "magic button" to switch the button.

Any hints/ideas on how I could implement this? 

thanks,
Sonja

**Comment by uli42** [comment]
Hello Sonja,

you need to add another (printed) activation field to the book and
change the product id of one of the GME files to match the code of
that additional button. You cannot change the language on the fly
while being within a game.

Uli

**Comment by SonjaChevre** [comment]
Makes sense - thanks for the hint!

Sonja
