### ISSUE TITLE
Does the tttool work with 3rd generation of tiptoi ?

### ISSUE THREAD

**Issue by m0dch3n** [entropia/tip-toi-reveng#223]
Hi, I recently bought a tiptoi pen and noticed that it's different, as those in the video... After googling, I found out, the main difference is, that it also has a [recording function](https://www.ravensburger.de/entdecken/ravensburger-marken/tiptoi/tiptoi-stift/index.html)

Anyway, I tried tttool v1.9 to create my own games... However the stick is not playing nor recognizing my newly created `Sticker.gme`. Also under the official PenToi Manager, the Product is no longer listed... When I put back the original file, on my stick, everything works fine again.

I did not touch the .ogg files, just tried, to export, media, assemble...

```bash
[m0dch3n@mbp test ]$ ../tttool export Stickerbogen_Starterset.gme
[m0dch3n@mbp test ]$ ../tttool media Stickerbogen_Starterset.gme
Audio Table entries: 47
Dumped sample 0 as media/Stickerbogen_Starterset_0.ogg
Dumped sample 1 as media/Stickerbogen_Starterset_1.ogg
Dumped sample 2 as media/Stickerbogen_Starterset_2.ogg
Dumped sample 3 as media/Stickerbogen_Starterset_3.ogg
Dumped sample 4 as media/Stickerbogen_Starterset_4.ogg
Dumped sample 5 as media/Stickerbogen_Starterset_5.ogg
Dumped sample 6 as media/Stickerbogen_Starterset_6.ogg
Dumped sample 7 as media/Stickerbogen_Starterset_7.ogg
Dumped sample 8 as media/Stickerbogen_Starterset_8.ogg
Dumped sample 9 as media/Stickerbogen_Starterset_9.ogg
Dumped sample 10 as media/Stickerbogen_Starterset_10.ogg
Dumped sample 11 as media/Stickerbogen_Starterset_11.ogg
Dumped sample 12 as media/Stickerbogen_Starterset_12.ogg
Dumped sample 13 as media/Stickerbogen_Starterset_13.ogg
Dumped sample 14 as media/Stickerbogen_Starterset_14.ogg
Dumped sample 15 as media/Stickerbogen_Starterset_15.ogg
Dumped sample 16 as media/Stickerbogen_Starterset_16.ogg
Dumped sample 17 as media/Stickerbogen_Starterset_17.ogg
Dumped sample 18 as media/Stickerbogen_Starterset_18.ogg
Dumped sample 19 as media/Stickerbogen_Starterset_19.ogg
Dumped sample 20 as media/Stickerbogen_Starterset_20.ogg
Dumped sample 21 as media/Stickerbogen_Starterset_21.ogg
Dumped sample 22 as media/Stickerbogen_Starterset_22.ogg
Dumped sample 23 as media/Stickerbogen_Starterset_23.ogg
Dumped sample 24 as media/Stickerbogen_Starterset_24.ogg
Dumped sample 25 as media/Stickerbogen_Starterset_25.ogg
Dumped sample 26 as media/Stickerbogen_Starterset_26.ogg
Dumped sample 27 as media/Stickerbogen_Starterset_27.ogg
Dumped sample 28 as media/Stickerbogen_Starterset_28.ogg
Dumped sample 29 as media/Stickerbogen_Starterset_29.ogg
Dumped sample 30 as media/Stickerbogen_Starterset_30.ogg
Dumped sample 31 as media/Stickerbogen_Starterset_31.ogg
Dumped sample 32 as media/Stickerbogen_Starterset_32.ogg
Dumped sample 33 as media/Stickerbogen_Starterset_33.ogg
Dumped sample 34 as media/Stickerbogen_Starterset_34.ogg
Dumped sample 35 as media/Stickerbogen_Starterset_35.ogg
Dumped sample 36 as media/Stickerbogen_Starterset_36.ogg
Dumped sample 37 as media/Stickerbogen_Starterset_37.ogg
Dumped sample 38 as media/Stickerbogen_Starterset_38.ogg
Dumped sample 39 as media/Stickerbogen_Starterset_39.ogg
Dumped sample 40 as media/Stickerbogen_Starterset_40.ogg
Dumped sample 41 as media/Stickerbogen_Starterset_41.ogg
Dumped sample 42 as media/Stickerbogen_Starterset_42.ogg
Dumped sample 43 as media/Stickerbogen_Starterset_43.ogg
Dumped sample 44 as media/Stickerbogen_Starterset_44.ogg
Dumped sample 45 as media/Stickerbogen_Starterset_45.ogg
Dumped sample 46 as media/Stickerbogen_Starterset_46.ogg
[m0dch3n@mbp test ]$ ../tttool assemble Stickerbogen_Starterset.yaml Sticker.gme
[m0dch3n@mbp test ]$ ../tttool info Sticker.gme
Product ID: 133
Raw XOR value: 0x00000039
Magic XOR value: 0xAD
Comment: CHOMPTECH DATA FORMAT CopyRight 2009 Ver2.10.0901
Date: 20200801
Language:
Number of registers: 5
Initial registers: [1,99,0,0,0]
Initial sounds: []
Scripts for OIDs from 9950 to 9965; 0/16 are disabled.
Audio table entries: 47
Binary tables entries: 0/0/0
Single binary table entries: 0/0/0
Checksum found 0x1542A2DE, calculated 0x1542A2DE
[m0dch3n@mbp test ]$ ../tttool info Stickerbogen_Starterset.gme
Product ID: 133
Raw XOR value: 0x0000001F
Magic XOR value: 0x62
Comment: CHOMPTECH DATA FORMAT CopyRight 2009 Ver2.10.0901
Date: 20180408
Language:
Number of registers: 10
Initial registers: [1,99,0,0,0,0,0,0,0,0]
Initial sounds: []
Scripts for OIDs from 9950 to 9965; 0/16 are disabled.
Audio table entries: 47
Audio table repeated twice
Binary tables entries: 0/0/0
Single binary table entries: 1/1/1
Special OIDs: 0, 0
Checksum found 0x14B8A016, calculated 0x14B8A016
[m0dch3n@mbp test ]$ ls -al Sticker*
-rw-r--r--  1 m0dch3n  staff  2796266 Aug  1 08:09 Sticker.gme
-rw-r--r--@ 1 m0dch3n  staff  2828456 Aug  1 07:59 Stickerbogen_Starterset.gme
-rw-r--r--  1 m0dch3n  staff     2237 Aug  1 08:09 Stickerbogen_Starterset.yaml
[m0dch3n@mbp test ]$
```

So my question, is this related to the 3rd generation of my stick or to wrong assembling ?

PS: I have attached the original and the created file...
[Stickerbogen_Starterset.gme.zip](https://github.com/entropia/tip-toi-reveng/files/5009924/Stickerbogen_Starterset.gme.zip)
[Sticker.gme.zip](https://github.com/entropia/tip-toi-reveng/files/5009925/Sticker.gme.zip)

**Comment by nomeata** [comment]
Hmm, so far we have no reports that it would not work on the third generation pens (not sure how many people have tried, though).

Can you try the same steps with another GME from Ravensburger that you have the product for? Maybe something that’s unrelated to the recording function?

**Comment by m0dch3n** [comment]
It's working now on 3rd generation too, by continuing to play around...

To summarize, what my problems were :

- I bought [this](https://www.amazon.de/Ravensburger-Tiptoi-00801-Der-Stift/dp/B07B47Y6FX/) stick, without games, so I only had the `Stickerbogen` to test, and the `Anleitung` without printing new game.

- I wasn't able to get `Stickerbogen_Starterset.gme` to work. Because of different repackaging I wasn't sure, if it's the stick or the newly generated .gme file. The different size and content, made me unsure.

- Modifying `Schnellstart-Anleitung.gme` did also not work. Doing `tttool rewrite Schnellstart-Anleitung.gme Schnellstart-Anleitung2.gme` also resulted in different file... What is strange, is that even without any `.gme` file on the stick, the `Anleitung` still works... 🤔

- The tic-tac-toi example, with the need to print the oid-table was also not working, because of my printer... 🤦‍♂️

Finally I tried the laser printer, with which I was able to get my selfmade gme to work! 🤩   So now I can finally start to play around 😁

Thanks for your help and all the time and effort you already put in this project!

**Comment by nifix777** [comment]
@m0dch3n could you share youre paramters for oid-table creation and the printing? I tried a bunch of settings with my own simple game and with the ravensburger test pdf (tiptoicode_Navigationsleiste.pdf) but no success until now. Your help would be awesome 🤩

**Comment by m0dch3n** [comment]
@nifix777 Basically my source of problem was just the ink printer at home and not the gme creation...

The laser printer at work worked without any issues. I just needed to print with 1200 dpi.

So I would suggest you, to first check that your printer works, by printing and using an OID which is already on a pre installed game. Then on the next step, try to replace this OID with your own sound file and then continue and try to write your own games
