### ISSUE TITLE
tiptoi A4 blinking

### ISSUE THREAD

**Issue by petres** [entropia/tip-toi-reveng#224]
Sorry, I know thats not tip-toi-reveng specific, but as I have seen, this issue tracker has already misused as tip toi forum (where would be a better place to ask?). 

My A4 tiptoi is blinking, and doing nothing. 
Still I don't know if it's a software or a hardware problem,
is there somewhere a link to download the original state of the flash drive?

Thanks

**Comment by nomeata** [comment]
> (where would be a better place to ask?).

https://lists.nomeata.de/mailman/listinfo/tiptoi probably.

Sorry, no idea about your actual question.
