### ISSUE TITLE
Creating Kompass example doesn´t work (Ubuntu 18.04)

### ISSUE THREAD

**Issue by Golpe82** [entropia/tip-toi-reveng#240]
Hi, i am trying to test the kompass example with this manual [http://docplayer.org/186613802-Punktgenau-bauanleitung-kurzinfo-material-108-make-6-2015-achtung-wie-das-muh-in-den-stift-kommt.html](url)

My working tree it seems like this:
`:~/tttool-1.9/linux$ tree
.
├── Kompass1.yaml
├── Kompass2.yaml
└── tttool

0 directories, 3 files
`

if i  execute this:
`:~/tttool-1.9/linux$ ./tttool assemble Kompass1.yaml `
i have this output:
```Speaking "Nord".
No suitable text-to-speech-engine found.
Do you have libttspico-utils or espeak installed?
Could not find "oggenc".
Do you have vorbis-tools installed?
Speaking "Ost".
No suitable text-to-speech-engine found.
Do you have libttspico-utils or espeak installed?
Could not find "oggenc".
Do you have vorbis-tools installed?
Speaking "Süd".
No suitable text-to-speech-engine found.
Do you have libttspico-utils or espeak installed?
Could not find "oggenc".
Do you have vorbis-tools installed?
Speaking "West".
No suitable text-to-speech-engine found.
Do you have libttspico-utils or espeak installed?
Could not find "oggenc".
Do you have vorbis-tools installed?
Speaking "Willkommen zum Tiptoi-Kompass".
No suitable text-to-speech-engine found.
Do you have libttspico-utils or espeak installed?
Could not find "oggenc".
Do you have vorbis-tools installed?
Speaking "Das einfache Programm kennt noch keine Spiele.".
No suitable text-to-speech-engine found.
Do you have libttspico-utils or espeak installed?
Could not find "oggenc".
Do you have vorbis-tools installed?
tttool: tts-cache/tts-Nord-de.ogg: openBinaryFile: does not exist (No such file or directory)
```
any idea?

**Comment by Golpe82** [comment]
Ok, i just installed
`sudo apt-get install libttspico-utils`
and
`sudo apt-get install vorbis-tools`
Should it may be written in the documentation for linux users?

**Comment by nomeata** [comment]
Yes, that might be helpful. Feel free to contribute a sentence in the docs where it would have helped you the most.

**Comment by Golpe82** [comment]
Steps implemented in the [README.md](https://github.com/entropia/tip-toi-reveng/blob/master/README.md#installation).
(Waiting for merge)
