### ISSUE TITLE
Changing product-id does not work

### ISSUE THREAD

**Issue by stephanweiss** [entropia/tip-toi-reveng#241]
I want to activate a German .gme file with the Italian product-id/power button (I can explain why in detail if you are interested...). Here is what works:
A) Activate a German .gme file with another German product-id/power button: 1) download "WWW Jahreszeiten.gme" and extract the .yaml file. 2) Change the product-id in that .yaml file from 77 to 35 (i.e. the product-id of "Puzzle Im Zoo.gme" 3) assemble and upload 4) "WWW Jahreszeiten" now only activates with the power button of the puzzle
Here is what does not work:
B) Activate a German .gme file with an Italian product-id/power button: 1) download "WWW Jahreszeiten.gme" and extract the .yaml file. 2) Change the product-id in that .yaml file from 77 to 53 (i.e. the product-id of "Animali Africa.gme" 3) assemble and upload 4) I get the message that the .gme file "WWW Jahreszeiten.gme" is missing when I hit the "Animali Africa" power button

This is strange in the sense that, from a program point of view, in the very same German .gme file, I only change the new product-id to 53 instead of 35. Am I missing something?

Thank you in advance for your valuable inputs

**Comment by nomeata** [comment]
Odd indeed. Any chance that there is another file with oid code 53 still on the tiptoi pen?

**Comment by uli42** [comment]
Wait, the pen tells your "WWW Jahreszeit.gme" i missing? How? Or does
it rather complain that it cannot find a matching gme file?

We had something similar some time ago where the filesystem of the pen
was not ok, IIRC. Try to connect the pen to the Tip Toi Manager and
add another file, does not matter, for which product. You just trigger
the pen to rescan the filesystem this way. See e.g.
https://lists.nomeata.de/archive/tiptoi/2016/001244.html

Does that help?

**Comment by stephanweiss** [comment]
Hi,

Thank you very much for the fast reply. It was an odd issue: there is an Italian version of "Tiere Afrikas" (start code 25) where the correct one says "Animalli Dell Africa" (with the start code 25) and for some reason I found (and downloaded) "Animali Africa" (with the start code 53). After examining the .yaml file of the latter one it seemed to be generally a bit odd. The former one had, of course, the same product-id as its German version, and everything worked. 
So essentially, I was expecting code 53 due to the wrong .gme file where I should have used code 25 instead.
Now everything works like mentioned in the countless tutorials/guides -- thanks a bunch to the developers. This is truly fantastic!
