### ISSUE TITLE
Replay and Stop OIDs not printed with oid-table or oid-codes

### ISSUE THREAD

**Issue by lubbifo** [entropia/tip-toi-reveng#250]
Reading https://tttool.readthedocs.io/de/latest/erste-schritte.html#der-erste-ton suggests, that the Replay and Stop OID are generated automatically using tttool [oid-table|oid-codes]. However, this doesnt work for me. Adding an OID Code for Replay/Stop as outlined in https://tttool.readthedocs.io/de/latest/yaml-referenz.html#replay doesnt work either, since it mixes names and numerics. 

Using tttool-1.9 on Linux Mint 20 Ulyana. The binary works flawlessly otherwise.

**Comment by nomeata** [comment]
> However, this doesnt work for me

What exactly doesn't work? The codes are not included in the table, or the codes are included, but do not work?

Ah, 1.9 does not have that feature yet. You can use the latest unreleased version. Go to https://github.com/entropia/tip-toi-reveng/actions?query=branch%3Amaster+workflow%3A%22Build+and+package%22, then click on the latest action, then scroll down to “Artifacts”

**Comment by lubbifo** [comment]
Sorry for being not precise. Yes, the OID codes are missing in the pdf file and no such png files are generated. 

I just installed build 6790804/master and it worked. Thanks.

**Comment by lubbifo** [comment]
Sorry guys, the codes now printed, but dont work. I have no 'replay' or 'stop' statement in my yaml, so the codes are now printed by default. If I start the playback of intro.ogg using

```
product-id: 900
comment: example
welcome: Start
scripts:
  Test_Intro: P(Intro) 

```

the stop OID does not stop the playback. Replay does also not repeat the playback. 

> 
> $../tttool --dpi 600 --code-dim 40x80 oid-codes something.yaml 
> Writing oid-900-START.png.. (Code 900, raw code 13911)
> Writing oid-900-REPLAY.png.. (Code 12159, raw code 7888)
> Writing oid-900-STOP.png.. (Code 12158, raw code 7887)
> ..... many others.... 
> Writing oid-900-Test_Intro.png.. (Code 3951, raw code 54021)
> 

What am I doing wrong?

**Comment by nomeata** [comment]
No idea :-)

This is a rather new feature, and probably needs more testing and debugging.

Did you replace the `.gme` file on the stick with one created with the `master`-version of `tttool`?

**Comment by lubbifo** [comment]
Ouch ....  sorry ... works...! Thanks.
