### ISSUE TITLE
What are existing project ids?

### ISSUE THREAD

**Issue by snwang** [entropia/tip-toi-reveng#255]
Thanks for this great project! I'm excited to work on a music playing books for my 2 years old! But could someone help me picking safe `project_id`s in yaml files so that there will be no conflicts with official tiptoi `gme`s?

**Comment by uli42** [comment]
THe tiptoi book
(https://tttool.readthedocs.io/de/latest/yaml-referenz.html#product-id)
mentions this:

"Es sollte zu jeder Produkt-ID nur eine GME-Datei auf den Stift
geladen werden. Ravensburger zählt seine Produkte fortlaufend ab 1
hoch und Sprachen werden mit 999 abwärts nummeriert. Wir raten dir für
dein eigenes Projekt daher eine Zahl zwischen 900 und 950 zu wählen."

In English: the recommendation is to choose a number between 900 and 950.

Uli

**Comment by nomeata** [comment]
Thanks for the answer, I hope this solves it.
