### ISSUE TITLE
Help with mTiny pen

### ISSUE THREAD

**Issue by thopd88** [entropia/tip-toi-reveng#259]
It seems mTiny robot pen is using OID, however it may use another version since it's not look like OID which is using for TipToi (1.5).
I couldn't find any references about OID except this git, could you please help? Thanks a lot

**Comment by thopd88** [comment]
@nomeata can you give me some suggestions on this? I dont know if mTiny using OID 1,1.5.2 or 3.
I tried to reach OID Producer author to get his free version but no response.

**Comment by nomeata** [comment]
I don’t know much about OIDs besides Tiptoi, sorry.

**Comment by nomeata** [comment]
Sorry, I have never used OIDProducer
