### ISSUE TITLE
https://ssl-static.ravensburger.de/db/tiptoi_$lang.xml is down - can't download GME

### ISSUE THREAD

**Issue by ignazioc** [entropia/tip-toi-reveng#260]
I found today this repo, while trying to hack around the tiptoi.  I tried to dowload all the GME files using the `script/update.sh` but the website is probably changed. Any idea of the new URL?

**Comment by jmayer** [comment]
My Mac doesn't have wget, only curl, but it looks like a genuine problem:
`curl https://ssl-static.ravensburger.de/db/tiptoi_de_de.xml
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://cdn.ravensburger.de/db/tiptoi_de_de.xml">here</a>.</p>
</body></html>

curl **-L** https://ssl-static.ravensburger.de/db/tiptoi_de_de.xml
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
</body></html>
`

**Comment by jmayer** [comment]
`curl https://cdn.ravensburger.de/db/tiptoi.csv`

seems to work.

**Comment by nomeata** [comment]
Ah, we have two download scripts. The ones in `testsuite` use http://catalog.tiptoi.de/tiptoi.json and work, but the one in `scripts` is no longer working. I’m tempted to just remove the `scripts` folder…

**Comment by maehw** [comment]
I've also stumbled across this and I'd also prefer if the broken scripts were removed.

**Comment by azrdev** [comment]
@nomeata  would you mind removing the notice in the README about scripts/update.sh, too?

**Comment by nomeata** [comment]
Thanks, done in 5037aae

**Comment by azrdev** [comment]
np, but that's not on the master branch -- by intention?

**Comment by nomeata** [comment]
No, well spotted! Fixed in d571692
