### ISSUE TITLE
Support both `.yml` and `.yaml` file extension

### ISSUE THREAD

**Issue by cstuder** [entropia/tip-toi-reveng#262]
Assembling a `.yml` file seems to work, but trying to `play` a `.yml` file fails with the error message 

```text
tttool: Trying to read from offset 0x646F7270, mentioned at 0x00000000, which is after the end of the file!
 when reading segment Header
```

The official [YAML FAQ](https://yaml.org/faq.html) asks to use `.yaml`, but the reality is that `.yml` seems to be [more popular](https://stackoverflow.com/questions/21059124/is-it-yaml-or-yml).

I propose that `tttool` should be able to handle both file extension version.

**Comment by nomeata** [comment]
Reasonable. Care to submit a patch? Only this line needs to be changed: https://github.com/entropia/tip-toi-reveng/blob/master/src/Commands.hs#L142

**Comment by cstuder** [comment]
I don't speak Haskell, but I can have a look. (As soon as I manage to reliably print my OID codes....)

**Comment by maehw** [comment]
I can't get the build toolchain run on my current machine (running Mac OS).

Just a guess (no Haskell programmer, too) which I cannot test:

Replace

```
        if ".yaml" `isSuffixOf` file
```

by

```
        if (".yaml" `isSuffixOf` file) || (".yml" `isSuffixOf` file)
```

?

I could submit a pull request for that if that helps reducing the effort for you.

**Comment by nomeata** [comment]
Actually
```
        if ".yaml" `isSuffixOf` file || ".yml" `isSuffixOf` file
```
should work.

I’ll just do it, simpler that way.
