### ISSUE TITLE
wrong oid print

### ISSUE THREAD

**Issue by JacobBaartse** [entropia/tip-toi-reveng#275]
when i use tttool to print the oid 47  dec 323 i get the wrong oid printed, lucky there is the tool at "https://upload.querysave.de/code.html" which i could use to print this oid, which works fine. all the other high number oid's work fine.

**Comment by nomeata** [comment]
Can you say more about how they differ? Is there maybe confusion about raw IDs vs the IDs read by the pen?

**Comment by JacobBaartse** [comment]
I can not reproduce it anymore probably i mixed up some files. 
If i can reproduce it i will log a new issue
