### ISSUE TITLE
tttool closes automatically after start

### ISSUE THREAD

**Issue by Seppi5** [entropia/tip-toi-reveng#276]
Guten Abend,

vor kurzem bin ich auf die Idee gekommen, Audiodateien auf dem Tiptoi Stift zu verändern. Gücklicherweise gibt es dafür Werkzeuge wie das tttool. Leider öffnet sich beim Ausführen der Anwendungsdatei das Befehlsfenster nur ganz kurz und schließt sich sofort wieder automatisch. Ich habe verschiedene Versionen (1.9 und 1.10) auf unterschiedlichen Computern (Windows 7 oder 10) ausprobiert, aber immer dasselbe. Habt ihr eine Idee, was ich falsch mache?

Danke und Gruß,
Seppi

**Comment by nomeata** [comment]
Hallo Seppi,

vermutlich versuchst du das tttool per Doppelklick zu öffnen? So funktioniert das bei einem Kommandozeilentool nicht - da musst du erst die Eingabeaufforderung öffnen, in das richtige Verzeichnis navigieren, und dann befehle wie
```
tttool --help
```
eintippen.

Wenn dir das Konzept neu ist empfiehlt die Doku auf https://tttool.readthedocs.io/de/latest/erste-schritte.html das Tutorial auf https://tutorial.djangogirls.org/de/intro_to_command_line/

**Comment by Seppi5** [comment]
Guten Abend Joachim,

vielen Dank für deine schnelle Hilfe! Ich hatte in diese Anleitungen schon mal reingeschaut, aber nicht kapiert, dass es sich nicht einfach so starten lässt ;-). Das Extrahieren der gme-Datei in einzelne Audios hat funktioniert.

**Comment by nomeata** [comment]
Freut mich dass es jetzt klappt, dann weiter viel Spaß damit!
