### ISSUE TITLE
Suchen_und_Entdecken-Meine_Welt not completely exported

### ISSUE THREAD

**Issue by heili77** [entropia/tip-toi-reveng#280]
Hi there,

I am new to using the tttool. 
I tried to adapt the Book Suchen_und_Entdecken-Meine_Welt. In this book one can search for elements in a picture. The audio is adapted if I tap on the elements to search and on the corresponding element in the picture. If right, there is a success message in the audio. 

Unfortunately the code for this is not contained in the export, so I cannot adapt the book experience.

I see the preparations for this and the information seems to be stored in $3.
```
...
Script for OID 8271:
    $1==1? P(434) $3:=8271 P(435)
Script for OID 8272:
    $1==1? P(436) $3:=8272 P(437)
Script for OID 8273:
    $1==1? P(438) $3:=8273 P(439)
...
```
$3 is never used in my export. The tttool found some holes in the file.
```
Unknown file segments: 8 (1668 bytes total)
   Offset: 000000D0 to 00000200 (304 bytes)
   Offset: 000041AE to 00004612 (1124 bytes)
   Offset: 00D90A26 to 00D90A52 (44 bytes)
   Offset: 00D934E2 to 00D9350A (40 bytes)
   Offset: 00D95662 to 00D9568A (40 bytes)
   Offset: 00D98116 to 00D9813E (40 bytes)
   Offset: 00D9A292 to 00D9A2BA (40 bytes)
   Offset: 00D9CD4E to 00D9CD72 (36 bytes)
```

$1 seems to avoid interruptions while an audio is playing, but the code for that is also missing in the export.

It seems that the `media` command also does not export the success message audio files. Have not found one jet, but there are 563 Elements in the media folder. 

It seems that there are features in the file that are not recognized by the tttool or I am using the tool not right.

Is this a known issue?

**Comment by nomeata** [comment]
It is a known problem that “binaries” (pieces of logic written in machine code) are not understood, and not exported in a way that can be modified. Does this file have binaries?

But they wouldn't be holes. 40 bytes sound like padding, not sure if the 1124 bytes may be a clue…

**Comment by heili77** [comment]
@nomeata I just have the gme file from the pen.
It's a pity that this is not fully editable. Thank you for the explanation.

**Comment by heili77** [comment]
Can I edit the existing gme files or just create a new ones?

**Comment by nomeata** [comment]
you can edit existing GME files, but not always without losing some functionality, unfortunately.

**Comment by MatthiasKohl** [comment]
@nomeata I believe I'm running into the same issue with the book "Suchen_und_Entdecken_Fahrzeuge" (ID 260). Do you know whether something has changed in the latest version of tttool w.r.t. binaries?
I can see that the original book has one binary table, but the exported/assembled gme file doesn't have any.
Is there a way to re-program the logic from the book (it doesn't seem very complicated)? Are you aware of any such effort?

**Comment by nomeata** [comment]
Last year I worked on a branch that might round-trip binaries, see
https://github.com/entropia/tip-toi-reveng/commits/binaries

Maybe try that, if you are able to build from source? I don’t actually remember how far I got with that branch.

**Comment by MatthiasKohl** [comment]
Thanks I'll give it a shot!

**Comment by MatthiasKohl** [comment]
@nomeata thank you so much, it looks like the binaries branch works well with the "Suchen und Entdecken" type books !
I had a small hiccup where it was re-playing the "start" OID on some specific spots in the book (maybe it encountered a bug in the re-assembled file), but it seems to be minor, the overall experience is great.

Thank you for the quick response, and I think it would be great if this could be included in the next release if you feel like it's ready for it :)

**Comment by nomeata** [comment]
> Thank you for the quick response, and I think it would be great if this could be included in the next release if you feel like it's ready for it :)

It’s good to have gotten some testing, thanks for that. This will probably have to wait until I have a quiet day or two where I can re-visit what I was doing back then, and especially what was missing 😅
