### ISSUE TITLE
Not able to assemble with TTS on mac m1

### ISSUE THREAD

**Issue by surfing-atari** [entropia/tip-toi-reveng#287]
When I try to asseble a yaml file including a speak command it wont work and I get following error message:
tttool: pico2wave: runProcess: posix_spawnp: illegal operation (Inappropriate ioctl for device)
Using a ogg file instead of the voice generation it works. Using a macbook (m1) and Ventura 13.2.1.

**Comment by nomeata** [comment]
Thanks for the report! tttool doesn't ship with pico2wave, did you somehow install it yourself? Or maybe the error message is simply very bad, but just means it's not installed?

I don't know how to install stuff on Mac; on Linux (Debian or Ubuntu) you'd install libttspico-utils and vorbis-tool.

**Comment by surfing-atari** [comment]
Thanks for the fast reply. pico2wave was not installed.
