### ISSUE TITLE
Offset after end of file

### ISSUE THREAD

**Issue by uli42** [entropia/tip-toi-reveng#41]
uli@traube:~/work/tiptoi/uli42/tip-toi-reveng-games$ ./decode info Reise\ durch\ die\ Jahreszeiten.gme 
decode: Trying to read from offset 0x007E007D, which is after the end of the file!

007E007d looks like 2 16bit offsets, not one 32bit offset

Happens fpr alle three language versions of this product.

**Comment by nomeata** [comment]
Seems to be fixed somewhen during the last 12 months:

```
$ ./tttool info Reise\ durch\ die\ Jahreszeiten.gme 
Product ID: 10
Raw XOR value: 0x000000A6
Magic XOR value: 0xF7
Comment: CHOMPTECH DATA FORMAT CopyRight 2009 Ver2.4.0316
Date: 20100825
Number of registers: 1
Initial registers: [0]
Initial sounds: [[73,74]]
Scripts for OIDs from 2201 to 2271; 12/71 are disabled.
Audio table entries: 176
Binary tables entries: 0/0/0/0
Checksum found 0x3C8BB3A7, calculated 0x3C8BB3A7
```
