### ISSUE TITLE
Debugger

### ISSUE THREAD

**Issue by nischelwitzer** [entropia/tip-toi-reveng#57]
Hi,

I have tried: tttool create-debug debug.gme 20
but when i use it on the tiptoi it is not working.

I have tried it with Product-ID 20 (Bilderlexikon Tiere) which are the current books you get a McDonalds as far as i know. I am missing something?

Thanks!

**Comment by nomeata** [comment]
A lot has happened since then. Is this still an issue?

**Comment by nomeata** [comment]
The  `tttool debug`  command has been removed in 921d29d, in favor of the Debug.yaml. Closing.
