### ISSUE TITLE
game disassebmly

### ISSUE THREAD

**Issue by m42e** [entropia/tip-toi-reveng#65]
Well this is less an issue but a place to discuss (hopefully, this is ok for you).

I discovered in the file of Erste Buchstaben only one game is recognized but there are several games (21 I think). 

But there are holes (11, one is about 120kB).

Does tttool offer a way of hex dump the unknown parts or also known parts? Would be a nice feature, wouldn't it?

I try to dig a bit deeper into the Erste Buchstaben file and report if I find something interesting.

Bye,
Matthias

**Comment by nomeata** [comment]
Hi. What of this is still  open? It seems that the new `tttool binaries` handles part of what this issue is about.

**Comment by m42e** [comment]
not at the moment, I think.

**Comment by nomeata** [comment]
Closing this issue, as there is not much actionable here. But we are still interested in someone tackling these binaries!
