### ISSUE TITLE
creating OID within tttool

### ISSUE THREAD

**Issue by ghost** [entropia/tip-toi-reveng#69]
For better understanding and generating the OID's for Printing, can you make a matching table,
perhaps as yaml-file for generating the OID-Output? 

Is there perhaps the possability to get some geometric foms for printing like:
square 10 (10mm) oder circle 10 (10mm diameter)? where the forms and measurements are
fixed in the code ...

**Comment by nomeata** [comment]
Sorry, not sure what exactly you want. Und wenns dir lieber ist, gehts auch auf deutsch, bisher haben sich keine nicht-deutschen hier beteiligt :-)

Willst du eine Ausgabe, die auf einem A4 möglichst viele OIDs mit Beschriftung unterbringt, um zu prüfen, welche Tiptoi-Codes dazu gehören?

**Comment by st-germain** [comment]
Ja, schon. Aich wäre es gut, wenn die OID bei der Übersicht ausgegeben wird...
Später, benötigt man ja nur kleine Schnipsel, wie bei Deiner Geschenkeaktion, daher
die Frage nach kleinen Ausgabeformen ...

**Comment by mercedon** [comment]
Hi,
the following bash-script generates a png with 15x23=345 oids. With frames and numbers.
You need Imagemagick installed. Set i_min and i to change the oid range.

#!/bin/bash 
i_min=1
i=345
echo print oid overview $i_min to $i
../tttool oid-code -d 600 $i_min-$i
until [  $i -lt $i_min ]; do
    echo doing oid${i}_tile.png
    convert oid${i}.png -crop 288x288+0+0 +repage oid${i}_tile.png
    convert oid${i}_tile.png -gravity north -stroke none -pointsize 72 -annotate 0 ${i} oid${i}_tile.png
    convert oid${i}_tile.png -shave 1x1 -bordercolor black -border 1 oid${i}_tile.png
let i-=1
done
montage oid*_tile.png -mode Concatenate  -tile 15x  tile_array.png
