### ISSUE TITLE
Product IDs

### ISSUE THREAD

**Issue by Flattermann78** [entropia/tip-toi-reveng#78]
Hi,

could you please provide a short introduction on how to write/create your own TipToi books/games. The movie published is awesome but a more detailed information on how to create non-conflicting product IDs etc. It would be greate to have a short written document that guids you through the process.

**Comment by nomeata** [comment]
A german page with better instructions towards users is in the make at http://entropia.github.io/tip-toi-reveng/ but the section “Die Crux mit den OID-Codes” is not yet written. Pull requests welcome :-)

**Comment by Flattermann78** [comment]
Leider habe ich das noch nicht wirklich verstanden, was schon bekannt und möglich ist. Wenn es mir erklärt wird, schreibe ich es gerne ordentlich auf. Aus dem was ich sehen kann hatte ich das Gefühl, dass du beliebige Product IDs erzeugen kannst. Mir ist aber nicht klar, ob das vom Tool schon unterstützt wird und woher ich das Mapping Product ID zu OID bekomme (also der Nummer, die gedruckt werden muss).

**Comment by nomeata** [comment]
Inzwischen kann das Tool die Zurordnung von Codes wie sie in der YAML-Datei stehen (z.B. 42) zur Nummer die gedruckt werden muss (z.B. 272), und auch der Befehl `tttool oid-codes` erwartet jetzt die gleichen Codes wie in der YAML-Datei , das heißt eigentlich muss man gar nicht mehr wissen dass es verschiedene Nummern gibt.

Ansonsten ist jeder Code <1000 eine mögliche Produkt-Id, und jeder ≥1000 eine normale ID für Skripte.

**Comment by uli42** [comment]
> Ansonsten ist jeder Code <1000 eine mögliche Produkt-Id, und jeder ≥1000
eine normale ID für Skripte.

Wobei ab 999 abwaerts die IDs für die unterschiedlichen Sprachen sind.
Wieviele das sind, ist jedoch unbekannt.

Uli

**Comment by stgermain1** [comment]
Können zum Druckertest das OIDProducer-testpage im Wiki oder im Ordner DOC-verwendet/gespeichert werden (PDF kann nicht hochgeladen werden)?

**Comment by uli42** [comment]
2015-02-10 15:55 GMT+01:00 st germain <notifications@github.com>:
>
> Können zum Druckertest das OIDProducer-testpage im Wiki oder im Ordner DOC-verwendet/gespeichert werden (PDF kann nicht hochgeladen werden)?


Ich denke, wir sollten keine Dateien aus dem OID-Producer-Paket
hochladen. Wenn sie von einem Teilnehmer hier erstellt wurde, ist das
anderes.

Bist du sicher, dass keine PDFs ins Wiki hochgeladen werden können?
Wenn dem so ist, dann dürfte .doc auch nicht gehen.

Uli

**Comment by nomeata** [comment]
Mir ist nicht klar was für dieses Ticket zu tun ist, schleße es daher. Bitte beschweren wenn ich was übersehen hab.
