### ISSUE TITLE
Generate wavs using text-to-speech software

### ISSUE THREAD

**Issue by uli42** [entropia/tip-toi-reveng#79]
Add a switch for the assemble command that generates wav files on the fly. This way you could hold all your text in the yaml file without maintaining any wav/mp3/oggs. Perfect during
testing/development. After you are satisfied with your yaml you cold
still create better sound files.

Here's the content of the mail I wrote that describes what needs to be done:

To make experimenting a bit easier and save some time I played around
with text-to-speech software. This is a little example how to use
text-to-speech software to generate your wavs using Ubuntu:

1. sudo apt-get install libttspico-utils
2. pico2wave -l en-GB -w cool.wav "tiptoi is cool"

-> you'll find cool.wav which you can listen to with play.

For conversion to .ogg I found dir2ogg:

1. dir2ogg *.wav
2. rm *.wav (tttool will complain if it finds both)

For the okto1 example yaml file (see below) you can this:

--------------------------------------------------------------
#!/bin/bash
for i in homer marge lisa bart grandpa; do
   pico2wave -l en-US -w $i.wav $i
done

pico2wave -l de-DE -w hallo.wav hallo
pico2wave -l de-DE -w Richtig.wav richtig
pico2wave -l de-DE -w falsch.wav falsch
pico2wave -l de-DE -w WoBarnius.wav "Wo ist Barnius"
--------------------------------------------------------------

$ cat okto1.yaml
--------------------------------------------------------------
product-id: 42
comment: test
init: $mode:=0

welcome: hallo

scripts:
  8066:
  - $mode==0? $mode:=1 P(WoBarnius)
  - $mode==1? $mode:=0 P(grandpa)
  8067:
  - $mode==0? P(homer)
  - $mode==1? P(Falsch)
  8068:
  - $mode==0? P(marge)
  - $mode==1? P(Richtig)
  8069:
  - $mode==0? P(bart)
  - $mode==1? P(Falsch)
  8070:
  - $mode==0? P(lisa)
  - $mode==1? P(Falsch)
--------------------------------------------------------------

**Comment by nomeata** [comment]
This generates a 16000Hz file, while we thought that the pen expects 22050Hz. Did you try it with 16000Hz? Did it work?

**Comment by nomeata** [comment]
Bitteschön :-)

**Comment by uli42** [comment]
I have tried with the files that pico2wav spit out and it worked!

Uli

On Wed, Jan 21, 2015 at 10:21 PM, Joachim Breitner <notifications@github.com
