### ISSUE TITLE
create-debug is broken

### ISSUE THREAD

**Issue by uli42** [entropia/tip-toi-reveng#80]
I have several issues with tttool crete-debug:

1.

uli@traube:~/work/tiptoi/tip-toi-reveng$ ./tttool create-debug debug42.gme 42Stack space overflow: current size 8388608 bytes.
Use `+RTS -Ksize -RTS' to increase it.

OK, so I tried that:
uli@traube:~/work/tiptoi/tip-toi-reveng$ ./tttool +RTS -K10000 -RTS create-debug debug42.gme 42
tttool: Most RTS options are disabled. Link with -rtsopts to enable them.

Ok, I have added -rtsopts to tttool.cabal. I'll make a pull request for this.

2. I'd like to generate the yaml-file for the debug file. Due to the issue above I am not sure if this is created. If not, there should be a way to only generate the yaml file. 

3. I'd like to create a text-to-speech debug version in German. Seems like this is not possible currently. Maybe a better way was to create a yaml file the user may adjust to his liking and in a second step use that yaml file to create the debug gme.

**Comment by nomeata** [comment]
> I'd like to generate the yaml-file for the debug file. Due to the issue above I am not sure if this is created. If not, there should be a way to only generate the yaml file. 

The debug file feature predates the YAML file format, so it currently generates the GME only. But you can simply run export on the GME, can’t you? But it would lose the names of the audio samples...

> I'd like to create a text-to-speech debug version in German. 

I’ll add that functionaly when I add a language field to the yam file, and I want to do that once the language header information is properly understood and documented.

BTW, why not simply add a `debug.yaml` file to the repository, with nice comments, and where the user simply changes the product-id? This should be at least as good as the current `create-debug` command, and probably easier to understand. Plus I could remove code from `tttool`, which would be good :-)

**Comment by uli42** [comment]
On Mon, Jan 26, 2015 at 11:34 PM, Joachim Breitner <notifications@github.com
> wrote:

> I'd like to generate the yaml-file for the debug file. Due to the issue
> above I am not sure if this is created. If not, there should be a way to
> only generate the yaml file.
>
> The debug file feature predates the YAML file format, so it currently
> generates the GME only. But you can simply run export on the GME, can’t
> you? But it would lose the names of the audio samples...
>
> I'd like to create a text-to-speech debug version in German.
>
> I’ll add that functionaly when I add a language field to the yam file, and
> I want to do that once the language header information is properly
> understood and documented.
>
​I now have managed to build a debug42-german.gme​ by renaming my digit
files to english-<1-9>.ogg


> BTW, why not simply add a debug.yaml file to the repository, with nice
> comments, and where the user simply changes the product-id? This should be
> at least as good as the current create-debug command, and probably easier
> to understand. Plus I could remove code from tttool, which would be good
> :-)
>
> ​I'd  be fine with that. Building the yaml from hand will be a lot of work
(because of > 15000 OIDs) so we'll have to generate that programatically​.
I do not know the internal handling in tttool but do you think you could
simply dump that yaml once before removing the create-debug code?

​Uli​
