### ISSUE TITLE
Ignore this [images for wiki]

### ISSUE THREAD

**Issue by B-G-T** [entropia/tip-toi-reveng#82]
![PCB overview](https://cloud.githubusercontent.com/assets/6303021/5909915/28065c3e-a5b5-11e4-84c3-bcb93c5d6bab.jpg)
![left part of PCB](https://cloud.githubusercontent.com/assets/6303021/5909955/8dec3a1e-a5b5-11e4-9ec2-7ce338ac11a9.jpg)
![right](https://cloud.githubusercontent.com/assets/6303021/5909970/b113b6fc-a5b5-11e4-8fbd-47c433c06f64.jpg)

**Comment by B-G-T** [comment]
![ZC90B - pin4](https://cloud.githubusercontent.com/assets/6303021/5910076/cbf5a0a6-a5b6-11e4-9ee6-3108a1c4f2c1.png)
![ZC90B - pin7](https://cloud.githubusercontent.com/assets/6303021/5910108/204bb050-a5b7-11e4-86dd-d9112a0e1b91.png)

**Comment by B-G-T** [comment]
![led flash](https://cloud.githubusercontent.com/assets/6303021/5910182/ac68188a-a5b7-11e4-8090-0da07a4374b9.png)

**Comment by B-G-T** [comment]
![newfile1](https://cloud.githubusercontent.com/assets/6303021/5927382/6a7fdeec-a672-11e4-83b9-9b2712ca2bf4.png)

**Comment by B-G-T** [comment]
![Tiptoi PCB back side](https://cloud.githubusercontent.com/assets/6303021/6091853/051aae6e-aec0-11e4-95d3-6fd14e4cb3ee.jpg)

**Comment by B-G-T** [comment]
![storage boot windows](https://cloud.githubusercontent.com/assets/6303021/6094668/8e8628c6-af34-11e4-8e17-63ef2af71007.gif)
![storage boot pads](https://cloud.githubusercontent.com/assets/6303021/6094671/a39409c2-af34-11e4-8dc1-a68e617538de.jpg)

**Comment by B-G-T** [comment]
![tiptoi-4g-frontside](https://cloud.githubusercontent.com/assets/6303021/6306394/88476610-b933-11e4-946e-32baa63ea3ab.jpg)
![tiptoi-4g-backside](https://cloud.githubusercontent.com/assets/6303021/6306397/94943b5a-b933-11e4-9d2a-180674618de8.jpg)

**Comment by B-G-T** [comment]
![stips-1](https://cloud.githubusercontent.com/assets/6303021/6585121/2918b07c-c770-11e4-9009-7d4b2a9bcc20.jpg)
![stips-2](https://cloud.githubusercontent.com/assets/6303021/6585146/4ef26d60-c770-11e4-904c-07984ca7a178.jpg)
![stips-3](https://cloud.githubusercontent.com/assets/6303021/6585130/3803810c-c770-11e4-824b-855eafd1449a.jpg)

**Comment by B-G-T** [comment]
![rt1](https://cloud.githubusercontent.com/assets/6303021/7400811/d3db6bdc-eebf-11e4-8d12-2a4ea7db61ef.jpg)

**Comment by B-G-T** [comment]
![rt1](https://cloud.githubusercontent.com/assets/6303021/7401115/de24633a-eec1-11e4-8ced-8bce48484f00.jpg)

**Comment by B-G-T** [comment]
![a4_front_meta](https://cloud.githubusercontent.com/assets/6303021/11637874/590dbcd4-9d24-11e5-9c74-2b9de0e0331b.jpg)
![a4_back_meta](https://cloud.githubusercontent.com/assets/6303021/11637884/61e3328a-9d24-11e5-8a6c-05dcce3eb808.jpg)

**Comment by B-G-T** [comment]
Content of EEPROM 27C02 from Rev B6 (4GB):
[EEPROM 2.txt](https://github.com/entropia/tip-toi-reveng/files/101807/EEPROM.2.txt)

**Comment by B-G-T** [comment]
![tiptoi-b5-front1](https://cloud.githubusercontent.com/assets/6303021/21908022/645f1f3a-d912-11e6-8781-e048087f9806.jpg)
![tiptoi-b5-back2](https://cloud.githubusercontent.com/assets/6303021/21908023/6628fc00-d912-11e6-9143-6ad331328342.jpg)

**Comment by B-G-T** [comment]
![tt r5 front](https://cloud.githubusercontent.com/assets/6303021/21908420/f70e5002-d913-11e6-98eb-a0ccf99ac5a4.jpg)
![tt r5 back](https://cloud.githubusercontent.com/assets/6303021/21908425/f9f543ca-d913-11e6-8f78-c8503731f379.jpg)
![tt r5 keypad](https://cloud.githubusercontent.com/assets/6303021/21908427/fc1bd7ae-d913-11e6-87c5-c2ed9f9093b8.jpg)

**Comment by B-G-T** [comment]
![SOC](https://user-images.githubusercontent.com/6303021/67005746-9932da80-f0e3-11e9-9efd-ff5635b9aa95.jpg)
![Audio Amplifier](https://user-images.githubusercontent.com/6303021/67005747-9932da80-f0e3-11e9-8c7b-571761364cb3.jpg)
![Crypto IC](https://user-images.githubusercontent.com/6303021/67005748-99cb7100-f0e3-11e9-8afe-9e52ef4ee54e.jpg)
![EEPROM](https://user-images.githubusercontent.com/6303021/67005749-99cb7100-f0e3-11e9-98d6-2a24f3af0613.jpg)
![Flash](https://user-images.githubusercontent.com/6303021/67005750-99cb7100-f0e3-11e9-932e-b074b31fd0cb.jpg)
![OID Decoder](https://user-images.githubusercontent.com/6303021/67005751-99cb7100-f0e3-11e9-8f97-a7bc4d0f1e60.jpg)

**Comment by B-G-T** [comment]
![GPIO13, RESET](https://user-images.githubusercontent.com/6303021/77105010-3b514880-6a1d-11ea-991f-743c07136f38.jpg)

**Comment by B-G-T** [comment]
![GPIO9](https://user-images.githubusercontent.com/6303021/77105055-4f954580-6a1d-11ea-9cb9-768a70ab5c7f.jpg)

**Comment by B-G-T** [comment]
![GPIO12](https://user-images.githubusercontent.com/6303021/77105098-5f148e80-6a1d-11ea-8b4f-e2f5b20febd7.jpg)

**Comment by B-G-T** [comment]
![1742R6 - back](https://user-images.githubusercontent.com/6303021/77254452-51e7e180-6c61-11ea-9584-c74862749ab3.jpg)
![1742R6 - front](https://user-images.githubusercontent.com/6303021/77254454-557b6880-6c61-11ea-8ff6-9016d88b6a74.jpg)

**Comment by B-G-T** [comment]
![2182R1 - front](https://user-images.githubusercontent.com/6303021/77255069-223ad880-6c65-11ea-9719-07a743c145ce.jpg)
![2182R1 - back](https://user-images.githubusercontent.com/6303021/77255071-2535c900-6c65-11ea-90b4-2219e152389e.jpg)

**Comment by B-G-T** [comment]
![B5 - front](https://user-images.githubusercontent.com/6303021/77257037-1efa1980-6c72-11ea-8190-3eb74141bd9f.jpg)
![B5 - back](https://user-images.githubusercontent.com/6303021/77257039-21f50a00-6c72-11ea-92e1-b1fb4b1295eb.jpg)

**Comment by B-G-T** [comment]
![B6 - front](https://user-images.githubusercontent.com/6303021/77257328-d5aac980-6c73-11ea-9ca4-c0b7147ff0ef.jpg)
![B6 - back](https://user-images.githubusercontent.com/6303021/77257330-d8a5ba00-6c73-11ea-8201-f010f3d76f93.jpg)

**Comment by B-G-T** [comment]
![Standard boot GPIO13](https://user-images.githubusercontent.com/6303021/97111499-5dabf280-16df-11eb-853f-6caee22549ea.png)

**Comment by B-G-T** [comment]
![Pushbutton (front)](https://user-images.githubusercontent.com/6303021/100771036-380cba00-33fe-11eb-9940-1e5c2f29999e.jpg)

**Comment by B-G-T** [comment]
![Pushbutton (back)](https://user-images.githubusercontent.com/6303021/100771106-4bb82080-33fe-11eb-9ac5-f97fcf55922b.jpg)

**Comment by maehw** [comment]
Thank you for the high-res pictures of the power button PCB. They are way better than mine.
By the way, it also worked to drag & drop images, you don't need actually store the comment.
However, it may be a good way to see the history.

**Comment by B-G-T** [comment]
Actually I planned to write some explanation in the Wiki and was pretty surprised when I saw in edit mode that there was already a perfect explanation.  So obviously we worked on it in parallel! :-)

**Comment by maehw** [comment]
Yes, sorry for the interference. I just found another broken pen in my inventory yesterday where I could take some photos from today. Can you still add some details? I'm pretty sure that the button connects pins 1 and 2 and the LED is between pins 3 and 4. A little schematic would be nice. But of course, it's not required at all.

**Comment by B-G-T** [comment]
![Test1 bin statistic](https://user-images.githubusercontent.com/6303021/102666462-46413100-4187-11eb-92b3-c1b284cc40c2.PNG)

**Comment by uli42** [comment]
Als ich zuletzt Bilder ins wikie eingestellt hab, könnte man die einfacmit
frag and drop in den Editor ziehen, IIRC.

B-G-T <notifications@github.com> schrieb am Fr., 18. Dez. 2020, 23:18:
