### ISSUE TITLE
Rewrite play commands in tttool

### ISSUE THREAD

**Issue by uli42** [entropia/tip-toi-reveng#88]
We now have 5 play commands;
 * `FFE0` (written `P()`: play one random sample of the media list
 * `FFE1` (written `P()`: play all samples of the media list
 * `FFE8` (written `P(m)`): Play audio referenced by the `m`th entry in the indices list.
 * `FB00` (written `P(b-a)`): Play all samples from that inclusive range. `a` := lowbyte(`m`), `b` := highbyte(`m`)
 * `FC00` (written `P(b-a)`): Play one random sample from that inclusive range. `a` := lowbyte(`m`), `b` := highbyte(`m`)

First implement the missing ones, then change code to make them distinguishable in the yaml file. Maybe implement some generic play command that resolves to the one of the known commands that fits best (as the current implementation does).

**Comment by nomeata** [comment]
Thanks for opening a ticket, and thanks for the concise overview. Thats much easier for me to play with.

For most uses of the `tttool`, a single play command is enough, as it is now. That would be `EFE8` and `FC00`. Since users of the tttool do not control the indices list directly, the others would be hard to use, and unless we find more differences (e.g. whether they are replayable or not), I don’t see much value in having an input syntax for them.

But it would still be nice if upon export, one can tell that they are different. So I need to come up with a syntax for them anyways, and we might then as well accept them as input syntax.

Proposal:
 * `FFE0`: `PR(*)`
 * `FFE1` : `P(*)`
 * `FFE8`: `P(one)`
 * `FB00`: `P(one, two, three)`
 * `FC00`: `PR(one, two, three)`

**Comment by uli42** [comment]
We could also use more selfexplaining command names, e.g. PlayRandom() and Play().

**Comment by nomeata** [comment]
Given that most of the scripts are play commands, I like the brief variants....

**Comment by nomeata** [comment]
I’m thinking more about the implementation of this. The problem with using `P(*)` for `FFE1` is: Where would the media file ids actually be printed. For the export, this is a loss of information; for the input this would actually be impossible.

So it should be included in the command syntax somehow. But what should the input

    P(one) P*(two, three)

(where `P` is `FFE8` and `P*` is `FFE0`) be compiled to? If `FFE0` refers to the whole media list, then there is no place for the `one`.

I would suspect that the variants `FFE0` and `FFE1` occur never together with other commands that refer the media list. In that case, `tttool` would simply reject that input.

**Comment by uli42** [comment]
Well, that P* example cannot exist in a gme file so tttool should simply reject it as input.

**Comment by nomeata** [comment]
Ok, I’m convinced. I’ll add it together with the new timer command before the next release.

**Comment by nomeata** [comment]
Hmm, wanted to do this right now, but there is a problem left. I’d like to use this syntax:
```
    FFE0: PR*(one,two,three)
    FFE1 : P*(one,two,three)
    FFE8: P(one)
    FB00: P(one, two, three)
    FC00: PR(one, two, three)
```
where the variants with `*`must be the only play command in a certain line.

But this would change the existing `P(one,two,three)` syntax, which currently is for random play.

How important is backward compatibility here? Is it more important than a consistent and sensible syntax?

**Comment by uli42** [comment]
On Sun, Jan 17, 2016 at 7:11 PM, Joachim Breitner
<notifications@github.com> wrote:
>
> Hmm, wanted to do this right now, but there is a problem left. I’d like to use this syntax:
>
>     FFE0: PR*(one,two,three)
>     FFE1 : P*(one,two,three)
>     FFE8: P(one)
>     FB00: P(one, two, three)
>     FC00: PR(one, two, three)
>
> where the variants with *must be the only play command in a certain line.
>
> But this would change the existing P(one,two,three) syntax, which currently is for random play.
>
> How important is backward compatibility here? Is it more important than a consistent and sensible syntax?

Hmm, as this would lead to unexpected behaviour when recompiling
existing projects and would confuse new users that read old mails or
howtos I would say we should not break that. What about changing or
adding some other field in the yaml syntax so that the code is able to
distinguish old and new sematics? E.g. we could introduce an "options:
newsyntax" field.

Uli

**Comment by nomeata** [comment]
> What about changing or adding some other field in the yaml syntax so that the code is able to distinguish old and new sematics? E.g. we could introduce an "options: newsyntax" field.

Nah, too complicated for the user, too much to explain, too much code to maintain.

I guess we have to be more creative with the syntax.

Maybe

    FFE0: PR*(one,two,three)
    FFE1: P*(one,two,three)
    FFE8: P(one)
    FB00: PA(one, two, three)
    FC00: P(one, two, three)

Note that `PR*`, `P*` and `PA` (play all) are only of interest to the file format hackage, the usual user who creates his own products only needs the existing two `P` variants anyways, so it does not matter that `PA` is a bit weird, and `PR*` a bit inconsistent.

**Comment by nomeata** [comment]
What are the register and literal argument to `FFE0` and `FFE0`

**Comment by nomeata** [comment]
Implemented, assuming the literal argument is always `0`. Can you test this?

**Comment by uli42** [comment]
not at the moment, will take some time... sorry.

**Comment by nomeata** [comment]
According to Daniel Karasek on the mailing list, `FFE0` can occur with a non-zero argument.
