### ISSUE TITLE
Moving all shell, or other "tools" to a new folder?

### ISSUE THREAD

**Issue by stgermain1** [entropia/tip-toi-reveng#90]
Hallo Joachim,
immer mehr Skripte (gerne auch das von Daniela) kommen hinzu. Manche sind im "main"-Folder
vom Git, andere haben einen eigenen "Sub-folder".
Was hälst Du von einer "Restrukturierung" dieser Skripte?

**Comment by uli42** [comment]
2015-02-16 9:45 GMT+01:00 st germain <notifications@github.com>:

> Hallo Joachim,
> immer mehr Skripte (gerne auch das von Daniela) kommen hinzu. Manche sind
> im "main"-Folder
> vom Git, andere haben einen eigenen "Sub-folder".
> Was hälst Du von einer "Restrukturierung" dieser Skripte?
>
>
​Da das derzeit alles work-in-progress ist, ist eine Strukturierung
schwierig. Hast du Ideen, wie wir das umbauen könnten/sollten?

Uli

**Comment by nomeata** [comment]
Ja, aufräumen tät not. Auch die ganzen beispielhaften `.yaml`-Dateien könnten zusammengefasst werden. Anderes würde ich gern rausschmeißen, wie die `matlab`, um es etwas übersichtlicher zu machen.

Die `transsript`-Sache hat auch nicht wirklich Fahrt aufgenommen...

**Comment by maehw** [comment]
matlab kann gerne raus, da hast du recht. ;)

**Comment by nomeata** [comment]
Hat jemand einen konkreten Vorschlag für eine bessere Repo-Organisation? Und vielleicht einer Liste von Sachen die raus können?
