### ISSUE TITLE
TOC auf den wiki-Seiten

### ISSUE THREAD

**Issue by maehw** [entropia/tip-toi-reveng#92]
Hi!

Gibt es eine Möglichkeit TOCs (table of content), als Inhaltsverzeichnisse in die wiki-Seiten einzubinden? Kenne mich leider zu wenig mit markdown aus, aber das scheint von der Sprache selbst nicht unterstützt zu werden.
IMHO werden Seiten wie diese https://github.com/entropia/tip-toi-reveng/wiki/Hardware schnell unübersichtlich.

**Comment by B-G-T** [comment]
Am 20.02.2015 um 21:16 schrieb maehw:
>
> Hi!
>
> Gibt es eine Möglichkeit TOCs (table of content), als 
> Inhaltsverzeichnisse in die wiki-Seiten einzubinden? Kenne mich leider 
> zu wenig mit markdown aus, aber das scheint von der Sprache selbst 
> nicht unterstützt zu werden.
> IMHO werden Seiten wie diese 
> https://github.com/entropia/tip-toi-reveng/wiki/Hardware schnell 
> unübersichtlich.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/entropia/tip-toi-reveng/issues/92>.
>

Hi,

du kannst TOCs wohl leider nur manuell erzeugen und dann mit Links 
versehen, also in der Art wie z. B.

-----
Jump to
   - [Revision 
A](https://github.com/entropia/tip-toi-reveng/wiki/Hardware#revision-a)
   - [Revision 
B](https://github.com/entropia/tip-toi-reveng/wiki/Hardware#revision-b)
-----

VG
Björn

**Comment by uli42** [comment]
2015-02-20 21:23 GMT+01:00 B-G-T <notifications@github.com>:
> > Gibt es eine Möglichkeit TOCs (table of content), als
> > Inhaltsverzeichnisse in die wiki-Seiten einzubinden? Kenne mich leider
> > zu wenig mit markdown aus, aber das scheint von der Sprache selbst
> > nicht unterstützt zu werden.
> > IMHO werden Seiten wie diese
> > https://github.com/entropia/tip-toi-reveng/wiki/Hardware schnell
> > unübersichtlich.

Ja, TOCs wären echt hilfreich.

> du kannst TOCs wohl leider nur manuell erzeugen und dann mit Links
> versehen, also in der Art wie z. B.
>
> -----
> Jump to
> - [Revision
> A](https://github.com/entropia/tip-toi-reveng/wiki/Hardware#revision-a)
> - [Revision
> B](https://github.com/entropia/tip-toi-reveng/wiki/Hardware#revision-b)
> -----
>

Man kann auch das Wiki per git clone auf seine Platte holen und dann
darin automatisiert ein TOP generieren und das dann hochladen. Aber
das geht dem Sinn eines Wiki zuwider.

Für Tabellen hab ich übrigens auch nichts gefunden, das markdown-Wiki
ist doch recht eingeschränkt.

Uli

**Comment by Ol-li** [comment]
Hi,

Laut dem hier

http://sourceforge.net/p/forge/documentation/markdown_syntax/#md_ex_tables

müsste eine Tabelle so gehen:

First Header | Second Header
------------- | -------------
Content Cell | Content Cell
Content Cell | Content Cell

Wenn das nicht geht würde ich es mal mit HTML Tags TR und TD probieren.

Ol-li

Am 20. Februar 2015 22:25:53 MEZ, schrieb uli42 <notifications@github.com>:

**Comment by uli42** [comment]
2015-02-20 22:40 GMT+01:00 Ol-li <notifications@github.com>:

> müsste eine Tabelle so gehen:
>
> First Header | Second Header
> ------------- | -------------
> Content Cell | Content Cell
> Content Cell | Content Cell
>
> Wenn das nicht geht würde ich es mal mit HTML Tags TR und TD probieren.

Yep, das geht. Ist auch hier beschrieben, nur in der markdown-Hilfe
beim Editieren nicht:
https://help.github.com/articles/github-flavored-markdown/

Danke,

Uli

**Comment by nomeata** [comment]
Ich schließe das mal, ist ja schon bald ein Jahr alt.
