### ISSUE TITLE
Find out text representation/description oid 

### ISSUE THREAD

**Issue by dafenix** [entropia/tip-toi-reveng#93]
Is it possible to extract the description of existing oids in a yaml file? 
For example 10306: # Europlocephalus

**Comment by nomeata** [comment]
In what you quote, `# Europlocephalus` is a comment, so it is ignored by any program processing yaml files. You could still hack something with perl or such...

But maybe you can elaborate a bit what you are trying to achieve?

**Comment by dafenix** [comment]
I saw the video with selfmade animals and want to achieve the same. How can i find out which oid is a start oid from a specific animal(original animals have this on there body)? I have a handcraftet giraffe and try to figure out which oid is the right one to print and map to the original giraffe media. Is it possible to get the oid code description like the comment u have made in the yam files from the tttool?

**Comment by nomeata** [comment]
According to `templates/Spielfiguren3.yaml`, the codes 10229 and 10230 are used for giraffes.

**Comment by dafenix** [comment]
works! Thank you
