### ISSUE TITLE
Neuer "Simulate"-Modus ?

### ISSUE THREAD

**Issue by stgermain1** [entropia/tip-toi-reveng#96]
Um die gme-Datei testen zu können, muss diese
immer wieder mit assemble gebaut und nach dem Assemble immer wieder 
auf den Stift kopiert werden. Dies finde ich sehr hinderlich. Ich habe einen alten Stift,
der dann immer abgeklemmt und gestartet werden muss.
 
Schöner wäre, den richtigen Sound direkt zu hören, nach dem man den 
OID-Gewählt hat (simulate) wäre dann ein Modus, so dass die yaml-Datei erst gar nicht
in das gme-Format "komprimiert" werden müsste?

Dabei kam die Frage auf:
Könnte das tttool auch mit https://www.libsdl.org zusammenarbeiten?

Ein workaround ist für Windows:
1. Download der Daten für die ogg-decodierung notwendig: 
    DirectShow Plugin: http://xiph.org/dshow/
2. Media-Player aus yaml-Datei aufrufen über: "FQ-Pfad zum WMP"  "AudioDatei" 
     Mittels https://msdn.microsoft.com/en-us/library/windows/desktop/dd562731(v=vs.85).aspx 
     kann geprüft werden, ob der Windows-Media-Player (WMP) installiert ist.

**Comment by nomeata** [comment]
Das sind eigentlich mehre Wünsche hier:

 * Der `play`-Befehl sollte auch YAML-Dateien lesen können. Das ist kein Problem.
 * Das Abspielen von Audio-Dateien unter Windows.

Wenn ich den Media-Player aufrufe, dann kommt doch ein Fenster und so? Das wär doch nicht schön.

Vielleicht wäre es einfacher wenn das `tttool` eine HTML-Datei erzeugt, die man im Browser bedient, mit Knöpfen statt OIDs eingeben. Dort sollte das Abspielen von Audio-Dateien zuverlässig funktionieren. Wär etwas mehr Arbeit, aber sehr nützlich.

**Comment by stgermain1** [comment]
Ja, der `Play`-Befehl kann ja bleiben... Ich habe nun mit dem `sox` weiter rumprobiert:
nach dem ich nun den SOX neu heruntergeladen und die `ogg`-Decodierungen installiert habe:
http://xiph.org/dshow/

kann ich nun auf auf der Windows-Kommdline die Ogg-Dateien wie folgt abspielen:
`F:\tip-toi-reveng\Software\Programme\sox-14.4.2-win32\sox-14.4.2>play "F:\tip-toi-reveng\media\027\00522 - Mission im Lesedschunge
l\20120118\Mission im Lesedschungel_0.ogg" -t waveaudio`
![2015-04-13 22_54_56-c__windows_system32_cmd exe - play _f__tip-toi-reveng_media_027_00522 - mission](https://cloud.githubusercontent.com/assets/10942697/7125319/301fedb0-e230-11e4-81f8-dacbaaed98df.png)
Nun stünde einem echten Kommdaline-Simulation (ohne lästiges Assemble dazwischen) nichts im Wege,oder?

Die Idee mit der statischen HTML finde ich auch nicht schlecht/hilfreich.
Alles was halt das assemble zum Testen/ersten Durchspielen des Projektes überflüssig macht ;)

**Comment by nomeata** [comment]
Das ist schonmal sehr schön. Noch besser wäre es, wenn man nichts extra installieren müsste und ich sox sagen könnte wo er die Ogg-Codecs findet.

Oder noch besser: Ich liefer ja eh schon oggenc mit, da kann ich ja auch einfach oggdec mitliefern und dem sox dann eine Wave-Datei liefern. Die wird sox ja wohl hoffentlich out-of-the-box abspielen können...

**Comment by stgermain1** [comment]
Ja, das stimmt. 

Man muss doch nix installieren, nur den sox-entpacken. Umbenennen brauch man den `sox` auch nicht. In der aktuellen `sox`-Version sind die notwendigen Windows dll's (libogg/libvorbis?) schon enthalten. 

Ich hatte eine ältere Version (<= *14.4.2* ), daher habe ich die https://www.libsdl.org nach installiert.

Ja, der `sox` die kann er dann ohne weiteres abspielen. Habe es auf einer neuen win7-VM getestet.

**Comment by nomeata** [comment]
Verstehe ich das richtig dass man das DirectShow Plugin von http://xiph.org/dshow/ doch nicht installieren muss, um direkt .ogg-Datein abspielen zu können?

**Comment by stgermain1** [comment]
Jepp, genau.... Denn die dll's sind im aktuellen `sox`-Packet (windows zip-File) enthalten

**Comment by LordJakson** [comment]
Was ist mit mp3 und wav Dateien? Die sind mir auch schon untergekommen.
