### ISSUE TITLE
Nummern der Sounds ändern sich nach Export -> Assemble

### ISSUE THREAD

**Issue by LordJakson** [entropia/tip-toi-reveng#98]
Das TTTool ist echt super weiter so.

Ich hab gerade angefangen mich mit der "WWW Bauernhof.gme" zu spielen.
Dabei ist mir aufgefallen das wenn ich die Datei mit Export in eine Yaml Konvertiere und ohne etwas zu ändern wieder mit Assemble eine Gme Datei erstelle ändern sich die Nummern der Sounds.
Überprüft hab ich das mit dem Kommando Play.

Das liegt vermutlich daran das bei den Sounds in der Gme Datei keine Namen oder Nummern mit abgespeichert werden und die einfach nur den Array Index bekommen.
Ist es möglich die Sounds wider in der alten Reihenfolge zu speichern?

Außerdem ist mir aufgefallen das sich die Anzahl der Media Dateien geändert hat. Zuerst waren es 620 jetzt nur mehr 428.
Hab ich da was falsch gemacht?

**Comment by nomeata** [comment]
`tttool yaml` schreibt die Audio-Dateien in relativ zufälliger Reihenfolge raus, da ist klar dass die Nummern sich ändern.

Auch ist nicht verwunderlich dass manche Dateien fehlen: Die wurden wohl nur in den Spielen referenziert und gingen mit denen verloren.

Warum wäre die Reihenfolge wichtig? Ohne guten Grund neige ich dazu, das so zu lassen.

**Comment by LordJakson** [comment]
Ich hab die Transcript Datei vom Bauernhof bis zur Nummer 200 fertig.
Jetzt wollt ich eben mit "Play" nachschauen was er bei welchem Code abspielen würde und hab mich gewundert das da nichts mehr zusammenpasst.

Soweit ich das verstanden habe gibt es in der GME Datei immer noch Bereiche die nicht verstanden werden.

Meine Überlegung war dass bei Export alle Dateien beim Export in ein Projektverzeichnis geschrieben werden.
Sound in Media
Spiele in Game als *.bin und so weiter.

Beim erstellen der GME Datei können dadurch wieder alle Teile zusammengefügt werden ohne das etwas verloren geht.

Jetzt ist es nicht möglich die "WWW Bauernhof.gme" zu exportieren, einen Sound zu ändern und wieder eine GME zu erstellen ohne das etwas verloren geht.

**Comment by nomeata** [comment]
Implemented in 08c6b4ee6cef6502a2a8c05dd00c4dbc0b39b09a
